import { connect } from 'node:net';
import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import Redis from 'ioredis';
import { Queue } from 'bullmq';
import { z } from 'zod';
import { encryptSecret, normalizeEmail } from '@zerochack/auth';
import { database, databaseHealthcheck } from '@zerochack/database';
import type { Prisma } from '@prisma/client';
import type { Environment } from '@zerochack/config';
import type { EmailProvider } from '@zerochack/email';
import { ApiError } from '../../errors.js';
import { authenticate, requireOwnerMfa, requirePermission } from '../auth/security.js';
import { parse } from '../auth/routes.js';
import { issueAuthToken, writeAudit } from '../auth/service.js';

const uuid = z.string().uuid(); const queueNames = ['default','email','notifications','scans','monitoring','backups','reports','ai'] as const;
const securityFixPriceInput=z.object({key:z.string().trim().regex(/^[a-z0-9-]+$/u).max(80),name:z.string().trim().min(2).max(120),description:z.string().trim().min(1).max(5000),scope:z.enum(['ISSUE','TASK','PROJECT']),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).nullable().optional(),owaspCategory:z.string().trim().max(64).nullable().optional(),cwe:z.string().trim().max(32).nullable().optional(),matchTerms:z.array(z.string().trim().min(2).max(80)).max(30).default([]),includedWork:z.array(z.string().trim().min(2).max(240)).min(1).max(30),priceMinor:z.number().int().min(0).max(2_000_000_000),currency:z.string().trim().length(3).transform((value)=>value.toUpperCase()),estimatedHours:z.number().int().min(1).max(10_000).nullable().optional(),priority:z.number().int().min(-10_000).max(10_000).default(0),active:z.boolean().default(true)});
function owner(request: FastifyRequest, permission = 'users.read') { requireOwnerMfa(request); requirePermission(request, permission); }
const safeMetadata = (value: unknown): unknown => { if (Array.isArray(value)) return value.map(safeMetadata); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key,item]) => [key, /password|token|secret|credential|private.?key|api.?key|authorization/iu.test(key) ? '[REDACTED]' : safeMetadata(item)])); return value; };
const packageSnapshot = (version: { id:string; version:number; name:string; description:string; priceMinor:number; currency:string; billingInterval:string; trialDays:number; websiteLimit:number; scanLimit:number; monitoringIntervalMinutes:number; backupFrequencyHours:number; backupRetentionDays:number; warrantyDays:number; aiRequestLimit:number; aiCostLimitMicros:number; supportLevel:string; featureEntitlements:Prisma.JsonValue }): Prisma.InputJsonObject => ({ packageVersionId:version.id,version:version.version,name:version.name,description:version.description,priceMinor:version.priceMinor,currency:version.currency,billingInterval:version.billingInterval,trialDays:version.trialDays,websiteLimit:version.websiteLimit,scanLimit:version.scanLimit,monitoringIntervalMinutes:version.monitoringIntervalMinutes,backupFrequencyHours:version.backupFrequencyHours,backupRetentionDays:version.backupRetentionDays,warrantyDays:version.warrantyDays,aiRequestLimit:version.aiRequestLimit,aiCostLimitMicros:version.aiCostLimitMicros,supportLevel:version.supportLevel,featureEntitlements:version.featureEntitlements as Prisma.InputJsonValue});
async function smtpHealth(environment: Environment): Promise<'HEALTHY'|'FAILED'> { return new Promise((resolve) => { const socket = connect({ host: environment.SMTP_HOST, port: environment.SMTP_PORT }); const timer = setTimeout(() => { socket.destroy(); resolve('FAILED'); }, 1500); socket.once('connect', () => { clearTimeout(timer); socket.destroy(); resolve('HEALTHY'); }); socket.once('error', () => { clearTimeout(timer); resolve('FAILED'); }); }); }
async function systemHealth(environment: Environment) {
  const redis = new Redis(environment.REDIS_URL, { lazyConnect: true, maxRetriesPerRequest: 1, connectTimeout: 1500 }); let databaseStatus: string='FAILED', redisStatus: string='FAILED', worker: string='FAILED', queues: Record<string,unknown>={}, scheduler: string='FAILED';
  try { await databaseHealthcheck(); databaseStatus='HEALTHY'; } catch { /* real failure */ }
  try { await redis.connect(); await redis.ping(); redisStatus='HEALTHY'; const heartbeat=await redis.get('zerochack:worker:heartbeat'); worker=heartbeat && Date.now()-new Date(heartbeat).getTime()<90_000?'HEALTHY':'FAILED'; const details: Record<string,unknown>={}; let schedulers=0; for(const name of queueNames){ const queue=new Queue(name,{connection:redis}); try { details[name]=await queue.getJobCounts('waiting','active','delayed','failed'); schedulers+=(await queue.getJobSchedulers(0,100)).length; } finally { await queue.close(); } } queues=details; scheduler=schedulers>0?'HEALTHY':'DEGRADED'; } catch { queues={ status:'FAILED' }; } finally { redis.disconnect(); }
  const [payments, ai, integrations, email, latestScan] = await Promise.all([database.paymentProviderConfig.findMany({ where:{enabled:true},select:{name:true,healthStatus:true,lastHealthCheckAt:true} }),database.aiProvider.findMany({where:{enabled:true},select:{name:true,healthStatus:true,lastHealthCheckAt:true}}),database.platformIntegration.findMany({where:{enabled:true},select:{type:true,name:true,healthStatus:true,lastHealthCheckAt:true}}),smtpHealth(environment),database.scan.findFirst({where:{status:{in:['SUCCEEDED','FAILED']}},orderBy:{completedAt:'desc'},select:{status:true,completedAt:true,errorCode:true}})]);
  const scanHealth=!latestScan?'UNKNOWN':latestScan.status==='FAILED'?'FAILED':latestScan.completedAt&&Date.now()-latestScan.completedAt.getTime()<=86_400_000?'HEALTHY':'DEGRADED';
  const integration=(type:string)=>integrations.filter((item)=>item.type===type); return { checkedAt:new Date(), services:{ api:'HEALTHY',database:databaseStatus,redis:redisStatus,workers:worker,queues,scheduler,email,payments:payments.length?payments:'NOT_CONFIGURED',ai:ai.length?ai:'NOT_CONFIGURED',securityEngines:{status:scanHealth,lastExecutionAt:latestScan?.completedAt??null,errorCode:latestScan?.errorCode??null,implemented:['tls','http-headers']},storage:integration('STORAGE').length?integration('STORAGE'):'NOT_CONFIGURED',webSockets:integration('WEBSOCKET').length?integration('WEBSOCKET'):'NOT_CONFIGURED' } };
}

export const ownerRoutes: FastifyPluginAsync<{environment:Environment;email:EmailProvider}> = async(app,{environment,email})=>{
  app.addHook('preHandler',(request)=>authenticate(request,environment)); app.addHook('onSend',async(_request,reply)=>{void reply.header('cache-control','private, no-store');});
  app.get('/owner/control/overview',async(request)=>{owner(request); const [users,tenants,websites,tickets,subscriptions,pendingApprovals,alerts]=await Promise.all([database.user.count(),database.tenant.count(),database.website.count({where:{lifecycle:'ACTIVE'}}),database.ticket.count({where:{status:{notIn:['CLOSED','CANCELLED']}}}),database.subscription.count({where:{status:{in:['TRIALING','ACTIVE','PAST_DUE','PAUSED']}}}),database.user.count({where:{status:'PENDING_APPROVAL'}}),database.securityAlert.count({where:{status:'OPEN'}})]);return{users,tenants,websites,openTickets:tickets,subscriptions,pendingApprovals,openSecurityAlerts:alerts};});
  app.get('/owner/control/:section',async(request)=>{owner(request); const section=parse(z.enum(['users','tenants','websites','specialists','tickets','subscriptions','packages','pricing','quotes','revenue','affiliates','commissions','payouts','backups','monitoring','security','notifications','email-automation','ai-gateway','integrations','audit-logs','settings']), (request.params as {section?:string}).section); const query=parse(z.object({search:z.string().trim().max(200).optional(),status:z.string().trim().max(80).optional(),take:z.coerce.number().int().min(1).max(500).default(100)}),request.query); const search=query.search;
    if(section==='users')return{records:await database.user.findMany({where:{...(query.status?{status:query.status as never}:{}),...(search?{OR:[{email:{contains:search,mode:'insensitive'}},{displayName:{contains:search,mode:'insensitive'}}]}:{})},select:{id:true,email:true,displayName:true,status:true,emailVerifiedAt:true,createdAt:true,userRoles:{select:{tenantId:true,role:{select:{name:true}}}},_count:{select:{sessions:{where:{revokedAt:null}}}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='tenants')return{records:await database.tenant.findMany({where:search?{OR:[{name:{contains:search,mode:'insensitive'}},{slug:{contains:search,mode:'insensitive'}}]}:{},select:{id:true,name:true,slug:true,createdAt:true,_count:{select:{memberships:true,websites:true,subscriptions:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='websites')return{records:await database.website.findMany({where:search?{OR:[{name:{contains:search,mode:'insensitive'}},{normalizedHost:{contains:search,mode:'insensitive'}}]}:{},select:{id:true,tenantId:true,name:true,url:true,lifecycle:true,connectionStatus:true,securityStatus:true,monitoringStatus:true,backupStatus:true,lastScanAt:true,tenant:{select:{name:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='specialists')return{records:await database.user.findMany({where:{userRoles:{some:{role:{name:'Cybersecurity Specialist'}}},...(query.status?{status:query.status as never}:{})},select:{id:true,email:true,displayName:true,status:true,createdAt:true,_count:{select:{assignedTickets:{where:{status:{notIn:['CLOSED','CANCELLED']}}},remediationRuns:true}}},take:query.take})};
    if(section==='tickets'){const [records,specialists]=await Promise.all([database.ticket.findMany({where:{...(query.status?{status:query.status as never}:{}),...(search?{title:{contains:search,mode:'insensitive'}}:{})},include:{website:{select:{name:true}},assignedSpecialist:{select:{displayName:true,email:true}}},take:query.take,orderBy:{createdAt:'desc'}}),database.user.findMany({where:{status:'APPROVED',userRoles:{some:{role:{name:'Cybersecurity Specialist'}}}},select:{id:true,displayName:true,email:true},orderBy:{displayName:'asc'}})]);return{records,specialists};}
    if(section==='subscriptions'){const where={...(query.status?{status:query.status as never}:{}),...(search?{OR:[{planName:{contains:search,mode:'insensitive' as const}},{tenant:{name:{contains:search,mode:'insensitive' as const}}}]}:{})};const [records,tenants,packageVersions]=await Promise.all([database.subscription.findMany({where,include:{tenant:{select:{name:true}},packageVersion:{select:{version:true}},providerConfig:{select:{name:true}}},take:query.take,orderBy:{createdAt:'desc'}}),database.tenant.findMany({where:{userRoles:{some:{role:{name:'Customer'}}}},select:{id:true,name:true,userRoles:{where:{role:{name:'Customer'}},select:{user:{select:{email:true,displayName:true}}},take:1}},orderBy:{name:'asc'}}),database.packageVersion.findMany({where:{package:{archivedAt:null}},select:{id:true,version:true,name:true,priceMinor:true,currency:true,billingInterval:true,trialDays:true,package:{select:{key:true}}},orderBy:[{name:'asc'},{version:'desc'}]})]);return{records,tenants,packageVersions};}
    if(section==='packages')return{records:await database.commercialPackage.findMany({include:{versions:{orderBy:{version:'desc'}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='pricing'){const[securityFixPrices,securityFixOrders,paymentProviders]=await Promise.all([database.securityFixPrice.findMany({where:{archivedAt:null},include:{_count:{select:{orders:true}}},orderBy:[{active:'desc'},{priority:'desc'},{createdAt:'desc'}],take:query.take}),database.securityFixOrder.findMany({include:{tenant:{select:{name:true}},website:{select:{name:true}},ticket:{select:{id:true,status:true,assignedSpecialistId:true}}},orderBy:{createdAt:'desc'},take:query.take}),database.paymentProviderConfig.findMany({select:{id:true,name:true,adapterKey:true,enabled:true,healthStatus:true}})]);return{securityFixPrices,securityFixOrders,paymentProviders};}
    if(section==='quotes')return{records:await database.quote.findMany({include:{tenant:{select:{name:true}},agencyTenant:{select:{name:true}},lineItems:true},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='revenue'){const rows=await database.paymentTransaction.groupBy({by:['currency'],where:{status:{in:['SUCCEEDED','PARTIALLY_REFUNDED','REFUNDED']}},_sum:{amountMinor:true},_count:true});return{records:rows};}
    if(section==='affiliates')return{records:await database.affiliateProfile.findMany({include:{user:{select:{email:true,displayName:true,status:true}},_count:{select:{attributions:true,conversions:true,commissions:true,payouts:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='commissions')return{records:await database.affiliateCommission.findMany({where:query.status?{status:query.status as never}:{},include:{affiliate:{select:{code:true}},conversion:{select:{recurringPeriod:true,paymentTransactionId:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='payouts')return{records:await database.affiliatePayout.findMany({where:query.status?{status:query.status as never}:{},include:{affiliate:{select:{code:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='backups')return{records:await database.backup.findMany({include:{website:{select:{name:true}}},take:query.take,orderBy:{requestedAt:'desc'}}),policies:await database.backupPolicy.findMany({take:query.take})};
    if(section==='monitoring')return{checks:await database.monitoringCheck.findMany({include:{website:{select:{name:true}},tenant:{select:{name:true}}},take:query.take,orderBy:{startedAt:'desc'}}),policies:await database.monitoringPolicy.findMany({take:query.take})};
    if(section==='security')return{events:await database.securityEvent.findMany({include:{website:{select:{name:true}},evidence:true,alerts:true},take:query.take,orderBy:{lastSeenAt:'desc'}})};
    if(section==='notifications')return{records:await database.notification.findMany({include:{tenant:{select:{name:true}}},take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='email-automation')return{integrations:await database.platformIntegration.findMany({where:{type:'EMAIL'},select:{id:true,type:true,name:true,adapterKey:true,enabled:true,configuration:true,healthStatus:true,lastHealthCheckAt:true,updatedAt:true}})};
    if(section==='ai-gateway')return{providers:await database.aiProvider.findMany({include:{models:true,credentials:{select:{id:true,label:true,enabled:true,healthStatus:true,keyVersion:true,lastUsedAt:true}}}}),usage:await database.aiUsage.findMany({take:query.take,orderBy:{createdAt:'desc'}})};
    if(section==='integrations')return{generic:await database.platformIntegration.findMany({select:{id:true,type:true,name:true,adapterKey:true,enabled:true,configuration:true,healthStatus:true,lastHealthCheckAt:true,createdAt:true,updatedAt:true}}),payments:await database.paymentProviderConfig.findMany({select:{id:true,name:true,adapterKey:true,enabled:true,healthStatus:true,lastHealthCheckAt:true}}),ai:await database.aiProvider.findMany({select:{id:true,name:true,adapterKey:true,enabled:true,healthStatus:true,lastHealthCheckAt:true}})};
    if(section==='audit-logs')return{records:(await database.auditLog.findMany({where:{...(query.status?{action:{contains:query.status,mode:'insensitive'}}:{}),...(search?{OR:[{action:{contains:search,mode:'insensitive'}},{resourceType:{contains:search,mode:'insensitive'}},{resourceId:{contains:search,mode:'insensitive'}}]}:{})},take:query.take,orderBy:{createdAt:'desc'}})).map((item)=>({...item,metadata:safeMetadata(item.metadata)}))};
    return{records:await database.systemSetting.findMany({select:{id:true,key:true,value:true,description:true,securityInvariant:true,updatedAt:true},orderBy:{key:'asc'}})};
  });
  app.get('/owner/control/system-health',async(request)=>{owner(request,'system.health.read');return systemHealth(environment);});
  app.post('/owner/control/subscriptions',async(request,reply)=>{owner(request,'commercial.manage');const input=parse(z.object({tenantId:uuid,packageVersionId:uuid,status:z.enum(['TRIALING','ACTIVE']),trialEndsAt:z.coerce.date().optional(),currentPeriodEnd:z.coerce.date().optional()}),request.body);const now=new Date();if(input.status==='TRIALING'&&input.trialEndsAt&&input.trialEndsAt<=now)throw new ApiError(400,'TRIAL_END_INVALID','Trial end must be in the future');if(input.currentPeriodEnd&&input.currentPeriodEnd<=now)throw new ApiError(400,'PERIOD_END_INVALID','Current period end must be in the future');const [tenant,version,existing]=await Promise.all([database.tenant.findFirst({where:{id:input.tenantId,userRoles:{some:{role:{name:'Customer'}}}},select:{id:true,name:true}}),database.packageVersion.findFirst({where:{id:input.packageVersionId,package:{archivedAt:null}}}),database.subscription.findFirst({where:{tenantId:input.tenantId,status:{in:['TRIALING','ACTIVE','PAST_DUE','PAUSED']}}})]);if(!tenant)throw new ApiError(404,'CUSTOMER_TENANT_NOT_FOUND','Customer organization was not found');if(!version)throw new ApiError(404,'PACKAGE_VERSION_NOT_FOUND','Published package version was not found');if(existing)throw new ApiError(409,'SUBSCRIPTION_ALREADY_EXISTS','This customer already has a current subscription');const created=await database.subscription.create({data:{tenantId:tenant.id,packageVersionId:version.id,planName:version.name,priceMinor:version.priceMinor,currency:version.currency,billingInterval:version.billingInterval,termsSnapshot:packageSnapshot(version),status:input.status,...(input.status==='TRIALING'?{trialEndsAt:input.trialEndsAt??new Date(now.getTime()+Math.max(1,version.trialDays||14)*86_400_000)}:{}),...(input.currentPeriodEnd?{currentPeriodEnd:input.currentPeriodEnd}:{})}});await writeAudit({tenantId:tenant.id,actorUserId:request.userId,requestId:request.id,action:'owner.subscription_provisioned',resourceType:'subscription',resourceId:created.id,ipAddress:request.ip,metadata:{packageVersionId:version.id,status:input.status,manual:true}});return reply.code(201).send(created);});
  app.patch('/owner/control/subscriptions/:subscriptionId',async(request)=>{owner(request,'commercial.manage');const id=parse(uuid,(request.params as {subscriptionId?:string}).subscriptionId);const input=parse(z.object({status:z.enum(['ACTIVE','PAUSED','CANCELLED','EXPIRED']).optional(),packageVersionId:uuid.optional(),currentPeriodEnd:z.coerce.date().nullable().optional()}).refine((value)=>Object.keys(value).length>0),request.body);const subscription=await database.subscription.findUnique({where:{id}});if(!subscription)throw new ApiError(404,'SUBSCRIPTION_NOT_FOUND','Subscription was not found');if(subscription.providerConfigId||subscription.providerReference)throw new ApiError(409,'PROVIDER_SUBSCRIPTION_MANAGED_EXTERNALLY','Provider-managed subscriptions must be changed through the payment provider workflow');if(['CANCELLED','EXPIRED'].includes(subscription.status))throw new ApiError(409,'SUBSCRIPTION_FINAL','A cancelled or expired subscription cannot be edited');if(input.currentPeriodEnd&&input.currentPeriodEnd<=new Date())throw new ApiError(400,'PERIOD_END_INVALID','Current period end must be in the future');const version=input.packageVersionId?await database.packageVersion.findFirst({where:{id:input.packageVersionId,package:{archivedAt:null}}}):null;if(input.packageVersionId&&!version)throw new ApiError(404,'PACKAGE_VERSION_NOT_FOUND','Published package version was not found');const updated=await database.subscription.update({where:{id},data:{...(input.status?{status:input.status}:{}),...(input.currentPeriodEnd!==undefined?{currentPeriodEnd:input.currentPeriodEnd}:{}),...(input.status==='CANCELLED'?{cancelledAt:new Date()}:{}),...(version?{packageVersionId:version.id,planName:version.name,priceMinor:version.priceMinor,currency:version.currency,billingInterval:version.billingInterval,termsSnapshot:packageSnapshot(version)}:{})}});await writeAudit({tenantId:subscription.tenantId,actorUserId:request.userId,requestId:request.id,action:'owner.subscription_changed',resourceType:'subscription',resourceId:id,ipAddress:request.ip,metadata:{fromStatus:subscription.status,toStatus:input.status,packageVersionId:input.packageVersionId,periodChanged:input.currentPeriodEnd!==undefined,manual:true}});return updated;});
  app.delete('/owner/control/subscriptions/:subscriptionId',async(request)=>{owner(request,'commercial.manage');const id=parse(uuid,(request.params as {subscriptionId?:string}).subscriptionId);const subscription=await database.subscription.findUnique({where:{id},include:{_count:{select:{invoices:true,transactions:true}}}});if(!subscription)throw new ApiError(404,'SUBSCRIPTION_NOT_FOUND','Subscription was not found');if(subscription.providerConfigId||subscription.providerReference||subscription._count.invoices||subscription._count.transactions)throw new ApiError(409,'SUBSCRIPTION_HISTORY_PROTECTED','Subscriptions linked to a provider, payment, or invoice cannot be removed; cancel them instead');await database.subscription.delete({where:{id}});await writeAudit({tenantId:subscription.tenantId,actorUserId:request.userId,requestId:request.id,action:'owner.subscription_removed',resourceType:'subscription',resourceId:id,ipAddress:request.ip,metadata:{planName:subscription.planName,status:subscription.status,manual:true}});return{removed:true};});
  app.post('/owner/control/security-fix-prices',async(request,reply)=>{owner(request,'commercial.manage');const input=parse(securityFixPriceInput,request.body);if(input.scope!=='PROJECT'&&!input.severity&&!input.owaspCategory&&!input.cwe&&!input.matchTerms.length)throw new ApiError(400,'MATCH_RULE_REQUIRED','Issue and task prices need at least one severity, OWASP, CWE, or keyword match rule');const created=await database.securityFixPrice.create({data:{key:input.key,name:input.name,description:input.description,scope:input.scope,severity:input.severity??null,owaspCategory:input.owaspCategory??null,cwe:input.cwe??null,matchTerms:input.matchTerms,includedWork:input.includedWork,priceMinor:input.priceMinor,currency:input.currency,estimatedHours:input.estimatedHours??null,priority:input.priority,active:input.active,createdByUserId:request.userId!}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'security_fix_price.created',resourceType:'security_fix_price',resourceId:created.id,ipAddress:request.ip,metadata:{key:created.key,scope:created.scope,priceMinor:created.priceMinor,currency:created.currency}});return reply.code(201).send(created);});
  app.patch('/owner/control/security-fix-prices/:priceId',async(request)=>{owner(request,'commercial.manage');const id=parse(uuid,(request.params as {priceId?:string}).priceId);const input=parse(securityFixPriceInput.partial().refine((value)=>Object.keys(value).length>0),request.body);const current=await database.securityFixPrice.findFirst({where:{id,archivedAt:null}});if(!current)throw new ApiError(404,'SECURITY_FIX_PRICE_NOT_FOUND','Security fix price was not found');const mergedScope=input.scope??current.scope;const mergedTerms=input.matchTerms??current.matchTerms;const mergedSeverity=input.severity!==undefined?input.severity:current.severity;const mergedOwasp=input.owaspCategory!==undefined?input.owaspCategory:current.owaspCategory;const mergedCwe=input.cwe!==undefined?input.cwe:current.cwe;if(mergedScope!=='PROJECT'&&!mergedSeverity&&!mergedOwasp&&!mergedCwe&&!mergedTerms.length)throw new ApiError(400,'MATCH_RULE_REQUIRED','Issue and task prices need at least one matching rule');const changes=Object.fromEntries(Object.entries(input).filter(([,value])=>value!==undefined)) as Prisma.SecurityFixPriceUncheckedUpdateInput;const updated=await database.securityFixPrice.update({where:{id},data:changes});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'security_fix_price.changed',resourceType:'security_fix_price',resourceId:id,ipAddress:request.ip,metadata:{changedFields:Object.keys(input),active:updated.active,priceMinor:updated.priceMinor,currency:updated.currency}});return updated;});
  app.delete('/owner/control/security-fix-prices/:priceId',async(request)=>{owner(request,'commercial.manage');const id=parse(uuid,(request.params as {priceId?:string}).priceId);const current=await database.securityFixPrice.findFirst({where:{id,archivedAt:null}});if(!current)throw new ApiError(404,'SECURITY_FIX_PRICE_NOT_FOUND','Security fix price was not found');const updated=await database.securityFixPrice.update({where:{id},data:{active:false,archivedAt:new Date()}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'security_fix_price.archived',resourceType:'security_fix_price',resourceId:id,ipAddress:request.ip,metadata:{key:current.key,historicalOrdersPreserved:true}});return{removed:true,archivedAt:updated.archivedAt};});
  app.get('/owner/control/audit-logs/export',async(request,reply)=>{owner(request,'audit.read');const rows=await database.auditLog.findMany({take:5000,orderBy:{createdAt:'desc'}});const csv=['timestamp,action,resourceType,resourceId,requestId,metadata',...rows.map((row)=>[row.createdAt.toISOString(),row.action,row.resourceType,row.resourceId??'',row.requestId,JSON.stringify(safeMetadata(row.metadata)??{})].map((value)=>`"${String(value).replaceAll('"','""')}"`).join(','))].join('\n');reply.header('content-type','text/csv; charset=utf-8').header('content-disposition','attachment; filename="zerochack-audit.csv"');return csv;});
  app.get('/owner/control/users/:userId',async(request)=>{owner(request);const id=parse(uuid,(request.params as {userId?:string}).userId);const user=await database.user.findUnique({where:{id},select:{id:true,email:true,displayName:true,status:true,emailVerifiedAt:true,createdAt:true,memberships:{include:{tenant:true}},userRoles:{include:{role:true}},sessions:{select:{id:true,createdAt:true,lastSeenAt:true,expiresAt:true,revokedAt:true,ipAddress:true,userAgent:true}}}});if(!user)throw new ApiError(404,'USER_NOT_FOUND','User not found');return user;});
  app.post('/owner/control/specialists',async(request,reply)=>{owner(request,'roles.manage');const input=parse(z.object({email:z.email().max(320),displayName:z.string().trim().min(2).max(120)}),request.body);const address=normalizeEmail(input.email);if(await database.user.findUnique({where:{email:address},select:{id:true}}))throw new ApiError(409,'ACCOUNT_EXISTS','An account with this email already exists');const role=await database.role.findFirst({where:{name:'Cybersecurity Specialist',tenantId:null},select:{id:true}});if(!role)throw new ApiError(500,'RBAC_NOT_INITIALIZED','Cybersecurity Specialist role is unavailable');const created=await database.$transaction(async(transaction)=>{const user=await transaction.user.create({data:{email:address,displayName:input.displayName,status:'APPROVED',emailVerifiedAt:new Date()}});await transaction.tenantMembership.create({data:{tenantId:request.tenantId!,userId:user.id,status:'ACTIVE'}});await transaction.userRole.create({data:{tenantId:request.tenantId!,userId:user.id,roleId:role.id}});await transaction.auditLog.create({data:{tenantId:request.tenantId!,actorUserId:request.userId!,requestId:request.id,action:'owner.specialist_created',resourceType:'user',resourceId:user.id,ipAddress:request.ip,metadata:{role:'Cybersecurity Specialist'}}});return user;});const token=await issueAuthToken(created.id,'PASSWORD_RESET',environment.RESET_TOKEN_TTL_MINUTES,environment);let inviteSent=true;try{await email.send({to:created.email,subject:'Your ZeroRoot specialist account',text:`A ZeroRoot owner created a Cybersecurity Specialist account for you. Set your password: ${environment.APP_URL}/reset-password?token=${encodeURIComponent(token)}\nThis link expires in ${environment.RESET_TOKEN_TTL_MINUTES} minutes.`,idempotencyKey:`specialist-invite-${created.id}`});}catch(error){inviteSent=false;request.log.error({err:error,errorCode:'SPECIALIST_INVITE_DELIVERY_FAILED',userId:created.id},'owner.specialist_invite.failed');}return reply.code(201).send({id:created.id,email:created.email,displayName:created.displayName,status:created.status,inviteSent});});
  app.delete('/owner/control/specialists/:specialistId',async(request)=>{owner(request,'roles.manage');const id=parse(uuid,(request.params as {specialistId?:string}).specialistId);const specialist=await database.user.findFirst({where:{id,userRoles:{some:{role:{name:'Cybersecurity Specialist'}}}},include:{userRoles:{include:{role:true}}}});if(!specialist)throw new ApiError(404,'SPECIALIST_NOT_FOUND','Cybersecurity specialist was not found');const [tickets,sessions,support]=await Promise.all([database.ticket.count({where:{assignedSpecialistId:id,status:{notIn:['RESOLVED','CLOSED','CANCELLED']}}}),database.remediationSession.count({where:{specialistId:id,status:'ACTIVE',expiresAt:{gt:new Date()}}}),database.supportConversation.count({where:{assignedSpecialistId:id,status:{not:'CLOSED'}}})]);if(tickets||sessions||support)throw new ApiError(409,'SPECIALIST_HAS_ACTIVE_WORK','Reassign or close the specialist’s active tickets, remediation sessions, and support conversations before removal',{tickets,sessions,support});const specialistRoleIds=specialist.userRoles.filter((item)=>item.role.name==='Cybersecurity Specialist').map((item)=>item.roleId);const hasOtherRole=specialist.userRoles.some((item)=>item.role.name!=='Cybersecurity Specialist');await database.$transaction(async(transaction)=>{await transaction.userRole.deleteMany({where:{userId:id,roleId:{in:specialistRoleIds}}});await transaction.session.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date(),revokedReason:'specialist_access_removed'}});if(!hasOtherRole){await transaction.user.update({where:{id},data:{status:'DEACTIVATED'}});await transaction.tenantMembership.updateMany({where:{userId:id},data:{status:'SUSPENDED'}});}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'owner.specialist_removed',resourceType:'user',resourceId:id,ipAddress:request.ip,metadata:{historicalRecordsPreserved:true,accountDeactivated:!hasOtherRole}});return{removed:true,accountDeactivated:!hasOtherRole};});
  app.post('/owner/control/users/:userId/revoke-sessions',async(request)=>{owner(request,'users.suspend');const id=parse(uuid,(request.params as {userId?:string}).userId);if(id===request.userId)throw new ApiError(400,'SELF_REVOCATION_FORBIDDEN','Use account session controls for your own session');const result=await database.session.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date(),revokedReason:'owner_revocation'}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'owner.user_sessions_revoked',resourceType:'user',resourceId:id,ipAddress:request.ip,metadata:{count:result.count}});return{revoked:result.count};});
  app.patch('/owner/control/tickets/:ticketId',async(request)=>{owner(request,'tickets.assign');const id=parse(uuid,(request.params as {ticketId?:string}).ticketId);const input=parse(z.object({assignedSpecialistId:uuid.optional(),escalate:z.boolean().optional()}).refine((v)=>v.assignedSpecialistId!==undefined||v.escalate===true),request.body);if(input.assignedSpecialistId){const specialist=await database.user.findFirst({where:{id:input.assignedSpecialistId,status:'APPROVED',userRoles:{some:{role:{name:'Cybersecurity Specialist'}}}}});if(!specialist)throw new ApiError(404,'SPECIALIST_NOT_FOUND','Active specialist was not found');}const ticket=await database.ticket.update({where:{id},data:{...(input.assignedSpecialistId?{assignedSpecialistId:input.assignedSpecialistId,assignedAt:new Date()}:{}),...(input.escalate?{status:'ESCALATED',escalatedAt:new Date()}: {})}});await writeAudit({tenantId:ticket.tenantId,actorUserId:request.userId,requestId:request.id,action:input.escalate?'owner.ticket_escalated':'owner.ticket_transferred',resourceType:'ticket',resourceId:id,ipAddress:request.ip,metadata:{assignedSpecialistId:input.assignedSpecialistId}});return ticket;});
  app.put('/owner/control/settings/:key',async(request)=>{owner(request,'settings.manage');const key=parse(z.enum(['defaultMonitoringIntervalMinutes','defaultBackupRetentionDays','notificationCooldownMinutes','emailAutomationEnabled']),(request.params as {key?:string}).key);const value=parse(z.union([z.boolean(),z.number().int().min(1).max(100000)]),request.body && (request.body as {value?:unknown}).value);const existing=await database.systemSetting.findUnique({where:{key}});if(existing?.securityInvariant)throw new ApiError(403,'SECURITY_INVARIANT_PROTECTED','Security invariants cannot be changed through ordinary settings');const setting=await database.systemSetting.upsert({where:{key},create:{key,value,description:`Owner-managed ${key}`,changedByUserId:request.userId!},update:{value,changedByUserId:request.userId!}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'system.setting_changed',resourceType:'system_setting',resourceId:setting.id,ipAddress:request.ip,metadata:{key}});return{...setting,value:safeMetadata(setting.value)};});
  app.post('/owner/control/integrations',async(request,reply)=>{owner(request,'integrations.manage');const input=parse(z.object({type:z.enum(['EMAIL','STORAGE','SECURITY_ENGINE','WEBSOCKET']),name:z.string().trim().min(2).max(120),adapterKey:z.string().trim().min(2).max(100),enabled:z.boolean(),credentials:z.string().min(1).max(20000).optional(),configuration:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).default({})}),request.body);const created=await database.platformIntegration.create({data:{type:input.type,name:input.name,adapterKey:input.adapterKey,enabled:input.enabled,configuration:input.configuration,changedByUserId:request.userId!,...(input.credentials?{encryptedCredentials:encryptSecret(input.credentials,environment.INTEGRATION_CREDENTIAL_ENCRYPTION_KEY)}:{}),healthStatus:input.enabled?'UNKNOWN':'NOT_CONFIGURED'},select:{id:true,type:true,name:true,adapterKey:true,enabled:true,configuration:true,healthStatus:true,createdAt:true}});await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'integration.created',resourceType:'platform_integration',resourceId:created.id,ipAddress:request.ip,metadata:{type:input.type,adapterKey:input.adapterKey,enabled:input.enabled,credentialsProvided:Boolean(input.credentials)}});return reply.code(201).send(created);});
  app.patch('/owner/control/integrations/:integrationId',async(request)=>{owner(request,'integrations.manage');const id=parse(uuid,(request.params as {integrationId?:string}).integrationId);const input=parse(z.object({enabled:z.boolean().optional(),credentials:z.string().min(1).max(20000).optional(),configuration:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).optional()}).refine((v)=>Object.keys(v).length>0),request.body);const result=await database.platformIntegration.updateMany({where:{id},data:{changedByUserId:request.userId!,...(input.enabled!==undefined?{enabled:input.enabled,healthStatus:input.enabled?'UNKNOWN':'NOT_CONFIGURED'}:{}),...(input.credentials?{encryptedCredentials:encryptSecret(input.credentials,environment.INTEGRATION_CREDENTIAL_ENCRYPTION_KEY),healthStatus:'UNKNOWN'}:{}),...(input.configuration?{configuration:input.configuration}:{})}});if(!result.count)throw new ApiError(404,'INTEGRATION_NOT_FOUND','Integration not found');await writeAudit({tenantId:request.tenantId,actorUserId:request.userId,requestId:request.id,action:'integration.changed',resourceType:'platform_integration',resourceId:id,ipAddress:request.ip,metadata:{enabled:input.enabled,credentialsRotated:Boolean(input.credentials)}});return database.platformIntegration.findUnique({where:{id},select:{id:true,type:true,name:true,adapterKey:true,enabled:true,configuration:true,healthStatus:true,lastHealthCheckAt:true,updatedAt:true}});});
};
