import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';

export interface ObjectStorage { put(key: string, data: Uint8Array, contentType: string): Promise<void>; get(key: string): Promise<Uint8Array>; delete(key: string): Promise<void>; }
export type BackupIdentity = Readonly<{ tenantId: string; websiteId: string; backupId: string; ticketId?: string }>;
export type BackupArtifact = Readonly<{ reference: string; integrityHash: string; sizeBytes: number; providerKey: string; encryption: { algorithm: 'AES-256-GCM'; keyId: string } }>;
export interface BackupSource { export(input: BackupIdentity): Promise<Uint8Array>; restore(input: BackupIdentity, plaintext: Uint8Array): Promise<void>; }
export interface BackupKeyManager { activeKey(tenantId: string): Promise<{ keyId: string; key: Uint8Array }>; key(tenantId: string, keyId: string): Promise<Uint8Array>; }
export interface BackupProvider { readonly providerKey: string; createBackup(input: BackupIdentity): Promise<BackupArtifact>; verifyBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<boolean>; restoreBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<void>; deleteBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<void>; revokeTemporaryAccess?(input: { sessionId: string; ticketId: string }): Promise<void>; }

type Envelope = { version: 1; keyId: string; iv: string; tag: string; ciphertext: string };
const aad = (input: BackupIdentity) => Buffer.from(`${input.tenantId}\0${input.websiteId}\0${input.backupId}`);
const hash = (value: Uint8Array) => createHash('sha256').update(value).digest('hex');
function parseEnvelope(bytes: Uint8Array): Envelope { const parsed = JSON.parse(Buffer.from(bytes).toString('utf8')) as Partial<Envelope>; if (parsed.version !== 1 || !parsed.keyId || !parsed.iv || !parsed.tag || !parsed.ciphertext) throw new Error('BACKUP_ENVELOPE_INVALID'); return parsed as Envelope; }
function assertKey(key: Uint8Array): Buffer { if (key.byteLength !== 32) throw new Error('BACKUP_KEY_INVALID'); return Buffer.from(key); }

/** Encrypts before ObjectStorage receives any bytes and binds ciphertext to tenant, website, and backup IDs. */
export class EncryptedBackupProvider implements BackupProvider {
  readonly providerKey: string;
  constructor(private readonly storage: ObjectStorage, private readonly source: BackupSource, private readonly keys: BackupKeyManager, providerKey = 'encrypted-object-storage') { this.providerKey = providerKey; }
  private objectKey(input: BackupIdentity): string { return `tenants/${input.tenantId}/websites/${input.websiteId}/backups/${input.backupId}.zcb`; }
  async createBackup(input: BackupIdentity): Promise<BackupArtifact> { const plaintext = await this.source.export(input); const active = await this.keys.activeKey(input.tenantId); const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', assertKey(active.key), iv); cipher.setAAD(aad(input)); const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]); const envelope: Envelope = { version: 1, keyId: active.keyId, iv: iv.toString('base64url'), tag: cipher.getAuthTag().toString('base64url'), ciphertext: ciphertext.toString('base64url') }; const encoded = Buffer.from(JSON.stringify(envelope)); const reference = this.objectKey(input); await this.storage.put(reference, encoded, 'application/vnd.zerochack.encrypted-backup+json'); const artifact = { reference, integrityHash: hash(encoded), sizeBytes: encoded.byteLength, providerKey: this.providerKey, encryption: { algorithm: 'AES-256-GCM' as const, keyId: active.keyId } }; if (!await this.verifyBackup(input, artifact)) throw new Error('BACKUP_VERIFICATION_FAILED'); return artifact; }
  async verifyBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<boolean> { if (artifact.providerKey !== this.providerKey || artifact.encryption.algorithm !== 'AES-256-GCM') return false; const encoded = await this.storage.get(artifact.reference); if (hash(encoded) !== artifact.integrityHash) return false; const envelope = parseEnvelope(encoded); if (envelope.keyId !== artifact.encryption.keyId) return false; try { const key = await this.keys.key(input.tenantId, envelope.keyId); const decipher = createDecipheriv('aes-256-gcm', assertKey(key), Buffer.from(envelope.iv, 'base64url')); decipher.setAAD(aad(input)); decipher.setAuthTag(Buffer.from(envelope.tag, 'base64url')); decipher.update(Buffer.from(envelope.ciphertext, 'base64url')); decipher.final(); return true; } catch { return false; } }
  async restoreBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<void> { const encoded = await this.storage.get(artifact.reference); if (hash(encoded) !== artifact.integrityHash) throw new Error('BACKUP_INTEGRITY_MISMATCH'); const envelope = parseEnvelope(encoded); const key = await this.keys.key(input.tenantId, envelope.keyId); const decipher = createDecipheriv('aes-256-gcm', assertKey(key), Buffer.from(envelope.iv, 'base64url')); decipher.setAAD(aad(input)); decipher.setAuthTag(Buffer.from(envelope.tag, 'base64url')); const plaintext = Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext, 'base64url')), decipher.final()]); await this.source.restore(input, plaintext); }
  async deleteBackup(input: BackupIdentity, artifact: BackupArtifact): Promise<void> { if (!artifact.reference.startsWith(`tenants/${input.tenantId}/websites/${input.websiteId}/backups/`)) throw new Error('BACKUP_SCOPE_INVALID'); await this.storage.delete(artifact.reference); }
}
