import { createHash } from 'node:crypto';
import { Worker, type Job } from 'bullmq';
import Redis from 'ioredis';
import type { Logger } from 'pino';
import { database } from '@zerochack/database';
import type { BackupArtifact, BackupProvider } from '@zerochack/storage';
import { emitTenantEvent } from './communication-events.js';
export type BackupJob = { action?: 'CREATE' | 'RESTORE' | 'DELETE' | 'RETENTION'; backupId?: string; restoreId?: string; tenantId: string; websiteId: string; ticketId?: string };
export type RemediationBackupJob = BackupJob & { backupId: string; ticketId: string };
const safeCode = (error: unknown, fallback: string) => error instanceof Error && /^[A-Z][A-Z0-9_]{2,119}$/u.test(error.message) ? error.message : error instanceof Error ? createHash('sha256').update(error.message).digest('hex').slice(0, 32) : fallback;
function artifact(backup: { restoreReference: string | null; integrityHash: string | null; sizeBytes: bigint | null; providerKey: string | null; encryption: unknown }): BackupArtifact {
  const encryption = backup.encryption as { algorithm?: string; keyId?: string } | null; if (!backup.restoreReference || !backup.integrityHash || backup.sizeBytes === null || !backup.providerKey || encryption?.algorithm !== 'AES-256-GCM' || !encryption.keyId) throw new Error('BACKUP_ARTIFACT_INVALID'); return { reference: backup.restoreReference, integrityHash: backup.integrityHash, sizeBytes: Number(backup.sizeBytes), providerKey: backup.providerKey, encryption: { algorithm: 'AES-256-GCM', keyId: encryption.keyId } };
}
async function failBackup(input: RemediationBackupJob, requestId: string, errorCode: string): Promise<void> { const operations = [database.backup.update({ where: { id: input.backupId }, data: { status: 'FAILED', errorCode, completedAt: new Date() } }), database.auditLog.create({ data: { tenantId: input.tenantId, requestId, action: input.ticketId ? 'remediation.backup_failed' : 'backup.failed', resourceType: 'backup', resourceId: input.backupId, metadata: { errorCode, ...(input.ticketId ? { ticketId: input.ticketId } : {}) } } })]; if (input.ticketId) operations.push(database.ticket.update({ where: { id: input.ticketId }, data: { status: 'AWAITING_CUSTOMER' } }) as never); await database.$transaction(operations); }

export async function processRemediationBackup(job: Job<RemediationBackupJob>, provider?: BackupProvider): Promise<void> { await processBackupCreate(job as Job<BackupJob>, provider); }
export async function processBackupCreate(job: Job<BackupJob>, provider?: BackupProvider): Promise<string> {
  const { tenantId, websiteId, ticketId } = job.data; let backupId = job.data.backupId; if (!backupId && job.data.action === 'CREATE') { const policy = await database.backupPolicy.findFirst({ where: { tenantId, websiteId, enabled: true } }); if (!policy) throw new Error('BACKUP_POLICY_INACTIVE'); const scheduled = await database.backup.create({ data: { tenantId, websiteId, purpose: 'SCHEDULED', retentionUntil: new Date(Date.now() + policy.retentionDays * 86_400_000) } }); backupId = scheduled.id; } if (!backupId) throw new Error('BACKUP_ID_REQUIRED'); const backup = await database.backup.findFirst({ where: { id: backupId, tenantId, websiteId, ...(ticketId ? { ticketId } : {}), status: 'QUEUED', deletedAt: null }, include: { website: true } }); if (!backup) throw new Error('BACKUP_JOB_BINDING_INVALID');
  await database.backup.update({ where: { id: backupId }, data: { status: 'RUNNING' } }); const requestId = `worker:${job.id ?? backupId}`.slice(0, 100); const bound = { backupId, tenantId, websiteId, ...(ticketId ? { ticketId } : {}) };
  if (!provider) { await failBackup({ ...bound, ticketId: ticketId ?? '' }, requestId, 'BACKUP_PROVIDER_UNCONFIGURED'); return backupId; }
  try { const created = await provider.createBackup(bound); const verified = await provider.verifyBackup(bound, created); if (!verified || !created.reference || !/^[a-f0-9]{64}$/u.test(created.integrityHash) || created.encryption.algorithm !== 'AES-256-GCM') throw new Error('BACKUP_VERIFICATION_INVALID'); const policy = await database.backupPolicy.findUnique({ where: { websiteId } }); const retentionDays = policy?.retentionDays ?? 30; const completedAt = new Date(); const operations = [database.backup.update({ where: { id: backupId }, data: { status: 'SUCCEEDED', verifiedAt: completedAt, completedAt, restoreReference: created.reference, integrityHash: created.integrityHash, sizeBytes: BigInt(created.sizeBytes), encryption: created.encryption, providerKey: created.providerKey, retentionUntil: new Date(completedAt.getTime() + retentionDays * 86_400_000), errorCode: null } }), database.website.update({ where: { id: websiteId }, data: { backupStatus: 'ACTIVE' } }), database.auditLog.create({ data: { tenantId, requestId, action: ticketId ? 'remediation.backup_verified' : 'backup.verified', resourceType: 'backup', resourceId: backupId, metadata: { ...(ticketId ? { ticketId } : {}), integrityHash: created.integrityHash, providerKey: created.providerKey, encrypted: true } } })]; if (ticketId) operations.push(database.ticket.update({ where: { id: ticketId }, data: { status: 'READY' } }) as never); await database.$transaction(operations); }
  catch (error) { await failBackup({ ...bound, ticketId: ticketId ?? '' }, requestId, safeCode(error, 'BACKUP_FAILED')); }
  return backupId;
}

export async function processRestore(job: Job<BackupJob>, provider?: BackupProvider): Promise<void> {
  const { restoreId, tenantId, websiteId } = job.data; if (!restoreId) throw new Error('RESTORE_ID_REQUIRED'); const restore = await database.restoreOperation.findFirst({ where: { id: restoreId, tenantId, websiteId, status: 'QUEUED' }, include: { backup: true, authorization: true } }); if (!restore) throw new Error('RESTORE_JOB_BINDING_INVALID'); await database.restoreOperation.update({ where: { id: restoreId }, data: { status: 'RUNNING' } }); const requestId = `worker:${job.id ?? restoreId}`.slice(0, 100);
  if (!provider) { await database.$transaction([database.restoreOperation.update({ where: { id: restoreId }, data: { status: 'FAILED', errorCode: 'BACKUP_PROVIDER_UNCONFIGURED', completedAt: new Date() } }), database.auditLog.create({ data: { tenantId, requestId, action: 'backup.restore_failed', resourceType: 'restore_operation', resourceId: restoreId, metadata: { errorCode: 'BACKUP_PROVIDER_UNCONFIGURED' } } })]); return; }
  try { if (!restore.authorization.usedAt || restore.authorization.revokedAt || restore.authorization.expiresAt <= restore.requestedAt || restore.backup.status !== 'SUCCEEDED' || !restore.backup.verifiedAt || restore.backup.deletedAt) throw new Error('RESTORE_AUTHORIZATION_INVALID'); const value = artifact(restore.backup); if (!await provider.verifyBackup({ tenantId, websiteId, backupId: restore.backupId }, value)) throw new Error('BACKUP_VERIFICATION_INVALID'); await provider.restoreBackup({ tenantId, websiteId, backupId: restore.backupId }, value); await database.$transaction([database.restoreOperation.update({ where: { id: restoreId }, data: { status: 'SUCCEEDED', completedAt: new Date(), errorCode: null } }), database.auditLog.create({ data: { tenantId, requestId, action: 'backup.restore_succeeded', resourceType: 'restore_operation', resourceId: restoreId, metadata: { backupId: restore.backupId } } })]); }
  catch (error) { const errorCode = safeCode(error, 'RESTORE_FAILED'); await database.$transaction([database.restoreOperation.update({ where: { id: restoreId }, data: { status: 'FAILED', errorCode, completedAt: new Date() } }), database.auditLog.create({ data: { tenantId, requestId, action: 'backup.restore_failed', resourceType: 'restore_operation', resourceId: restoreId, metadata: { backupId: restore.backupId, errorCode } } })]); }
}

export async function deleteEligibleBackup(backupId: string, tenantId: string, websiteId: string, provider?: BackupProvider): Promise<boolean> {
  const backup = await database.backup.findFirst({ where: { id: backupId, tenantId, websiteId, status: 'SUCCEEDED', deletedAt: null }, include: { remediationRuns: { take: 1 }, ticket: true } }); if (!backup) throw new Error('BACKUP_NOT_FOUND'); const now = new Date(); const warrantyClaim = backup.ticketId ? await database.warrantyClaim.findFirst({ where: { ticketId: backup.ticketId, status: { in: ['SUBMITTED', 'REVIEWING', 'APPROVED'] } }, select: { id: true } }) : null; const activeTicket = backup.ticket && !['RESOLVED', 'CLOSED', 'CANCELLED'].includes(backup.ticket.status); if (backup.remediationRuns.length || activeTicket || warrantyClaim || (backup.protectedUntil && backup.protectedUntil > now) || (backup.retentionUntil && backup.retentionUntil > now)) return false; if (!provider) throw new Error('BACKUP_PROVIDER_UNCONFIGURED'); await provider.deleteBackup({ tenantId, websiteId, backupId }, artifact(backup)); await database.backup.update({ where: { id: backupId }, data: { deletedAt: now } }); await database.auditLog.create({ data: { tenantId, requestId: `retention:${backupId}`.slice(0, 100), action: 'backup.deleted', resourceType: 'backup', resourceId: backupId, metadata: { providerConfirmed: true } } }); return true;
}

export async function processRetention(tenantId: string, websiteId: string, provider?: BackupProvider): Promise<number> { const policy = await database.backupPolicy.findFirst({ where: { tenantId, websiteId } }); if (!policy) return 0; const backups = await database.backup.findMany({ where: { tenantId, websiteId, status: 'SUCCEEDED', deletedAt: null }, orderBy: { completedAt: 'desc' }, select: { id: true, retentionUntil: true } }); const candidates = backups.filter((item, index) => index >= policy.restorePointLimit && (!item.retentionUntil || item.retentionUntil <= new Date())); let deleted = 0; for (const candidate of candidates) if (await deleteEligibleBackup(candidate.id, tenantId, websiteId, provider)) deleted += 1; return deleted; }

export function createBackupWorker(redisUrl: string, logger: Logger, provider?: BackupProvider): Worker<BackupJob> { const connection = new Redis(redisUrl, { maxRetriesPerRequest: null }); const worker = new Worker<BackupJob>('backups', async (job) => { if (job.data.action === 'RESTORE') return processRestore(job, provider); if (job.data.action === 'DELETE') { if (!job.data.backupId) throw new Error('BACKUP_ID_REQUIRED'); await deleteEligibleBackup(job.data.backupId, job.data.tenantId, job.data.websiteId, provider); return; } if (job.data.action === 'RETENTION') { await processRetention(job.data.tenantId, job.data.websiteId, provider); return; } const backupId=await processBackupCreate(job, provider);const backup=await database.backup.findFirst({where:{id:backupId,tenantId:job.data.tenantId,websiteId:job.data.websiteId},include:{website:{select:{name:true}}}});if(backup)await emitTenantEvent({tenantId:job.data.tenantId,eventType:backup.status==='SUCCEEDED'?'BACKUP_SUCCESS':'BACKUP_FAILURE',deduplicationKey:`backup-${backup.status.toLowerCase()}:${backup.id}`,title:backup.status==='SUCCEEDED'?'Backup completed':'Backup failed',message:backup.status==='SUCCEEDED'?`A verified backup was created for ${backup.website.name}.`:`A backup for ${backup.website.name} failed.`,actionUrl:`/customer/websites/${job.data.websiteId}/backups`,data:{backupId:backup.id,websiteId:job.data.websiteId,status:backup.status}},redisUrl); }, { connection, concurrency: 2 }); worker.on('failed', (job, error) => logger.error({ jobId: job?.id, errorCode: 'BACKUP_JOB_FAILED', err: error }, 'backup.job.failed')); return worker; }
