import { createHash } from 'node:crypto';
import { Worker, type Job } from 'bullmq';
import Redis from 'ioredis';
import type { Logger } from 'pino';
import { database } from '@zerochack/database';
import { safeHttpRequest, TargetSecurityError, type SafeResponse } from '@zerochack/scanner';
import { emitTenantEvent } from './communication-events.js';

export type MonitoringJob = { tenantId: string; websiteId: string };
export type MonitoringSnapshot = { available: boolean; status: number; tls: boolean; resolvedAddress: string; securityHeaders: Record<string, boolean>; contentHash: string };
export type DetectedChange = { type: 'AVAILABILITY' | 'TLS' | 'DNS' | 'HEADERS' | 'INTEGRITY' | 'SECURITY_INDICATOR'; severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; key: string; title: string; summary: string; metadata: Record<string, string | number | boolean | null> };
const monitoredHeaders = ['strict-transport-security', 'content-security-policy', 'x-content-type-options', 'referrer-policy'] as const;
const sha = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex');
const snapshotHash = (value: MonitoringSnapshot) => sha(JSON.stringify(value));
const responseSnapshot = (response: SafeResponse): MonitoringSnapshot => ({ available: response.status < 500, status: response.status, tls: response.url.startsWith('https:'), resolvedAddress: response.resolvedAddress, securityHeaders: Object.fromEntries(monitoredHeaders.map((header) => [header, Boolean(response.headers[header])])), contentHash: sha(response.body) });

export function detectMonitoringChanges(previous: MonitoringSnapshot | undefined, current: MonitoringSnapshot, rawIndicators: unknown): DetectedChange[] {
  const changes: DetectedChange[] = []; const indicators = typeof rawIndicators === 'object' && rawIndicators ? rawIndicators as { expectedStatus?: unknown; requiredHeaders?: unknown; integrityHash?: unknown } : {};
  if (!current.available) changes.push({ type: 'AVAILABILITY', severity: 'CRITICAL', key: 'unavailable', title: 'Website availability failure', summary: `The monitored website returned HTTP ${current.status}.`, metadata: { status: current.status } });
  if (!current.tls) changes.push({ type: 'TLS', severity: 'HIGH', key: 'tls-disabled', title: 'TLS is not active', summary: 'The final monitored URL is not protected by HTTPS.', metadata: { tls: false } });
  if (previous?.resolvedAddress && previous.resolvedAddress !== current.resolvedAddress) changes.push({ type: 'DNS', severity: 'LOW', key: 'resolved-address-changed', title: 'DNS destination changed', summary: 'The public address selected for the verified hostname changed.', metadata: { previousAddress: previous.resolvedAddress, currentAddress: current.resolvedAddress } });
  if (previous) for (const header of monitoredHeaders) if (previous.securityHeaders[header] && !current.securityHeaders[header]) changes.push({ type: 'HEADERS', severity: header === 'strict-transport-security' || header === 'content-security-policy' ? 'HIGH' : 'MEDIUM', key: `header-removed:${header}`, title: 'Security header removed', summary: `${header} was present in the previous check and is now absent.`, metadata: { header, present: false } });
  if (previous?.contentHash && previous.contentHash !== current.contentHash) changes.push({ type: 'INTEGRITY', severity: 'MEDIUM', key: 'content-changed', title: 'Website integrity changed', summary: 'The monitored response content hash changed.', metadata: { previousHash: previous.contentHash, currentHash: current.contentHash } });
  if (typeof indicators.expectedStatus === 'number' && current.status !== indicators.expectedStatus) changes.push({ type: 'SECURITY_INDICATOR', severity: 'HIGH', key: 'expected-status', title: 'Configured status indicator failed', summary: `Expected HTTP ${indicators.expectedStatus}, received ${current.status}.`, metadata: { expectedStatus: indicators.expectedStatus, currentStatus: current.status } });
  if (Array.isArray(indicators.requiredHeaders)) for (const value of indicators.requiredHeaders) if (typeof value === 'string' && monitoredHeaders.includes(value as typeof monitoredHeaders[number]) && !current.securityHeaders[value]) changes.push({ type: 'SECURITY_INDICATOR', severity: 'HIGH', key: `required-header:${value}`, title: 'Configured header indicator failed', summary: `Required security header ${value} is absent.`, metadata: { header: value, present: false } });
  if (typeof indicators.integrityHash === 'string' && /^[a-f0-9]{64}$/u.test(indicators.integrityHash) && current.contentHash !== indicators.integrityHash) changes.push({ type: 'SECURITY_INDICATOR', severity: 'HIGH', key: 'configured-integrity', title: 'Configured integrity indicator failed', summary: 'The response content does not match the configured integrity hash.', metadata: { expectedHash: indicators.integrityHash, currentHash: current.contentHash } });
  return changes;
}

const cooldownFor = (severity: DetectedChange['severity'], configured: number) => severity === 'CRITICAL' ? Math.min(configured, 15) : severity === 'HIGH' ? Math.min(configured, 30) : severity === 'LOW' ? configured * 2 : configured;
async function preserveAndAlert(input: { tenantId: string; websiteId: string; checkId: string; websiteName: string; change: DetectedChange; cooldownMinutes: number; observedAt: Date }): Promise<string> {
  const fingerprint = sha(`${input.websiteId}\0${input.change.type}\0${input.change.key}`); const evidenceMetadata = input.change.metadata; const evidenceHash = sha(JSON.stringify({ engine: 'continuous-monitor', version: '1.0.0', observedAt: input.observedAt.toISOString(), summary: input.change.summary, metadata: evidenceMetadata }));
  let event = await database.securityEvent.findFirst({ where: { tenantId: input.tenantId, websiteId: input.websiteId, fingerprint, status: { in: ['OPEN', 'ACKNOWLEDGED', 'ESCALATED'] } }, orderBy: { lastSeenAt: 'desc' } });
  event = event ? await database.securityEvent.update({ where: { id: event.id }, data: { checkId: input.checkId, severity: input.change.severity, occurrenceCount: { increment: 1 }, lastSeenAt: input.observedAt, summary: input.change.summary } }) : await database.securityEvent.create({ data: { tenantId: input.tenantId, websiteId: input.websiteId, checkId: input.checkId, type: input.change.type, severity: input.change.severity, fingerprint, title: input.change.title, summary: input.change.summary } });
  await database.securityEventEvidence.create({ data: { eventId: event.id, observedAt: input.observedAt, engine: 'continuous-monitor', engineVersion: '1.0.0', summary: input.change.summary, metadata: evidenceMetadata, integrityHash: evidenceHash } });
  const deduplicationKey = sha(`${input.tenantId}\0${fingerprint}`); const now = input.observedAt; const recent = await database.securityAlert.findFirst({ where: { tenantId: input.tenantId, websiteId: input.websiteId, deduplicationKey, status: { in: ['OPEN', 'ACKNOWLEDGED'] } }, orderBy: { createdAt: 'desc' } });
  if (recent && recent.cooldownUntil > now) { await database.securityAlert.update({ where: { id: recent.id }, data: { suppressedCount: { increment: 1 } } }); return event.id; }
  const cooldownUntil = new Date(now.getTime() + cooldownFor(input.change.severity, input.cooldownMinutes) * 60_000); await database.$transaction(async (tx) => { const notification = await tx.notification.create({ data: { tenantId: input.tenantId, title: `${input.change.severity}: ${input.change.title}`, body: input.change.summary } }); const ticket = ['HIGH', 'CRITICAL'].includes(input.change.severity) ? await tx.ticket.create({ data: { tenantId: input.tenantId, websiteId: input.websiteId, title: `Monitoring escalation: ${input.change.title}`, description: `Automatically escalated from preserved security event ${event.id}.`, status: 'QUEUED', escalatedAt: now } }) : null; await tx.securityAlert.create({ data: { tenantId: input.tenantId, websiteId: input.websiteId, eventId: event.id, deduplicationKey, severity: input.change.severity, cooldownUntil, notificationId: notification.id, ...(ticket ? { specialistTicketId: ticket.id } : {}) } }); await tx.securityEvent.update({ where: { id: event.id }, data: { status: ticket ? 'ESCALATED' : 'OPEN' } }); await tx.auditLog.create({ data: { tenantId: input.tenantId, requestId: `monitor:${input.checkId}`.slice(0, 100), action: 'monitoring.alert_created', resourceType: 'security_event', resourceId: event.id, metadata: { severity: input.change.severity, type: input.change.type, specialistEscalated: Boolean(ticket) } } }); }); return event.id;
}

export async function processMonitoringCheck(job: Job<MonitoringJob>, runner: typeof safeHttpRequest = safeHttpRequest): Promise<{ events: number }> {
  const { tenantId, websiteId } = job.data; const jobId = String(job.id ?? `${websiteId}:${job.timestamp}`); const duplicate = await database.monitoringCheck.findUnique({ where: { jobId } }); if (duplicate) return { events: await database.securityEvent.count({ where: { checkId: duplicate.id } }) };
  const policy = await database.monitoringPolicy.findFirst({ where: { tenantId, websiteId, enabled: true }, include: { website: true } }); if (!policy || policy.website.lifecycle !== 'ACTIVE' || policy.website.connectionStatus !== 'VERIFIED') throw new Error('MONITORING_JOB_BINDING_INVALID'); const check = await database.monitoringCheck.create({ data: { tenantId, websiteId, jobId } }); const started = performance.now(); const observedAt = new Date();
  try { const response = await runner(policy.website.url, { allowedHostname: policy.website.normalizedHost, method: 'GET', timeoutMs: 10_000, maxRedirects: 5, maxBytes: 1_048_576 }); const current = responseSnapshot(response); const prior = await database.monitoringCheck.findFirst({ where: { tenantId, websiteId, status: 'SUCCEEDED', id: { not: check.id } }, orderBy: { completedAt: 'desc' } }); const previous = prior?.snapshot as MonitoringSnapshot | undefined; const changes = detectMonitoringChanges(previous, current, policy.indicators); await database.monitoringCheck.update({ where: { id: check.id }, data: { status: 'SUCCEEDED', snapshot: current, snapshotHash: snapshotHash(current), resolvedAddress: current.resolvedAddress, responseTimeMs: Math.round(performance.now() - started), completedAt: observedAt } }); for (const change of changes) await preserveAndAlert({ tenantId, websiteId, checkId: check.id, websiteName: policy.website.name, change, cooldownMinutes: policy.alertCooldownMinutes, observedAt }); const activeFingerprints = changes.map((change) => sha(`${websiteId}\0${change.type}\0${change.key}`)); await database.securityEvent.updateMany({ where: { tenantId, websiteId, status: { in: ['OPEN', 'ACKNOWLEDGED', 'ESCALATED'] }, ...(activeFingerprints.length ? { fingerprint: { notIn: activeFingerprints } } : {}) }, data: { status: 'RESOLVED', resolvedAt: observedAt } }); await database.monitoringPolicy.update({ where: { websiteId }, data: { nextCheckAt: new Date(observedAt.getTime() + policy.intervalMinutes * 60_000) } }); await database.website.update({ where: { id: websiteId }, data: { monitoringStatus: 'ACTIVE' } }); return { events: changes.length }; }
  catch (error) { const errorCode = error instanceof TargetSecurityError ? error.code : 'MONITORING_CHECK_FAILED'; await database.monitoringCheck.update({ where: { id: check.id }, data: { status: 'FAILED', errorCode, responseTimeMs: Math.round(performance.now() - started), completedAt: observedAt } }); const change: DetectedChange = { type: 'AVAILABILITY', severity: 'CRITICAL', key: 'connection-failed', title: 'Website monitoring connection failed', summary: 'The safe monitoring probe could not reach the verified website.', metadata: { errorCode } }; await preserveAndAlert({ tenantId, websiteId, checkId: check.id, websiteName: policy.website.name, change, cooldownMinutes: policy.alertCooldownMinutes, observedAt }); await database.website.update({ where: { id: websiteId }, data: { monitoringStatus: 'ERROR' } }); return { events: 1 }; }
}

export function createMonitoringWorker(redisUrl: string, logger: Logger): Worker<MonitoringJob> { const connection = new Redis(redisUrl, { maxRetriesPerRequest: null }); const worker = new Worker<MonitoringJob>('monitoring', async(job)=>{const result=await processMonitoringCheck(job);if(result.events)await emitTenantEvent({tenantId:job.data.tenantId,eventType:'MONITORING_ALERT',deduplicationKey:`monitoring-alert:${String(job.id)}`,title:'Monitoring alert',message:`Continuous monitoring detected ${result.events} security event(s).`,actionUrl:`/customer/websites/${job.data.websiteId}/monitoring`,data:{websiteId:job.data.websiteId,eventCount:result.events}},redisUrl);return result;}, { connection, concurrency: 4, limiter: { max: 60, duration: 60_000 } }); worker.on('failed', (job, error) => logger.error({ jobId: job?.id, errorCode: 'MONITORING_JOB_FAILED', err: error }, 'monitoring.job.failed')); return worker; }
