import { Worker, type Job } from 'bullmq';
import IORedis from 'ioredis';
import type { Logger } from 'pino';
import type { Prisma } from '@prisma/client';
import { database } from '@zerochack/database';
import type { Environment } from '@zerochack/config';
import { reportIntegrity, signReport, type ReportDocument } from '@zerochack/reports';

async function reportData(report:{id:string;tenantId:string;websiteId:string;type:'SECURITY_SCAN'|'REMEDIATION'|'MONITORING'|'BEFORE_AFTER';sourceId:string|null}):Promise<Record<string,unknown>>{
  if(report.type==='SECURITY_SCAN'){const scan=report.sourceId?await database.scan.findFirst({where:{id:report.sourceId,tenantId:report.tenantId,websiteId:report.websiteId},select:{id:true,status:true,requestedAt:true,startedAt:true,completedAt:true,engineCount:true,completedEngines:true,errorCode:true}}):await database.scan.findFirst({where:{tenantId:report.tenantId,websiteId:report.websiteId},orderBy:{requestedAt:'desc'},select:{id:true,status:true,requestedAt:true,startedAt:true,completedAt:true,engineCount:true,completedEngines:true,errorCode:true}});if(!scan)throw new Error('REPORT_SOURCE_NOT_FOUND');const findings=await database.securityFinding.findMany({where:{tenantId:report.tenantId,websiteId:report.websiteId,scanId:scan.id},select:{id:true,title:true,severity:true,status:true,confidence:true,affectedResource:true,recommendation:true,cwe:true,cve:true,owaspCategory:true,evidence:{select:{engine:true,engineVersion:true,observedAt:true,summary:true,integrityHash:true}}},orderBy:{createdAt:'asc'}});return{scan,findings};}
  if(report.type==='MONITORING'){const checks=await database.monitoringCheck.findMany({where:{tenantId:report.tenantId,websiteId:report.websiteId},select:{id:true,status:true,responseTimeMs:true,errorCode:true,startedAt:true,completedAt:true},orderBy:{startedAt:'desc'},take:500});const events=await database.securityEvent.findMany({where:{tenantId:report.tenantId,websiteId:report.websiteId},select:{id:true,type:true,severity:true,status:true,title:true,summary:true,firstSeenAt:true,lastSeenAt:true,occurrenceCount:true,evidence:{select:{observedAt:true,summary:true,integrityHash:true}}},orderBy:{lastSeenAt:'desc'},take:500});return{checks,events};}
  const run=await database.remediationRun.findFirst({where:{...(report.sourceId?{id:report.sourceId}:{}),tenantId:report.tenantId,websiteId:report.websiteId},orderBy:{createdAt:'desc'},select:{id:true,status:true,executedActions:true,comparison:true,postScanId:true,startedAt:true,completedAt:true,authorization:{select:{scope:true,authorizedAt:true}},ticket:{select:{id:true,title:true,status:true,finding:{select:{id:true,title:true,severity:true,status:true}}}},backup:{select:{id:true,status:true,verifiedAt:true,integrityHash:true}}}});if(!run)throw new Error('REPORT_SOURCE_NOT_FOUND');return report.type==='BEFORE_AFTER'?{remediationRunId:run.id,comparison:run.comparison,postScanId:run.postScanId}:{remediation:run};
}

export async function processReport(reportId:string,environment:Pick<Environment,'REPORT_SIGNING_KEY'>):Promise<void>{const report=await database.report.findUnique({where:{id:reportId},include:{website:{select:{id:true,name:true,url:true}}}});if(!report||report.status==='SUCCEEDED')return;await database.report.update({where:{id:report.id},data:{status:'RUNNING',errorCode:null}});try{const generatedAt=new Date();const data=await reportData(report);const document:ReportDocument={schemaVersion:1,reportId:report.id,type:report.type,tenantId:report.tenantId,website:{id:report.website.id,name:report.website.name,origin:new URL(report.website.url).origin},generatedAt:generatedAt.toISOString(),data};const integrityHash=reportIntegrity(document);const signature=signReport(document,environment.REPORT_SIGNING_KEY);await database.$transaction([database.report.update({where:{id:report.id},data:{status:'SUCCEEDED',content:document as unknown as Prisma.InputJsonValue,integrityHash,signature,generatedAt,completedAt:generatedAt}}),database.auditLog.create({data:{tenantId:report.tenantId,requestId:`report:${report.id}`.slice(0,100),action:'report.generated',resourceType:'report',resourceId:report.id,metadata:{type:report.type,integrityHash}}})]);}catch(error){const errorCode=error instanceof Error&&/^[A-Z][A-Z0-9_]{2,119}$/u.test(error.message)?error.message:'REPORT_GENERATION_FAILED';await database.$transaction([database.report.update({where:{id:report.id},data:{status:'FAILED',errorCode,completedAt:new Date()}}),database.auditLog.create({data:{tenantId:report.tenantId,requestId:`report:${report.id}`.slice(0,100),action:'report.failed',resourceType:'report',resourceId:report.id,metadata:{type:report.type,errorCode}}})]);throw error;}}

export function createReportWorker(redisUrl:string,logger:Logger,environment:Pick<Environment,'REPORT_SIGNING_KEY'>):Worker{const worker=new Worker('reports',(job:Job<{reportId:string}>)=>processReport(job.data.reportId,environment),{connection:new IORedis(redisUrl,{maxRetriesPerRequest:null}),concurrency:3});worker.on('failed',(job,error)=>logger.error({jobId:job?.id,err:error,errorCode:'REPORT_JOB_FAILED'},'report.job_failed'));return worker;}
