import type { Metadata } from 'next';
import Link from 'next/link';
import { HomePreview } from '../components/home-preview';
import { HomeTechnologies } from '../components/home-technologies';
import { agentCatalogue, toolCatalogue } from '@zerochack/care/catalogue';
import { headers } from 'next/headers';
const reviewRoles = agentCatalogue.filter(role => role.enabled && role.sourceReview).map(({ id, name }) => ({ id, name }));

const title = 'ZeroRoot | AI Website, API, Server & DevOps Care';
const description = 'AI-assisted care for websites, web apps, APIs, servers and DevOps. Review issues, plan repairs, strengthen security and coordinate specialist-led fixes.';

export const metadata: Metadata = {
  title: { absolute: title }, description,
  alternates: { canonical: '/' },
  openGraph: { title, description, type: 'website', url: '/', siteName: 'ZeroRoot', locale: 'en_US', images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: 'ZeroRoot — One workspace for your whole web stack' }] },
  twitter: { card: 'summary_large_image', title, description, images: ['/opengraph-image'] }
};

const services = [
  { id: 'redesign', number: '01', symbol: '◧', tag: 'LOOK BETTER', title: 'Better websites.\nBetter app experiences.', description: 'Find what makes a page feel confusing, dated or difficult to use. Get focused AI feedback on website and web application design, content, accessibility and mobile layouts.', features: ['Website & web app design reviews', 'Content & on-page SEO guidance', 'Mobile & accessibility recommendations'], link: 'Start a design review', className: 'design' },
  { id: 'repair', number: '02', symbol: '⌘', tag: 'WORK BETTER', title: 'Find the issue.\nPlan the right fix.', description: 'Bring a broken interface, API issue or server configuration concern. Get source-based findings and a repair plan. Supported standalone HTML repairs include a protected preview.', features: ['Frontend, backend & API source reviews', 'Server, DevOps & deployment reviews', 'Supported HTML repairs with previews'], link: 'Get help with a repair', className: 'repair' },
  { id: 'security', number: '03', symbol: '◇', tag: 'FEEL IN CONTROL', title: 'When something’s wrong,\nknow your next step.', description: 'Suspect a hacked website or an insecure application? Review available evidence, improve security practices and coordinate an authorized recovery with a specialist.', features: ['Website, app & API security guidance', 'Hardening recommendations & recovery plans', 'Scoped access for human specialists'], link: 'Start a security assessment', className: 'security' }
];

const capabilities = [
  ['Website & app design', 'Review UI structure, CSS, accessibility and user journeys. Plan a clearer experience across screen sizes.', 'Design · Frontend · Accessibility'],
  ['Backend & API logic', 'Review API handlers, authentication, validation, integration logic and error paths. Plan fixes for failures and timeouts.', 'APIs · Business logic · Integrations'],
  ['Servers & DevOps', 'Review CI/CD pipelines, Dockerfiles and deployment configuration. Plan fixes for build, release and infrastructure issues.', 'CI/CD · Containers · Configuration'],
  ['Security & recovery', 'Review defensive code, assess supplied incident evidence and organize hardening or specialist-led recovery.', 'Security · Permissions · Incidents'],
  ['Data & performance', 'Review schemas, migration text and source-level bottlenecks. Build a plan for measurement and safer changes.', 'Databases · Performance · Reliability'],
  ['SEO, content & quality', 'Review headings, metadata and content. Define acceptance criteria and test recommendations before implementation.', 'SEO · Content · Quality assurance']
];



const faqs = [
  ['Is ZeroRoot only for websites?', 'No. ZeroRoot brings website and web application care together with API/backend, database, security and infrastructure source reviews. The shared workspace connects findings, conversations and specialist next steps. It is not an automatic repair engine for every server or technology.'],
  ['What can ZeroRoot AI actually do?', `ZeroRoot supports website conversations, approved reviews of supplied source across ${reviewRoles.length} specialist roles, and a separate repair workflow for supported standalone HTML pages with inline CSS. Reviews provide referenced findings and recommendations. AI features require an enabled provider and model; they do not offer unrestricted, autonomous repair of any application.`],
  ['Can you help redesign my existing website?', 'Yes. You can request reviews of layout, content, accessibility and mobile usability, then use the findings to plan a redesign. Supported standalone HTML pages can also use the scoped repair and preview workflow. Full redesigns of dynamic applications require developer implementation.'],
  ['Can it help with DevOps and deployment failures?', 'ZeroRoot can review supplied CI/CD YAML, Dockerfiles and deployment configuration, explain source-level concerns and help plan a fix. It can also suggest release checks, test criteria and recovery questions. Reviews do not run pipelines, restart services or change cloud infrastructure; those actions require an authorized engineer and appropriate access.'],
  ['Can it help fix APIs and server problems?', 'Yes, through reviews of supplied API code, configuration, deployment manifests and relevant evidence. AI can identify source-level concerns and recommend a repair plan. These reviews do not execute server commands, contact APIs or apply backend changes. A developer or authorized specialist carries out those changes.'],
  ['Can ZeroRoot improve security before something goes wrong?', 'Yes. Approved reviews can examine authentication, authorization, validation, dependency declarations and least-privilege settings in supplied source. Recommendations can guide security improvements; a source review does not replace live testing, current vulnerability intelligence or a full security audit.'],
  ['Can ZeroRoot fix a hacked website?', 'ZeroRoot helps organize security findings, authorized specialist access and recovery work. The right fix depends on the incident, the affected system and available restore points. It does not guarantee automatic malware removal or complete recovery from every compromise.'],
  ['Will AI change my live website without asking?', 'Reviews do not deploy changes. Supported repairs use a separate plan, candidate preview and approval process. Release availability depends on the supported website type, connection setup and enabled deployment capabilities.'],
  ['Do you cover my technology or hosting platform?', 'The directory covers frontend frameworks, CMS and commerce, backend languages, APIs, databases, Linux and Windows servers, web servers, cloud, containers, DevOps, networking and security. Reviews work from supported text source, manifests or redacted configuration excerpts you provide. Naming a technology does not mean a live connector or automatic repair is available. Unlisted stacks need a scope review; implementation and system changes require an authorized developer or specialist.'],
  ['How do I get started?', 'Create a customer account, add your website and describe what you want to improve. Connect only the access needed for the agreed task. Your workspace keeps the conversation, findings and next steps together. Agencies have a separate portal for authorized client work.']
];

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default async function Home() {
  const nonce = (await headers()).get('x-nonce') ?? undefined;
  const siteUrl = (process.env.APP_URL ?? 'http://localhost:3000').replace(/\/$/, '');
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'Organization', '@id': `${siteUrl}/#organization`, name: 'ZeroRoot', url: siteUrl, logo: `${siteUrl}/brand/zeroroot-logo.webp` },
      { '@type': 'WebSite', '@id': `${siteUrl}/#website`, name: 'ZeroRoot', url: siteUrl, description, publisher: { '@id': `${siteUrl}/#organization` }, inLanguage: 'en' },
      { '@type': 'WebPage', '@id': `${siteUrl}/#webpage`, name: title, description, url: siteUrl, isPartOf: { '@id': `${siteUrl}/#website` }, about: { '@id': `${siteUrl}/#software` }, inLanguage: 'en' },
      { '@type': 'SoftwareApplication', '@id': `${siteUrl}/#software`, name: 'ZeroRoot', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', url: siteUrl, description, featureList: ['Website and web application design reviews', 'Backend and API source reviews', 'Server, DevOps and CI/CD configuration reviews', 'Database and performance source reviews', 'Supported standalone HTML repairs', 'Security hardening guidance', 'Authorized specialist recovery workflows'], provider: { '@id': `${siteUrl}/#organization` } },
      { '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) }
    ]
  };
  return <div className="zr-home">
    <script nonce={nonce} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll('<', '\\u003c') }} />
    <section className="zr-hero" aria-labelledby="home-title">
      <div className="zr-container zr-hero-grid">
        <div className="zr-hero-copy"><div className="zr-eyebrow"><span className="zr-status-dot"/> ALL-IN-ONE CARE FOR YOUR WEB STACK</div><h1 id="home-title">Your web stack.<br/><span>In better hands.</span></h1><p>Websites, web apps, APIs, servers and DevOps. Understand issues, plan fixes, improve performance and strengthen security in one AI-assisted workspace—with specialist help when you need it.</p><div className="zr-actions"><Link href="/customer/register" className="zr-button zr-button--dark">Let’s improve your web stack <Arrow/></Link><a href="#ai" className="zr-text-link">Meet your AI workspace <span aria-hidden="true">↓</span></a></div><div className="zr-hero-assurances"><span>✓ Your systems. Your approvals.</span><span>✓ Human expertise when it matters.</span></div></div>
        <div className="zr-hero-visual"><div className="zr-orbit" aria-hidden="true"/><div className="zr-visual-caption"><span aria-hidden="true">✳</span> A little clarity changes everything.</div><HomePreview/><div className="zr-control-note"><span aria-hidden="true">↳</span> Built to help. Designed to keep you in charge.</div></div>
      </div>
      <div className="zr-container zr-service-strip"><span>ONE WORKSPACE. MORE POSSIBILITIES.</span><div><a href="#redesign">Websites & web apps</a><i aria-hidden="true">✳</i><a href="#repair">APIs, servers & DevOps</a><i aria-hidden="true">✳</i><a href="#security">Security & recovery</a><i aria-hidden="true">✳</i><a href="#ai">AI expertise</a></div></div>
    </section>

    <section id="services" className="zr-section zr-container" aria-labelledby="services-title"><div className="zr-section-head"><div><span className="zr-eyebrow">01 / CONNECT THE WHOLE PICTURE</span><h2 id="services-title">Whatever needs attention,<br/>start here.</h2></div><p>A tired design. A failing API. A server concern.<br/>Get the right perspective and a practical next step.</p></div><div className="zr-services">{services.map(service => <article id={service.id} key={service.id} className={`zr-service zr-service--${service.className}`}><div className="zr-service-top"><span className="zr-service-symbol" aria-hidden="true">{service.symbol}</span><span>{service.number} / {service.tag}</span></div><h3>{service.title}</h3><p>{service.description}</p><ul>{service.features.map(feature => <li key={feature}><span aria-hidden="true">↳</span>{feature}</li>)}</ul><Link href="/customer/register">{service.link}<Arrow/></Link></article>)}</div></section>

    <section id="technology" className="zr-technology zr-container" aria-labelledby="technology-title"><div className="zr-section-head"><div><span className="zr-eyebrow">FROM THE INTERFACE TO THE INFRASTRUCTURE</span><h2 id="technology-title">Your stack is complex.<br/>Getting help shouldn’t be.</h2></div><p>Explore the technology behind your business—from the browser to the database, cloud and deployment pipeline. Find the review and troubleshooting context for your stack.</p></div><HomeTechnologies roles={reviewRoles} implementedTools={toolCatalogue.filter(tool => tool.enabled).length} plannedTools={toolCatalogue.filter(tool => !tool.enabled).length}/></section>

    <section id="ai" className="zr-ai zr-section" aria-labelledby="ai-title"><div className="zr-container"><div className="zr-section-head"><div><span className="zr-eyebrow">02 / INTELLIGENCE, WITH INTENTION</span><h2 id="ai-title">One conversation.<br/><span>More ways forward.</span></h2></div><p>From interface details to infrastructure questions, bring the context. Your AI workspace explains source findings and helps you plan the next step.</p></div><div className="zr-ai-layout"><div className="zr-ai-core"><div className="zr-core-graphic" aria-hidden="true"><span className="zr-core-ring zr-core-ring--one"/><span className="zr-core-ring zr-core-ring--two"/><span className="zr-core-dot zr-core-dot--one"/><span className="zr-core-dot zr-core-dot--two"/><div>z<span>r</span><i>✳</i></div></div><span className="zr-ai-label">YOUR AI CARE WORKSPACE</span><h3>Specialist thinking.<br/>Shared context.</h3><p>{reviewRoles.length} review roles bring different perspectives to approved source reviews. Findings stay connected to the website and conversation they belong to.</p><Link href="/customer/register" className="zr-button zr-button--lime">Explore ZeroRoot Care <Arrow/></Link></div><div className="zr-capabilities">{capabilities.map(([heading, copy, tags], index) => <article key={heading}><span className="zr-capability-number">0{index + 1}</span><div><h3>{heading}</h3><p>{copy}</p><span>{tags}</span></div><Arrow/></article>)}</div></div><div className="zr-ai-boundary"><span aria-hidden="true">◈</span><p><strong>Clear capabilities. Clear expectations.</strong> AI reviews and recommends. Direct repairs are limited to supported standalone HTML pages. Backend, API, server and DevOps changes need a developer or authorized specialist. AI features need a configured provider.</p></div></div></section>

    <section id="how-it-works" className="zr-section zr-container" aria-labelledby="process-title"><div className="zr-section-head"><div><span className="zr-eyebrow">03 / FROM “SOMETHING’S WRONG” TO “WHAT’S NEXT”</span><h2 id="process-title">Less back-and-forth.<br/>More moving forward.</h2></div><p>A clear process that keeps the context together<br/>and the decisions in your hands.</p></div><ol className="zr-process"><li><span>01</span><h3>Tell us what’s happening.</h3><p>Add your project’s website, describe the issue and bring relevant app source, API code or configuration into the review.</p><small>A conversation, not a complicated brief.</small></li><li><span>02</span><h3>Get a clearer picture.</h3><p>Connect interface, application and infrastructure findings in one project workspace.</p><small>Understand the why behind the next step.</small></li><li><span>03</span><h3>Choose the way forward.</h3><p>Review a supported repair preview or coordinate the next action with a developer or specialist.</p><small>Your approval stays part of the process.</small></li></ol></section>

    <section className="zr-control zr-container" aria-labelledby="control-title"><div className="zr-control-copy"><span className="zr-eyebrow">CONFIDENCE IS PART OF THE PRODUCT</span><h2 id="control-title">Your systems.<br/>Your decisions.<br/><span>Always.</span></h2><p>Good technical care starts with trust. Keep access scoped, conversations organized and important changes subject to your approval.</p><Link href="/customer/register" className="zr-text-link">Build with more confidence <Arrow/></Link></div><div className="zr-control-list"><article><span aria-hidden="true">◎</span><div><h3>Access with a purpose</h3><p>Authorize the access a task needs, with time-limited specialist permissions and revocation controls.</p></div></article><article><span aria-hidden="true">▤</span><div><h3>A record you can return to</h3><p>Keep website conversations, review findings and recorded approvals in one workspace.</p></div></article><article><span aria-hidden="true">↶</span><div><h3>Recovery belongs in the plan</h3><p>Plan specialist work around available backups, verified restore points and a clear recovery path.</p></div></article></div></section>

    <section id="portals" className="zr-section zr-container zr-audience" aria-labelledby="audience-title"><div><span className="zr-eyebrow">BUILT AROUND THE WAY YOU WORK</span><h2 id="audience-title">One project?<br/>A whole portfolio?</h2><p>Bring your digital business into focus.</p></div><Link href="/customer/register"><span className="zr-audience-icon" aria-hidden="true">⌂</span><h3>For owners & product teams</h3><p>One place to understand issues, improve your website or app and coordinate technical work.</p><strong>Meet your workspace <Arrow/></strong></Link><Link href="/agency/register"><span className="zr-audience-icon" aria-hidden="true">▦</span><h3>For agencies & teams</h3><p>Manage authorized client work with separate website context and clear access boundaries.</p><strong>Explore agency access <Arrow/></strong></Link></section>

    <section id="faq" className="zr-faq zr-section" aria-labelledby="faq-title"><div className="zr-container zr-faq-grid"><div><span className="zr-eyebrow">A FEW THINGS WORTH KNOWING</span><h2 id="faq-title">Good questions.<br/>Straight answers.</h2><p>Get to know what ZeroRoot can help with<br/>and where human expertise fits.</p></div><div>{faqs.map(([question, answer], index) => <details key={question}><summary><span className="zr-faq-number">0{index + 1}</span>{question}<span className="zr-faq-plus" aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>

    <section className="zr-final" aria-labelledby="final-title"><div className="zr-container"><span className="zr-eyebrow">MAKE YOUR NEXT MOVE A BETTER ONE</span><h2 id="final-title">One workspace.<br/>Your whole web stack<span>.</span></h2><p>From a better homepage to a stronger backend.<br/>Review, improve and plan your next move with ZeroRoot.</p><Link href="/customer/register" className="zr-button zr-button--lime">Let’s take care of your technology <Arrow/></Link><span className="zr-final-note">Already have an account? <Link href="/sign-in">Welcome back →</Link></span></div><span className="zr-final-star" aria-hidden="true">✳</span></section>
  </div>;
}
