import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Queue } from 'bullmq';
import { z } from 'zod';
import { database } from '@zerochack/database';
import { generateOpaqueToken, hashOpaqueToken } from '@zerochack/auth';
import { assertRemediationGate, RemediationGateError } from '@zerochack/security';
import type { Environment } from '@zerochack/config';
import { ApiError } from '../../errors.js';
import { authenticate, requireOwnerMfa, requirePermission } from '../auth/security.js';
import { writeAudit } from '../auth/service.js';
import { publishTenantEvent } from '../communications/service.js';

const uuid = z.string().uuid();
const ids = z.object({ websiteId: uuid, ticketId: uuid });
const scopes = z.array(z.enum(['finding.remediate', 'headers.write', 'configuration.write', 'dependency.update'])).min(1).max(10);
function parse<T>(schema: z.ZodType<T>, value: unknown): T { const result = schema.safeParse(value);
if (!result.success) throw new ApiError(400, 'VALIDATION_ERROR', 'Request validation failed', result.error.flatten());
return result.data;
}
function specialist(request: FastifyRequest): asserts request is FastifyRequest & { userId: string;
roleNames: string[];
permissions: string[] } { if (!request.userId || (!request.roleNames?.includes('Cybersecurity Specialist') && !request.roleNames?.includes('Owner'))) throw new ApiError(403, 'SPECIALIST_REQUIRED', 'Specialist authorization required');
if (!request.permissions?.includes('specialist.jobs.read')) throw new ApiError(403, 'FORBIDDEN', 'Insufficient permissions');
}
async function expireAssignments() { await database.ticket.updateMany({ where: { status: 'ASSIGNED', assignmentExpiresAt: { lte: new Date() } }, data: { status: 'QUEUED', assignedSpecialistId: null, assignmentExpiresAt: null } });
await database.remediationSession.updateMany({ where: { status: 'ACTIVE', expiresAt: { lte: new Date() } }, data: { status: 'EXPIRED', revokedAt: new Date(), revokedReason: 'automatic_expiration' } });
}

export async function specialistRoutes(app: FastifyInstance, options: { environment: Environment;
queues?: { backups?: Queue;
scans?: Queue;notifications?:Queue;reports?:Queue } }): Promise<void> {
  app.addHook('preHandler', async (request) => authenticate(request, options.environment));
app.addHook('onSend', async (_request, reply) => { void reply.header('cache-control', 'private, no-store');
});
  app.get('/specialist/overview', async (request) => { specialist(request);
await expireAssignments();
const [available, mine, active, resolved] = await Promise.all([database.ticket.count({ where: { status: 'QUEUED', assignedSpecialistId: null } }), database.ticket.count({ where: { assignedSpecialistId: request.userId, status: { notIn: ['RESOLVED','CLOSED','CANCELLED'] } } }), database.remediationSession.count({ where: { specialistId: request.userId!, status: 'ACTIVE', expiresAt: { gt: new Date() } } }), database.ticket.count({ where: { assignedSpecialistId: request.userId, status: { in: ['RESOLVED','CLOSED'] } } })]);
return { availableJobs: available, myOpenTickets: mine, activeSessions: active, resolvedTickets: resolved };
});
  app.get('/specialist/jobs', async (request) => { specialist(request);
await expireAssignments();
return database.ticket.findMany({ where: { status: 'QUEUED', assignedSpecialistId: null }, orderBy: { createdAt: 'asc' }, take: 100, select: { id: true, tenantId: true, websiteId: true, title: true, description: true, status: true, createdAt: true, website: { select: { name: true, normalizedHost: true, securityStatus: true } }, finding: { select: { severity: true, title: true } } } });
});
  app.get('/specialist/tickets', async (request) => { specialist(request);
return database.ticket.findMany({ where: { assignedSpecialistId: request.userId }, orderBy: { updatedAt: 'desc' }, include: { website: { select: { name: true, normalizedHost: true } }, finding: { select: { title: true, severity: true } }, backups: { orderBy: { requestedAt: 'desc' }, take: 1, select: { id: true, status: true, requestedAt: true, completedAt: true, verifiedAt: true, errorCode: true } } } });
});
  app.get('/specialist/tickets/:ticketId/chat', async (request) => { specialist(request);
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId }, select: { tenantId: true, websiteId: true } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Assigned ticket was not found');
return database.chatMessage.findMany({ where: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, OR: [{ ticketId }, { ticketId: null }] }, orderBy: { createdAt: 'asc' }, take: 200, include: { author: { select: { displayName: true } } } });
});
  app.post('/specialist/tickets/:ticketId/chat', async (request, reply) => { specialist(request); requirePermission(request, 'chat.write');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId); const { content } = parse(z.object({ content: z.string().trim().min(1).max(4000) }), request.body);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId, status: { notIn: ['CLOSED', 'CANCELLED'] } }, select: { tenantId: true, websiteId: true } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Active assigned ticket was not found');
const message = await database.chatMessage.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, authorUserId: request.userId!, type: 'SPECIALIST', content }, include: { author: { select: { displayName: true } } } });
await writeAudit({ tenantId: ticket.tenantId, actorUserId: request.userId, requestId: request.id, action: 'specialist.message_sent', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip });
return reply.code(201).send(message);
});
  app.patch('/specialist/tickets/:ticketId/progress', async (request) => { specialist(request); requirePermission(request, 'specialist.jobs.accept');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const input = parse(z.object({ stage: z.enum(['ACCEPTED','ASSESSING','AWAITING_APPROVAL','BACKUP','REMEDIATING','VERIFYING','DELIVERED']), note: z.string().trim().min(2).max(500) }), request.body);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId, status: { notIn: ['CLOSED','CANCELLED'] } }, select: { tenantId: true, websiteId: true } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Active assigned ticket was not found');
const [updated] = await database.$transaction([
  database.ticket.update({ where: { id: ticketId }, data: { progressStage: input.stage, progressNote: input.note, progressUpdatedAt: new Date() } }),
  database.chatMessage.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, type: 'SYSTEM', content: `Work update — ${input.stage.replaceAll('_',' ').toLowerCase()}: ${input.note}` } })
]);
await writeAudit({ tenantId: ticket.tenantId, actorUserId: request.userId, requestId: request.id, action: 'ticket.progress_updated', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip, metadata: { stage: input.stage } });
return updated;
});
  app.get('/specialist/sessions', async (request) => { specialist(request);
await expireAssignments();
return database.remediationSession.findMany({ where: { specialistId: request.userId }, orderBy: { createdAt: 'desc' }, take: 100, select: { id: true, tenantId: true, websiteId: true, ticketId: true, scope: true, status: true, expiresAt: true, revokedAt: true, revokedReason: true, createdAt: true } });
});
  app.get('/specialist/performance', async (request) => { specialist(request);
const [resolved, accepted, escalated] = await Promise.all([database.ticket.count({ where: { assignedSpecialistId: request.userId, status: { in: ['RESOLVED','CLOSED'] } } }), database.ticket.count({ where: { assignedSpecialistId: request.userId, acceptedAt: { not: null } } }), database.ticket.count({ where: { assignedSpecialistId: request.userId, status: 'ESCALATED' } })]);
return { resolvedTickets: resolved, acceptedTickets: accepted, escalatedTickets: escalated, generatedAt: new Date() };
});
  app.get('/specialist/notifications', async (request) => { specialist(request);
return database.notification.findMany({ where: { tenantId: request.tenantId!,OR:[{recipientUserId:request.userId!},{recipientUserId:null}] }, orderBy: { createdAt: 'desc' }, take: 100 });
});
  app.get('/specialist/profile', async (request) => { specialist(request);
return database.user.findUnique({ where: { id: request.userId! }, select: { id: true, email: true, displayName: true, status: true, createdAt: true } });
});

  app.get('/specialist/support', async (request) => { specialist(request); requirePermission(request, 'chat.read');
return database.supportConversation.findMany({ where: { OR: [{ status: 'OPEN', assignedSpecialistId: null }, { assignedSpecialistId: request.userId }] }, orderBy: [{ status: 'asc' }, { updatedAt: 'desc' }], include: { customer: { select: { displayName: true, email: true } }, assignedSpecialist: { select: { displayName: true } }, _count: { select: { messages: true } } }, take: 200 });
});
  app.post('/specialist/support/:conversationId/claim', async (request) => { specialist(request); requirePermission(request, 'chat.write');
const conversationId = parse(uuid, (request.params as { conversationId?: string }).conversationId);
const claimed = await database.supportConversation.updateMany({ where: { id: conversationId, status: 'OPEN', assignedSpecialistId: null }, data: { status: 'ASSIGNED', assignedSpecialistId: request.userId, updatedAt: new Date() } });
if (!claimed.count) throw new ApiError(409, 'SUPPORT_ALREADY_ASSIGNED', 'This Live Help conversation was already assigned');
await database.supportMessage.create({ data: { conversationId, type: 'SYSTEM', content: 'A cybersecurity specialist joined the Live Help conversation.' } });
return database.supportConversation.findUnique({ where: { id: conversationId } });
});
  app.get('/specialist/support/:conversationId/messages', async (request) => { specialist(request); requirePermission(request, 'chat.read');
const conversationId = parse(uuid, (request.params as { conversationId?: string }).conversationId);
const conversation = await database.supportConversation.findFirst({ where: { id: conversationId, assignedSpecialistId: request.userId }, select: { id: true } });
if (!conversation) throw new ApiError(404, 'SUPPORT_CONVERSATION_NOT_FOUND', 'Assigned Live Help conversation was not found');
return database.supportMessage.findMany({ where: { conversationId }, orderBy: { createdAt: 'asc' }, take: 300, include: { author: { select: { displayName: true } } } });
});
  app.post('/specialist/support/:conversationId/messages', async (request, reply) => { specialist(request); requirePermission(request, 'chat.write');
const conversationId = parse(uuid, (request.params as { conversationId?: string }).conversationId); const { content } = parse(z.object({ content: z.string().trim().min(1).max(4000) }), request.body);
const conversation = await database.supportConversation.findFirst({ where: { id: conversationId, assignedSpecialistId: request.userId, status: 'ASSIGNED' }, select: { id: true, tenantId: true } });
if (!conversation) throw new ApiError(404, 'SUPPORT_CONVERSATION_NOT_FOUND', 'Active assigned Live Help conversation was not found');
const message = await database.supportMessage.create({ data: { conversationId, authorUserId: request.userId!, type: 'SPECIALIST', content }, include: { author: { select: { displayName: true } } } });
await database.supportConversation.update({ where: { id: conversationId }, data: { updatedAt: new Date() } });
await writeAudit({ tenantId: conversation.tenantId, actorUserId: request.userId, requestId: request.id, action: 'support.specialist_replied', resourceType: 'support_conversation', resourceId: conversationId, ipAddress: request.ip });
return reply.code(201).send(message);
});
  app.post('/specialist/support/:conversationId/close', async (request) => { specialist(request); requirePermission(request, 'chat.write');
const conversationId = parse(uuid, (request.params as { conversationId?: string }).conversationId);
const closed = await database.supportConversation.updateMany({ where: { id: conversationId, assignedSpecialistId: request.userId, status: 'ASSIGNED' }, data: { status: 'CLOSED', closedAt: new Date(), updatedAt: new Date() } });
if (!closed.count) throw new ApiError(404, 'SUPPORT_CONVERSATION_NOT_FOUND', 'Active assigned Live Help conversation was not found');
await database.supportMessage.create({ data: { conversationId, type: 'SYSTEM', content: 'This Live Help conversation was closed. Start a new conversation if you need more help.' } });
return { closed: true };
});

  app.post('/specialist/jobs/:ticketId/accept', async (request) => { specialist(request);
requirePermission(request, 'specialist.jobs.accept');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
await expireAssignments();
const accepted = await database.ticket.updateMany({ where: { id: ticketId, OR: [{ status: 'QUEUED', assignedSpecialistId: null }, { status: 'ASSIGNED', assignedSpecialistId: request.userId, assignmentExpiresAt: { gt: new Date() } }] }, data: { status: 'ACCEPTED', assignedSpecialistId: request.userId, acceptedAt: new Date(), assignmentExpiresAt: null, progressStage: 'ACCEPTED', progressNote: 'A cybersecurity specialist accepted your request.', progressUpdatedAt: new Date() } });
if (accepted.count !== 1) throw new ApiError(409, 'TICKET_ACCEPTANCE_CONFLICT', 'Ticket is unavailable or already accepted');
await writeAudit({ actorUserId: request.userId, requestId: request.id, action: 'ticket.accepted', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip });
return database.ticket.findUnique({ where: { id: ticketId } });
});
  app.post('/specialist/tickets/:ticketId/requeue', async (request) => { specialist(request);
requirePermission(request, 'specialist.jobs.accept');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const changed = await database.ticket.updateMany({ where: { id: ticketId, assignedSpecialistId: request.userId, status: { in: ['ASSIGNED','ACCEPTED','AWAITING_AUTHORIZATION','AWAITING_CUSTOMER'] } }, data: { status: 'QUEUED', assignedSpecialistId: null, assignmentExpiresAt: null } });
if (!changed.count) throw new ApiError(409, 'TICKET_REQUEUE_DENIED', 'Ticket cannot be requeued');
return { requeued: true };
});
  app.post('/specialist/tickets/:ticketId/request-authorization', async (request) => {
    specialist(request); requirePermission(request, 'specialist.jobs.accept');
    const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
    const changed = await database.ticket.updateMany({ where: { id: ticketId, assignedSpecialistId: request.userId, status: 'ACCEPTED' }, data: { status: 'AWAITING_AUTHORIZATION', progressStage: 'AWAITING_APPROVAL', progressNote: 'Your approval is required before remediation begins.', progressUpdatedAt: new Date() } });
    if (!changed.count) throw new ApiError(409, 'AUTHORIZATION_REQUEST_DENIED', 'Accepted ticket was not found');
    await writeAudit({ actorUserId: request.userId, requestId: request.id, action: 'remediation.authorization_requested', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip });
    const ticket=await database.ticket.findUniqueOrThrow({where:{id:ticketId}});await publishTenantEvent({tenantId:ticket.tenantId,eventType:'AUTHORIZATION_REQUESTED',deduplicationKey:`authorization-requested:${ticketId}`,title:'Remediation authorization requested',message:`Authorization is required before work can begin on “${ticket.title}”.`,actionUrl:`/customer/websites/${ticket.websiteId}/tickets`,data:{ticketId,websiteId:ticket.websiteId}},options.queues?.notifications);
    return { status: 'AWAITING_AUTHORIZATION' };
  });
  app.post('/specialist/tickets/:ticketId/transfer', async (request) => {
    specialist(request); requirePermission(request, 'specialist.jobs.accept');
    const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId); const { specialistId } = parse(z.object({ specialistId: uuid }), request.body);
    const valid = await database.userRole.findFirst({ where: { userId: specialistId, user: { status: 'APPROVED' }, role: { name: 'Cybersecurity Specialist' }, tenant: { memberships: { some: { userId: specialistId, status: 'ACTIVE' } } } }, select: { tenantId: true } }); if (!valid) throw new ApiError(400, 'SPECIALIST_INVALID', 'Transfer target is not an active specialist');
    const changed = await database.ticket.updateMany({ where: { id: ticketId, assignedSpecialistId: request.userId, status: { in: ['ACCEPTED','AWAITING_AUTHORIZATION','AWAITING_CUSTOMER','ESCALATED'] } }, data: { status: 'ASSIGNED', assignedSpecialistId: specialistId, acceptedAt: null, assignmentExpiresAt: new Date(Date.now() + 30 * 60_000) } });
    if (!changed.count) throw new ApiError(409, 'TICKET_TRANSFER_DENIED', 'Ticket cannot be transferred'); await database.remediationSession.updateMany({ where: { ticketId, status: 'ACTIVE' }, data: { status: 'REVOKED', revokedAt: new Date(), revokedReason: 'ticket_transferred' } });
    await writeAudit({ actorUserId: request.userId, requestId: request.id, action: 'ticket.transferred', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip, metadata: { specialistId } }); return { transferred: true };
  });
  app.post('/specialist/tickets/:ticketId/escalate', async (request) => { specialist(request);
requirePermission(request, 'specialist.jobs.accept');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const changed = await database.ticket.updateMany({ where: { id: ticketId, assignedSpecialistId: request.userId, status: { notIn: ['RESOLVED','CLOSED','CANCELLED'] } }, data: { status: 'ESCALATED', escalatedAt: new Date() } });
if (!changed.count) throw new ApiError(409, 'TICKET_ESCALATION_DENIED', 'Ticket cannot be escalated');
return { escalated: true };
});
  app.post('/owner/specialist/tickets/:ticketId/assign', async (request) => { requireOwnerMfa(request);
requirePermission(request, 'remediation.manage');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const { specialistId, timeoutMinutes } = parse(z.object({ specialistId: uuid, timeoutMinutes: z.number().int().min(5).max(240).default(30) }), request.body);
const valid = await database.userRole.findFirst({ where: { userId: specialistId, user: { status: 'APPROVED' }, role: { name: 'Cybersecurity Specialist' }, tenant: { memberships: { some: { userId: specialistId, status: 'ACTIVE' } } } }, select: { tenantId: true } });
if (!valid) throw new ApiError(400, 'SPECIALIST_INVALID', 'Assigned user is not an active specialist');
const changed = await database.ticket.updateMany({ where: { id: ticketId, status: { in: ['QUEUED','ESCALATED'] } }, data: { status: 'ASSIGNED', assignedSpecialistId: specialistId, assignmentExpiresAt: new Date(Date.now() + timeoutMinutes * 60_000) } });
if (!changed.count) throw new ApiError(409, 'TICKET_ASSIGNMENT_CONFLICT', 'Ticket cannot be assigned');
const assigned=await database.ticket.findUniqueOrThrow({where:{id:ticketId}});await publishTenantEvent({tenantId:assigned.tenantId,eventType:'SPECIALIST_ASSIGNED',deduplicationKey:`specialist-assigned:${ticketId}:${specialistId}`,title:'Specialist assigned',message:`A cybersecurity specialist was assigned to “${assigned.title}”.`,actionUrl:`/customer/websites/${assigned.websiteId}/tickets`,data:{ticketId,websiteId:assigned.websiteId}},options.queues?.notifications);
return { assigned: true };
});

  app.post('/websites/:websiteId/tickets/:ticketId/queue', async (request) => { requirePermission(request, 'tickets.create');
const { websiteId, ticketId } = parse(ids, request.params);
const changed = await database.ticket.updateMany({ where: { id: ticketId, websiteId, tenantId: request.tenantId!, status: 'CREATED' }, data: { status: 'QUEUED' } });
if (!changed.count) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Ticket was not found or cannot be queued');
return { status: 'QUEUED' };
});
  app.post('/websites/:websiteId/tickets/:ticketId/authorization', async (request, reply) => { requirePermission(request, 'remediation.authorize');
const { websiteId, ticketId } = parse(ids, request.params);
const input = parse(z.object({ scope: scopes, expiresInMinutes: z.number().int().min(5).max(1440) }), request.body);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, websiteId, tenantId: request.tenantId!, status: 'AWAITING_AUTHORIZATION' } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Ticket was not found or is not awaiting authorization');
const authorization = await database.$transaction(async (tx) => { await tx.remediationAuthorization.updateMany({ where: { ticketId, revokedAt: null }, data: { revokedAt: new Date() } });
const created = await tx.remediationAuthorization.create({ data: { tenantId: request.tenantId!, websiteId, ticketId, authorizedByUserId: request.userId!, scope: input.scope, expiresAt: new Date(Date.now() + input.expiresInMinutes * 60_000) } });
await tx.ticket.update({ where: { id: ticketId }, data: { status: 'AUTHORIZED', progressStage: 'BACKUP', progressNote: 'Access approved. The specialist is preparing a verified backup.', progressUpdatedAt: new Date() } });
return created;
});
await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: 'remediation.authorized', resourceType: 'ticket', resourceId: ticketId, ipAddress: request.ip, metadata: { scope: input.scope, expiresAt: authorization.expiresAt } });
return reply.code(201).send(authorization);
});
  app.post('/specialist/tickets/:ticketId/backup', async (request, reply) => { specialist(request);
requirePermission(request, 'remediation.execute');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId, status: 'AUTHORIZED' } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'Authorized assigned ticket was not found');
const auth = await database.remediationAuthorization.findFirst({ where: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, revokedAt: null, expiresAt: { gt: new Date() } }, orderBy: { authorizedAt: 'desc' } });
if (!auth) throw new ApiError(409, 'AUTHORIZATION_EXPIRED', 'Valid customer authorization is required');
const backup = await database.$transaction(async (tx) => { const created = await tx.backup.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, purpose: 'PRE_REMEDIATION', protectedUntil: auth.expiresAt } });
await tx.ticket.update({ where: { id: ticketId }, data: { status: 'BACKUP_PENDING', progressStage: 'BACKUP', progressNote: 'Creating and verifying a restore point before any changes.', progressUpdatedAt: new Date() } });
return created;
});
try { if (!options.queues?.backups) throw new Error('queue unavailable'); await options.queues.backups.add('remediation.restore-point', { action: 'CREATE', backupId: backup.id, tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId }, { jobId: backup.id, attempts: 1, removeOnComplete: 1000, removeOnFail: 5000 });
} catch { await database.$transaction([database.backup.update({ where: { id: backup.id }, data: { status: 'FAILED', errorCode: 'QUEUE_UNAVAILABLE', completedAt: new Date() } }), database.ticket.update({ where: { id: ticketId }, data: { status: 'AWAITING_CUSTOMER' } })]);
throw new ApiError(503, 'QUEUE_UNAVAILABLE', 'Backup could not be queued. Remediation stopped');
} await writeAudit({ tenantId: ticket.tenantId, actorUserId: request.userId, requestId: request.id, action: 'remediation.backup_requested', resourceType: 'backup', resourceId: backup.id, ipAddress: request.ip, metadata: { ticketId, websiteId: ticket.websiteId } }); return reply.code(202).send(backup);
});
  app.post('/specialist/tickets/:ticketId/sessions', async (request, reply) => { specialist(request);
requirePermission(request, 'remediation.execute');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const { durationMinutes } = parse(z.object({ durationMinutes: z.number().int().min(5).max(120).default(60) }), request.body);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId, status: 'READY' } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_READY', 'Assigned ticket is not ready');
const authorization = await database.remediationAuthorization.findFirst({ where: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, revokedAt: null, expiresAt: { gt: new Date() } }, orderBy: { authorizedAt: 'desc' } });
const backup = await database.backup.findFirst({ where: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, status: 'SUCCEEDED', verifiedAt: { not: null } }, orderBy: { completedAt: 'desc' } });
if (!authorization) throw new ApiError(409, 'AUTHORIZATION_EXPIRED', 'Valid customer authorization is required');
if (!backup) throw new ApiError(409, 'BACKUP_NOT_VERIFIED', 'Verified restore point is required');
const token = generateOpaqueToken();
const expiresAt = new Date(Math.min(Date.now() + durationMinutes * 60_000, authorization.expiresAt.getTime()));
const session = await database.$transaction(async (tx) => { await tx.remediationSession.updateMany({ where: { ticketId, status: 'ACTIVE' }, data: { status: 'REVOKED', revokedAt: new Date(), revokedReason: 'replaced' } });
const created = await tx.remediationSession.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, specialistId: request.userId!, authorizationId: authorization.id, tokenHash: hashOpaqueToken(token, options.environment.SESSION_SECRET), scope: authorization.scope, expiresAt } });
await tx.ticket.update({ where: { id: ticketId }, data: { status: 'IN_PROGRESS', progressStage: 'REMEDIATING', progressNote: 'A time-limited secure session is active and the approved fix is in progress.', progressUpdatedAt: new Date() } });
return created;
});
await writeAudit({ tenantId: ticket.tenantId, actorUserId: request.userId, requestId: request.id, action: 'remediation.session_created', resourceType: 'remediation_session', resourceId: session.id, ipAddress: request.ip, metadata: { ticketId, websiteId: ticket.websiteId, scope: session.scope, expiresAt } });
return reply.code(201).send({ id: session.id, token, scope: session.scope, expiresAt });
});
  app.delete('/specialist/sessions/:sessionId', async (request, reply) => { specialist(request);
requirePermission(request, 'remediation.execute');
const sessionId = parse(uuid, (request.params as { sessionId?: string }).sessionId);
const changed = await database.remediationSession.updateMany({ where: { id: sessionId, specialistId: request.userId, status: 'ACTIVE' }, data: { status: 'REVOKED', revokedAt: new Date(), revokedReason: 'specialist_revoked' } });
if (!changed.count) throw new ApiError(404, 'SESSION_NOT_FOUND', 'Active remediation session not found');
await writeAudit({ actorUserId: request.userId, requestId: request.id, action: 'remediation.session_revoked', resourceType: 'remediation_session', resourceId: sessionId, ipAddress: request.ip });
return reply.code(204).send();
});

  app.post('/owner/remediation/playbooks', async (request, reply) => { requireOwnerMfa(request);
requirePermission(request, 'remediation.manage');
const input = parse(z.object({ name: z.string().trim().min(2).max(160), version: z.number().int().positive(), description: z.string().max(2000).optional(), enabled: z.boolean().default(false), actionKeys: z.array(z.literal('FINDING_MARK_IN_REMEDIATION')).min(1), requiredScopes: scopes }), request.body);
return reply.code(201).send(await database.remediationPlaybook.create({ data: { name: input.name, version: input.version, enabled: input.enabled, actionKeys: input.actionKeys, requiredScopes: input.requiredScopes, ...(input.description ? { description: input.description } : {}) } }));
});
  app.post('/specialist/tickets/:ticketId/remediate', async (request, reply) => { specialist(request);
requirePermission(request, 'remediation.execute');
const ticketId = parse(uuid, (request.params as { ticketId?: string }).ticketId);
const { playbookId } = parse(z.object({ playbookId: uuid }), request.body);
const rawToken = request.headers['x-remediation-token'];
if (typeof rawToken !== 'string') throw new ApiError(401, 'REMEDIATION_TOKEN_REQUIRED', 'Temporary remediation token required');
const ticket = await database.ticket.findFirst({ where: { id: ticketId, assignedSpecialistId: request.userId, status: 'IN_PROGRESS' }, include: { finding: true } });
if (!ticket) throw new ApiError(404, 'TICKET_NOT_FOUND', 'In-progress assigned ticket not found');
const session = await database.remediationSession.findUnique({ where: { tokenHash: hashOpaqueToken(rawToken, options.environment.SESSION_SECRET) } });
const authorization = session ? await database.remediationAuthorization.findUnique({ where: { id: session.authorizationId } }) : null;
const backup = await database.backup.findFirst({ where: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, status: 'SUCCEEDED' }, orderBy: { completedAt: 'desc' } });
const playbook = await database.remediationPlaybook.findFirst({ where: { id: playbookId, enabled: true } });
if (!session || !authorization || !backup || !playbook) throw new ApiError(409, 'REMEDIATION_PREREQUISITE_MISSING', 'Session, authorization, backup, and enabled playbook are required');
try { assertRemediationGate({ tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, specialistId: request.userId!, authorization, backup, session, requiredScopes: playbook.requiredScopes });
} catch (error) { if (error instanceof RemediationGateError) throw new ApiError(409, error.code, error.message);
throw error;
} if (!ticket.findingId || !playbook.actionKeys.every((key) => key === 'FINDING_MARK_IN_REMEDIATION')) throw new ApiError(409, 'PLAYBOOK_UNSUPPORTED', 'Playbook action is not supported for this ticket');
const beforeScanId = ticket.finding?.scanId ?? null;
const [run, postScan] = await database.$transaction(async (tx) => { await tx.securityFinding.updateMany({ where: { id: ticket.findingId!, tenantId: ticket.tenantId, websiteId: ticket.websiteId }, data: { status: 'IN_REMEDIATION' } });
const scan = await tx.scan.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId } });
const created = await tx.remediationRun.create({ data: { tenantId: ticket.tenantId, websiteId: ticket.websiteId, ticketId, specialistId: request.userId!, authorizationId: authorization.id, sessionId: session.id, backupId: backup.id, playbookId, status: 'AWAITING_POST_SCAN', executedActions: playbook.actionKeys, beforeScanId, postScanId: scan.id, startedAt: new Date() } });
await tx.ticket.update({ where: { id: ticketId }, data: { status: 'POST_SCAN', progressStage: 'VERIFYING', progressNote: 'The fix is complete. A post-fix security scan is verifying the result.', progressUpdatedAt: new Date() } });
await tx.remediationSession.update({ where: { id: session.id }, data: { status: 'COMPLETED', revokedAt: new Date(), revokedReason: 'playbook_completed' } });
return [created, scan] as const;
});
try { await options.queues?.scans?.add('scan.requested', { scanId: postScan.id, websiteId: ticket.websiteId, tenantId: ticket.tenantId }, { jobId: postScan.id, attempts: 3, removeOnComplete: 1000, removeOnFail: 5000 });
} catch { await database.$transaction([database.remediationRun.update({ where: { id: run.id }, data: { status: 'FAILED', errorCode: 'POST_SCAN_QUEUE_UNAVAILABLE', completedAt: new Date() } }), database.ticket.update({ where: { id: ticketId }, data: { status: 'AWAITING_CUSTOMER' } })]);
throw new ApiError(503, 'POST_SCAN_QUEUE_UNAVAILABLE', 'Post-remediation scan could not be queued');
} await writeAudit({ tenantId: ticket.tenantId, actorUserId: request.userId, requestId: request.id, action: 'remediation.playbook_executed', resourceType: 'remediation_run', resourceId: run.id, ipAddress: request.ip, metadata: { playbookId, actions: playbook.actionKeys, postScanId: postScan.id } });
await publishTenantEvent({tenantId:ticket.tenantId,eventType:'REMEDIATION_STARTED',deduplicationKey:`remediation-started:${run.id}`,title:'Remediation started',message:`Approved remediation started for “${ticket.title}”.`,actionUrl:`/customer/websites/${ticket.websiteId}/tickets`,data:{ticketId,runId:run.id,websiteId:ticket.websiteId}},options.queues?.notifications);
return reply.code(202).send({ runId: run.id, postScanId: postScan.id, sessionRevoked: true });
});
  app.post('/specialist/remediation/:runId/complete-post-scan', async (request) => { specialist(request);
requirePermission(request, 'remediation.execute');
const runId = parse(uuid, (request.params as { runId?: string }).runId);
const run = await database.remediationRun.findFirst({ where: { id: runId, specialistId: request.userId, status: 'AWAITING_POST_SCAN' } });
if (!run?.postScanId) throw new ApiError(404, 'REMEDIATION_RUN_NOT_FOUND', 'Awaiting post-scan run not found');
const scan = await database.scan.findFirst({ where: { id: run.postScanId, tenantId: run.tenantId, websiteId: run.websiteId, status: 'SUCCEEDED' } });
if (!scan) throw new ApiError(409, 'POST_SCAN_INCOMPLETE', 'Post-remediation scan has not succeeded');
const [beforeOpen, afterOpen] = await Promise.all([run.beforeScanId ? database.securityFinding.count({ where: { scanId: run.beforeScanId, status: { in: ['OPEN','REOPENED','IN_REMEDIATION'] } } }) : 0, database.securityFinding.count({ where: { scanId: run.postScanId, status: { in: ['OPEN','REOPENED','IN_REMEDIATION'] } } })]);
const comparison = { beforeOpenFindings: beforeOpen, afterOpenFindings: afterOpen, comparedAt: new Date().toISOString() };
const [, , report]=await database.$transaction([database.remediationRun.update({ where: { id: runId }, data: { status: 'SUCCEEDED', comparison, completedAt: new Date() } }), database.ticket.update({ where: { id: run.ticketId }, data: { status: 'RESOLVED', progressStage: 'DELIVERED', progressNote: 'Fix delivered and verified by the post-remediation security scan.', progressUpdatedAt: new Date() } }), database.report.create({ data: { tenantId: run.tenantId, websiteId: run.websiteId,requestedByUserId:request.userId!,type:'BEFORE_AFTER',sourceId:runId,title: `Remediation comparison ${runId}` } })]);try{if(!options.queues?.reports)throw new Error('queue unavailable');await options.queues.reports.add('report.requested',{reportId:report.id,websiteId:run.websiteId,tenantId:run.tenantId},{jobId:report.id,attempts:3,backoff:{type:'exponential',delay:2_000},removeOnComplete:1000,removeOnFail:5000});}catch{await database.report.update({where:{id:report.id},data:{status:'FAILED',errorCode:'QUEUE_UNAVAILABLE',completedAt:new Date()}});}
await writeAudit({ tenantId: run.tenantId, actorUserId: request.userId, requestId: request.id, action: 'remediation.post_scan_compared', resourceType: 'remediation_run', resourceId: runId, ipAddress: request.ip, metadata: comparison });await publishTenantEvent({tenantId:run.tenantId,eventType:'POST_SCAN',deduplicationKey:`post-scan:${runId}`,title:'Post-remediation scan completed',message:`The post-scan comparison completed with ${afterOpen} open finding(s).`,actionUrl:`/customer/websites/${run.websiteId}/reports`,data:{runId,beforeOpen,afterOpen}},options.queues?.notifications);await publishTenantEvent({tenantId:run.tenantId,eventType:'REMEDIATION_COMPLETED',deduplicationKey:`remediation-completed:${runId}`,title:'Remediation completed',message:'Remediation and its post-scan verification completed.',actionUrl:`/customer/websites/${run.websiteId}/tickets`,data:{runId,ticketId:run.ticketId}},options.queues?.notifications);return comparison;
});

  app.put('/owner/warranty/tenants/:tenantId', async (request) => { requireOwnerMfa(request);
requirePermission(request, 'warranty.manage');
const tenantId = parse(uuid, (request.params as { tenantId?: string }).tenantId);
const input = parse(z.object({ durationDays: z.number().int().min(1).max(3650), eligibleSeverities: z.array(z.enum(['LOW','MEDIUM','HIGH','CRITICAL'])).min(1), exclusions: z.array(z.string().trim().min(1).max(240)).max(50), enabled: z.boolean() }), request.body);
return database.warrantyPolicy.upsert({ where: { tenantId }, create: { tenantId, ...input }, update: input });
});
  app.post('/websites/:websiteId/tickets/:ticketId/warranty-claims', async (request, reply) => { requirePermission(request, 'tickets.create'); const { websiteId, ticketId } = parse(ids, request.params);
const { findingId, reason } = parse(z.object({ findingId: uuid.optional(), reason: z.string().trim().min(10).max(4000) }), request.body);
const ticket = await database.ticket.findFirst({ where: { id: ticketId, websiteId, tenantId: request.tenantId!, status: { in: ['RESOLVED','CLOSED'] } } });
const policy = await database.warrantyPolicy.findUnique({ where: { tenantId: request.tenantId! } });
if (!ticket || !policy?.enabled) throw new ApiError(404, 'WARRANTY_NOT_AVAILABLE', 'Eligible warranty was not found');
const run = await database.remediationRun.findFirst({ where: { ticketId, status: 'SUCCEEDED', completedAt: { gte: new Date(Date.now() - policy.durationDays * 86_400_000) } }, orderBy: { completedAt: 'desc' } });
const finding = findingId ? await database.securityFinding.findFirst({ where: { id: findingId, tenantId: request.tenantId!, websiteId } }) : null;
if (!run || (finding && !policy.eligibleSeverities.includes(finding.severity))) throw new ApiError(409, 'WARRANTY_INELIGIBLE', 'Claim is outside the configured warranty');
const claim=await database.warrantyClaim.create({ data: { tenantId: request.tenantId!, websiteId, ticketId, submittedByUserId: request.userId!, reason, ...(findingId ? { findingId } : {}) } });await publishTenantEvent({tenantId:request.tenantId!,recipientId:request.userId!,eventType:'WARRANTY',deduplicationKey:`warranty:${claim.id}`,title:'Warranty claim submitted',message:'Your warranty claim was submitted for review.',actionUrl:`/customer/websites/${websiteId}/tickets`,data:{claimId:claim.id,ticketId}},options.queues?.notifications);return reply.code(201).send(claim);
});
}
