// Shared, secret-free service descriptions. Choosing a service is not execution authority.
export const websiteServices = [
  { id: 'security', label: 'Fix hacks & security', name: 'Fix hacks & security', code: '01', description: 'Recover a compromised website and plan stronger protection.', hint: 'Describe suspicious changes, affected pages and when the problem began. Only include websites you own or are authorized to administer.', success: 'Define the recovery checks, affected functionality and backup requirements.', boundary: 'Assessment, cleanup and hardening need verified access, reviewed evidence and separate change approval.', links: [{ label: 'Saved security findings', path: '/findings' }, { label: 'Backup & recovery records', path: '/backups' }] },
  { id: 'development', label: 'Full-stack web development', name: 'Develop a feature', code: '02', description: 'Plan frontend, backend, database and integration features.', hint: 'Describe the feature, the pages it affects and who will use it. Include your frontend/backend stack and existing integrations, without credentials.', success: 'List user flows, API behaviour and compatibility checks that must pass.', boundary: 'Source review and implementation require scoped files; runtime testing and releases need an isolated runner and approval.', links: [{ label: 'Connection methods', path: '/access' }] },
  { id: 'redesign', label: 'Website redesign', name: 'Redesign a page', code: '03', description: 'Improve your layout, branding and mobile experience.', hint: 'Describe the layout, mobile behaviour and visual result you want. Name the pages, brand constraints and references you are allowed to use.', success: 'Define mobile/desktop sizes, accessibility and the visual result to check.', boundary: 'Design changes are scoped to approved pages and assets. No automatic publishing or invented accessibility results.', links: [{ label: 'Connection methods', path: '/access' }] },
  { id: 'issue', label: 'Fix an issue', name: 'Fix an issue', code: '04', description: 'Resolve broken pages, bugs and unexpected behaviour.', hint: 'Include steps to reproduce, what happens now and what should happen. Describe errors without private customer data.', success: 'Describe a repeatable test that fails now and should pass after the fix.', boundary: 'A request records the problem. Diagnosis, patches and verification need the relevant source, access and approval.', links: [{ label: 'Saved reports', path: '/reports' }] },
  { id: 'server', label: 'Server-side work', name: 'Server-side work', code: '05', description: 'Plan hosting, deployment, performance and server maintenance.', hint: 'Describe the server task, OS, hosting setup and affected services. Include downtime constraints; use Connections for access information.', success: 'Specify health checks, permitted downtime, backup and rollback expectations.', boundary: 'No root access, reboot, database reset or production change is authorized by this form.', links: [{ label: 'SSH & platform access', path: '/access' }, { label: 'Backup & recovery records', path: '/backups' }] },
  { id: 'seo', label: 'SEO work', name: 'SEO work', code: '06', description: 'Plan technical SEO, page metadata and search visibility improvements.', hint: 'List the pages, indexing or metadata problems, target audience and approved content changes. Do not include search-console tokens.', success: 'Specify checks for titles, canonical URLs, robots rules, structured data or page performance.', boundary: 'Search ranking is not guaranteed. Crawling, external accounts and content publication need separate authorization.', links: [{ label: 'Connection methods', path: '/access' }, { label: 'Saved reports', path: '/reports' }] },
  { id: 'automation', label: 'Automation', name: 'Automation', code: '07', description: 'Plan repeatable workflows, scheduled tasks and integrations.', hint: 'Describe the trigger, inputs, expected output and systems involved. Include schedule, rate limits and how the workflow should stop.', success: 'Define duplicate prevention, retry limits, notifications and failure recovery.', boundary: 'No schedule, webhook, external message or paid API call starts from selecting or submitting this service request.', links: [{ label: 'Connection methods', path: '/access' }, { label: 'Monitoring records', path: '/monitoring' }] }
] as const;

export type WebsiteService = (typeof websiteServices)[number];
export function getWebsiteService(value: string | null | undefined): WebsiteService | undefined {
  return websiteServices.find(service => service.id === value);
}
export function websiteWorkspaceHref(websiteId: string, service?: WebsiteService, suffix = '') {
  const base = `/customer/websites/${encodeURIComponent(websiteId)}${suffix}`;
  return service ? `${base}?service=${service.id}` : base;
}
