import { createHmac, randomBytes } from 'node:crypto';
import { database } from '@zerochack/database';
import type { Environment } from '@zerochack/config';
import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { ApiError } from '../../errors.js';
import { authenticate, requireOwnerMfa, requirePermission } from '../auth/security.js';
import { parse } from '../auth/routes.js';
import { writeAudit } from '../auth/service.js';
import type { Queue } from 'bullmq';
import { publishTenantEvent } from '../communications/service.js';

const uuid = z.string().uuid(); const referralCookie = 'zerochack_referral';
const tokenHash = (value: string, secret: string) => createHmac('sha256', secret).update(value).digest('hex');
function affiliate(request: FastifyRequest, permission = 'referrals.read') { if (!request.roleNames?.includes('Affiliate')) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Resource not found'); requirePermission(request, permission); }
async function profileFor(request: FastifyRequest) { affiliate(request); const profile = await database.affiliateProfile.findUnique({ where: { tenantId: request.tenantId! } }); if (!profile?.active) throw new ApiError(403, 'AFFILIATE_INACTIVE', 'Affiliate profile is not active'); return profile; }

export const affiliateRoutes: FastifyPluginAsync<{ environment: Environment;notificationsQueue?:Queue }> = async (app, { environment,notificationsQueue }) => {
  app.post('/affiliate/attributions', async (request, reply) => {
    const { code } = parse(z.object({ code: z.string().trim().min(6).max(32).transform((value) => value.toUpperCase()) }), request.body); const profile = await database.affiliateProfile.findUnique({ where: { code } }); const config = await database.affiliateProgramConfig.findFirst({ where: { active: true }, orderBy: { version: 'desc' } });
    if (!profile?.active || !config) throw new ApiError(404, 'REFERRAL_UNAVAILABLE', 'Referral code is not available');
    const existingRaw = request.cookies[referralCookie]; if (existingRaw) { const existing = await database.referralAttribution.findUnique({ where: { tokenHash: tokenHash(existingRaw, environment.SESSION_SECRET) } }); if (existing?.status === 'ACTIVE' && existing.expiresAt > new Date()) return { attributed: true, duplicate: true, expiresAt: existing.expiresAt }; }
    const raw = randomBytes(32).toString('base64url'); const attribution = await database.referralAttribution.create({ data: { affiliateId: profile.id, configId: config.id, tokenHash: tokenHash(raw, environment.SESSION_SECRET), expiresAt: new Date(Date.now() + config.attributionWindowDays * 86_400_000) } }); reply.setCookie(referralCookie, raw, { httpOnly: true, secure: environment.NODE_ENV === 'production', sameSite: 'lax', path: '/', maxAge: config.attributionWindowDays * 86_400 }); await writeAudit({ tenantId: profile.tenantId, requestId: request.id, action: 'affiliate.attribution_captured', resourceType: 'referral_attribution', resourceId: attribution.id, ipAddress: request.ip }); return reply.code(201).send({ attributed: true, duplicate: false, expiresAt: attribution.expiresAt });
  });

  app.register(async (secure) => {
    secure.addHook('preHandler', (request) => authenticate(request, environment)); secure.addHook('onSend', async (_request, reply) => { void reply.header('cache-control', 'private, no-store'); });
    secure.post('/affiliate/attributions/claim', async (request) => {
      if (!request.roleNames?.includes('Customer')) throw new ApiError(403, 'CUSTOMER_REQUIRED', 'A customer account is required'); const raw = request.cookies[referralCookie]; if (!raw) throw new ApiError(400, 'REFERRAL_TOKEN_MISSING', 'Referral attribution token is missing'); const hash = tokenHash(raw, environment.SESSION_SECRET);
      const claimed = await database.$transaction(async (tx) => { const attribution = await tx.referralAttribution.findUnique({ where: { tokenHash: hash }, include: { affiliate: true, config: true } }); if (!attribution || attribution.status !== 'ACTIVE' || attribution.expiresAt <= new Date()) throw new ApiError(400, 'REFERRAL_EXPIRED', 'Referral attribution is invalid or expired'); if (attribution.affiliate.tenantId === request.tenantId || attribution.affiliate.userId === request.userId) throw new ApiError(409, 'SELF_REFERRAL_FORBIDDEN', 'Self-referral is not permitted'); const existing = await tx.referralAttribution.findUnique({ where: { customerTenantId: request.tenantId! } }); if (existing && existing.id !== attribution.id) { if (existing.status === 'CONVERTED' || attribution.config.attributionModel === 'FIRST_TOUCH') throw new ApiError(409, 'ATTRIBUTION_ALREADY_CLAIMED', 'Customer attribution already exists'); await tx.referralAttribution.update({ where: { id: existing.id }, data: { customerTenantId: null, status: 'REJECTED' } }); } return tx.referralAttribution.update({ where: { id: attribution.id }, data: { customerTenantId: request.tenantId! } }); }, { isolationLevel: 'Serializable' }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: 'affiliate.attribution_claimed', resourceType: 'referral_attribution', resourceId: claimed.id, ipAddress: request.ip }); return { claimed: true };
    });

    secure.post('/affiliate/profile', async (request, reply) => { affiliate(request, 'referrals.create'); const existing = await database.affiliateProfile.findUnique({ where: { tenantId: request.tenantId! } }); if (existing) return { ...existing, duplicate: true }; const code = `ZC${randomBytes(8).toString('hex').toUpperCase()}`; const created = await database.affiliateProfile.create({ data: { tenantId: request.tenantId!, userId: request.userId!, code } }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: 'affiliate.profile_created', resourceType: 'affiliate_profile', resourceId: created.id, ipAddress: request.ip }); return reply.code(201).send({ ...created, duplicate: false }); });
    secure.get('/affiliate/referral-link', async (request) => { const profile = await profileFor(request); return { code: profile.code, url: `${environment.APP_URL}/?ref=${encodeURIComponent(profile.code)}` }; });
    secure.get('/affiliate/overview', async (request) => { const profile = await profileFor(request); const [referrals, conversions, commissions, payable, payouts] = await Promise.all([database.referralAttribution.count({ where: { affiliateId: profile.id } }), database.affiliateConversion.count({ where: { affiliateId: profile.id } }), database.affiliateCommission.count({ where: { affiliateId: profile.id } }), database.affiliateCommission.aggregate({ where: { affiliateId: profile.id, status: 'PAYABLE' }, _sum: { amountMinor: true } }), database.affiliatePayout.count({ where: { affiliateId: profile.id, status: { in: ['PENDING', 'APPROVED', 'PROCESSING'] } } })]); return { referrals, conversions, commissions, payableMinor: payable._sum.amountMinor ?? 0, pendingPayouts: payouts }; });
    secure.get('/affiliate/referrals', async (request) => { const profile = await profileFor(request); return { referrals: await database.referralAttribution.findMany({ where: { affiliateId: profile.id }, select: { id: true, status: true, attributedAt: true, expiresAt: true, convertedAt: true }, orderBy: { attributedAt: 'desc' } }) }; });
    secure.get('/affiliate/attribution', async (request) => { const profile = await profileFor(request); return { attributions: await database.referralAttribution.findMany({ where: { affiliateId: profile.id }, select: { id: true, status: true, attributedAt: true, expiresAt: true, convertedAt: true, config: { select: { version: true, attributionModel: true, attributionWindowDays: true } } }, orderBy: { attributedAt: 'desc' } }) }; });
    secure.get('/affiliate/commissions', async (request) => { const profile = await profileFor(request); return { commissions: await database.affiliateCommission.findMany({ where: { affiliateId: profile.id }, include: { conversion: { select: { recurringPeriod: true, convertedAt: true } } }, orderBy: { createdAt: 'desc' } }) }; });
    secure.get('/affiliate/transactions', async (request) => { const profile = await profileFor(request); return { transactions: await database.affiliateConversion.findMany({ where: { affiliateId: profile.id }, select: { id: true, recurringPeriod: true, convertedAt: true, paymentTransaction: { select: { amountMinor: true, currency: true, status: true, completedAt: true } }, packageVersion: { select: { name: true, version: true } } }, orderBy: { convertedAt: 'desc' } }) }; });
    secure.get('/affiliate/payouts', async (request) => { const profile = await profileFor(request); return { payouts: await database.affiliatePayout.findMany({ where: { affiliateId: profile.id }, select: { id: true, amountMinor: true, currency: true, status: true, failureCode: true, createdAt: true, updatedAt: true, paidAt: true }, orderBy: { createdAt: 'desc' } }) }; });
    secure.get('/affiliate/notifications', async (request) => { affiliate(request); return { notifications: await database.notification.findMany({ where: { tenantId: request.tenantId!,OR:[{recipientUserId:request.userId!},{recipientUserId:null}] }, orderBy: { createdAt: 'desc' }, take: 100 }) }; });

    secure.post('/owner/affiliate/programs', async (request, reply) => { requireOwnerMfa(request); requirePermission(request, 'affiliate.manage'); const input = parse(z.object({ attributionWindowDays: z.number().int().min(1).max(365), attributionModel: z.enum(['FIRST_TOUCH', 'LAST_TOUCH']), commissionKind: z.enum(['ONE_TIME', 'RECURRING']), calculation: z.enum(['PERCENTAGE', 'FIXED']), percentageBasisPoints: z.number().int().min(1).max(10_000).optional(), fixedAmountMinor: z.number().int().positive().optional(), recurringDurationMonths: z.number().int().min(1).max(120), payoutThresholdMinor: z.number().int().min(0), approvalRequired: z.boolean(), eligibilityRules: z.object({ minimumPaymentMinor: z.number().int().min(0).default(0), newCustomersOnly: z.boolean().default(false) }), eligiblePackageVersionIds: z.array(uuid).min(1).max(500) }).refine((value) => value.calculation === 'PERCENTAGE' ? value.percentageBasisPoints !== undefined && value.fixedAmountMinor === undefined : value.fixedAmountMinor !== undefined && value.percentageBasisPoints === undefined, 'Exactly one commission calculation value is required'), request.body); const packageCount = await database.packageVersion.count({ where: { id: { in: input.eligiblePackageVersionIds } } }); if (packageCount !== new Set(input.eligiblePackageVersionIds).size) throw new ApiError(404, 'ELIGIBLE_PRODUCT_NOT_FOUND', 'One or more eligible products were not found'); const config = await database.$transaction(async (tx) => { await tx.affiliateProgramConfig.updateMany({ where: { active: true }, data: { active: false } }); const latest = await tx.affiliateProgramConfig.aggregate({ _max: { version: true } }); return tx.affiliateProgramConfig.create({ data: { version: (latest._max.version ?? 0) + 1, active: true, createdByUserId: request.userId!, attributionWindowDays: input.attributionWindowDays, attributionModel: input.attributionModel, commissionKind: input.commissionKind, calculation: input.calculation, ...(input.percentageBasisPoints !== undefined ? { percentageBasisPoints: input.percentageBasisPoints } : {}), ...(input.fixedAmountMinor !== undefined ? { fixedAmountMinor: input.fixedAmountMinor } : {}), recurringDurationMonths: input.recurringDurationMonths, payoutThresholdMinor: input.payoutThresholdMinor, approvalRequired: input.approvalRequired, eligibilityRules: input.eligibilityRules, eligibleProducts: { create: [...new Set(input.eligiblePackageVersionIds)].map((packageVersionId) => ({ packageVersionId })) } }, include: { eligibleProducts: true } }); }, { isolationLevel: 'Serializable' }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: 'affiliate.program_configured', resourceType: 'affiliate_program_config', resourceId: config.id, ipAddress: request.ip, metadata: { version: config.version } }); return reply.code(201).send(config); });
    secure.patch('/owner/affiliate/commissions/:commissionId', async (request) => { requireOwnerMfa(request); requirePermission(request, 'affiliate.manage'); const id = parse(uuid, (request.params as { commissionId?: string }).commissionId); const { status } = parse(z.object({ status: z.enum(['APPROVED', 'CANCELLED']) }), request.body); const commission = await database.affiliateCommission.findUnique({ where: { id } }); if (!commission || commission.status !== 'PENDING') throw new ApiError(409, 'COMMISSION_TRANSITION_INVALID', 'Only pending commissions can be reviewed'); const updated = await database.affiliateCommission.update({ where: { id }, data: { status: status === 'APPROVED' ? 'PAYABLE' : 'CANCELLED', ...(status === 'APPROVED' ? { approvedAt: new Date() } : {}) } }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: `affiliate.commission_${status.toLowerCase()}`, resourceType: 'affiliate_commission', resourceId: id, ipAddress: request.ip }); return updated; });
    secure.post('/owner/affiliate/payouts', async (request, reply) => { requireOwnerMfa(request); requirePermission(request, 'affiliate.manage'); const input = parse(z.object({ affiliateId: uuid, currency: z.string().length(3).transform((v) => v.toUpperCase()), idempotencyKey: uuid }), request.body); const existing = await database.affiliatePayout.findUnique({ where: { idempotencyKey: input.idempotencyKey } }); if (existing) return { ...existing, duplicate: true }; const payout = await database.$transaction(async (tx) => { const profile = await tx.affiliateProfile.findUnique({ where: { id: input.affiliateId } }); const config = await tx.affiliateProgramConfig.findFirst({ where: { active: true }, orderBy: { version: 'desc' } }); if (!profile?.active || !config) throw new ApiError(409, 'PAYOUT_CONFIGURATION_INVALID', 'Affiliate or active program configuration is unavailable'); const commissions = await tx.affiliateCommission.findMany({ where: { affiliateId: profile.id, currency: input.currency, status: 'PAYABLE', payoutId: null }, select: { id: true, amountMinor: true } }); const amountMinor = commissions.reduce((sum, item) => sum + item.amountMinor, 0); if (amountMinor < config.payoutThresholdMinor) throw new ApiError(409, 'PAYOUT_THRESHOLD_NOT_MET', 'Payable balance is below the configured threshold'); const created = await tx.affiliatePayout.create({ data: { affiliateId: profile.id, affiliateTenantId: profile.tenantId, idempotencyKey: input.idempotencyKey, amountMinor, currency: input.currency, changedByUserId: request.userId! } }); await tx.affiliateCommission.updateMany({ where: { id: { in: commissions.map((item) => item.id) }, payoutId: null, status: 'PAYABLE' }, data: { payoutId: created.id } }); return created; }, { isolationLevel: 'Serializable' }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: 'affiliate.payout_created', resourceType: 'affiliate_payout', resourceId: payout.id, ipAddress: request.ip, metadata: { affiliateId: input.affiliateId, amountMinor: payout.amountMinor } });const recipient=await database.affiliateProfile.findUniqueOrThrow({where:{id:input.affiliateId}});await publishTenantEvent({tenantId:recipient.tenantId,recipientId:recipient.userId,eventType:'PAYOUT',deduplicationKey:`payout-created:${payout.id}`,title:'Payout created',message:`A payout of ${payout.amountMinor} ${payout.currency} is pending.`,actionUrl:'/affiliate/payouts',data:{payoutId:payout.id,status:payout.status}},notificationsQueue);return reply.code(201).send({ ...payout, duplicate: false }); });
    secure.patch('/owner/affiliate/payouts/:payoutId', async (request) => { requireOwnerMfa(request); requirePermission(request, 'affiliate.manage'); const id = parse(uuid, (request.params as { payoutId?: string }).payoutId); const input = parse(z.object({ status: z.enum(['APPROVED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED']), providerReference: z.string().trim().min(1).max(255).optional(), failureCode: z.string().trim().max(120).optional() }), request.body); const payout = await database.affiliatePayout.findUnique({ where: { id } }); if (!payout) throw new ApiError(404, 'PAYOUT_NOT_FOUND', 'Payout was not found'); const transitions: Record<string, string[]> = { PENDING: ['APPROVED', 'CANCELLED'], APPROVED: ['PROCESSING', 'CANCELLED'], PROCESSING: ['PAID', 'FAILED'] }; if (!transitions[payout.status]?.includes(input.status)) throw new ApiError(409, 'PAYOUT_TRANSITION_INVALID', `Cannot transition payout from ${payout.status} to ${input.status}`); if (input.status === 'PAID' && !input.providerReference) throw new ApiError(400, 'PAYOUT_CONFIRMATION_REQUIRED', 'A provider reference is required to confirm payment'); const updated = await database.$transaction(async (tx) => { const record = await tx.affiliatePayout.update({ where: { id }, data: { status: input.status, changedByUserId: request.userId!, ...(input.providerReference ? { providerReference: input.providerReference } : {}), ...(input.failureCode ? { failureCode: input.failureCode } : {}), ...(input.status === 'PAID' ? { paidAt: new Date() } : {}) } }); if (input.status === 'PAID') await tx.affiliateCommission.updateMany({ where: { payoutId: id }, data: { status: 'PAID' } }); if (['FAILED', 'CANCELLED'].includes(input.status)) await tx.affiliateCommission.updateMany({ where: { payoutId: id, status: 'PAYABLE' }, data: { payoutId: null } }); return record; }); await writeAudit({ tenantId: request.tenantId, actorUserId: request.userId, requestId: request.id, action: `affiliate.payout_${input.status.toLowerCase()}`, resourceType: 'affiliate_payout', resourceId: id, ipAddress: request.ip, metadata: { providerReferencePresent: Boolean(input.providerReference), failureCode: input.failureCode } });const recipient=await database.affiliateProfile.findUniqueOrThrow({where:{id:payout.affiliateId}});await publishTenantEvent({tenantId:recipient.tenantId,recipientId:recipient.userId,eventType:'PAYOUT',deduplicationKey:`payout-${input.status.toLowerCase()}:${id}`,title:`Payout ${input.status.toLowerCase()}`,message:`Your payout is now ${input.status.toLowerCase()}.`,actionUrl:'/affiliate/payouts',data:{payoutId:id,status:input.status}},notificationsQueue);return updated; });
  });
};
