CREATE TYPE "AttributionModel" AS ENUM ('FIRST_TOUCH','LAST_TOUCH');
CREATE TYPE "AttributionStatus" AS ENUM ('ACTIVE','CONVERTED','EXPIRED','REJECTED');
CREATE TYPE "CommissionKind" AS ENUM ('ONE_TIME','RECURRING');
CREATE TYPE "CommissionCalculation" AS ENUM ('PERCENTAGE','FIXED');
CREATE TYPE "CommissionStatus" AS ENUM ('PENDING','APPROVED','PAYABLE','PAID','REVERSED','CANCELLED');
CREATE TYPE "AffiliatePayoutStatus" AS ENUM ('PENDING','APPROVED','PROCESSING','PAID','FAILED','CANCELLED');

CREATE TABLE "affiliate_profiles" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"user_id" UUID NOT NULL,"code" VARCHAR(32) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "affiliate_profiles_pkey" PRIMARY KEY("id"));
CREATE TABLE "affiliate_program_configs" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"version" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT false,"attribution_window_days" INTEGER NOT NULL,"attribution_model" "AttributionModel" NOT NULL,"commission_kind" "CommissionKind" NOT NULL,"calculation" "CommissionCalculation" NOT NULL,"percentage_basis_points" INTEGER,"fixed_amount_minor" INTEGER,"recurring_duration_months" INTEGER NOT NULL DEFAULT 1,"payout_threshold_minor" INTEGER NOT NULL,"approval_required" BOOLEAN NOT NULL DEFAULT true,"eligibility_rules" JSONB NOT NULL DEFAULT '{}',"created_by_user_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "affiliate_program_configs_pkey" PRIMARY KEY("id"),CONSTRAINT "affiliate_program_calculation_check" CHECK (("calculation"='PERCENTAGE' AND "percentage_basis_points" BETWEEN 1 AND 10000 AND "fixed_amount_minor" IS NULL) OR ("calculation"='FIXED' AND "fixed_amount_minor">0 AND "percentage_basis_points" IS NULL)),CONSTRAINT "affiliate_program_limits_check" CHECK ("attribution_window_days" BETWEEN 1 AND 365 AND "recurring_duration_months" BETWEEN 1 AND 120 AND "payout_threshold_minor">=0));
CREATE TABLE "affiliate_eligible_products" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"config_id" UUID NOT NULL,"package_version_id" UUID NOT NULL,CONSTRAINT "affiliate_eligible_products_pkey" PRIMARY KEY("id"));
CREATE TABLE "referral_attributions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"affiliate_id" UUID NOT NULL,"config_id" UUID NOT NULL,"token_hash" CHAR(64) NOT NULL,"customer_tenant_id" UUID,"status" "AttributionStatus" NOT NULL DEFAULT 'ACTIVE',"attributed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expires_at" TIMESTAMPTZ(6) NOT NULL,"converted_at" TIMESTAMPTZ(6),CONSTRAINT "referral_attributions_pkey" PRIMARY KEY("id"));
CREATE TABLE "affiliate_conversions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"attribution_id" UUID NOT NULL,"affiliate_id" UUID NOT NULL,"config_id" UUID NOT NULL,"customer_tenant_id" UUID NOT NULL,"payment_transaction_id" UUID NOT NULL,"package_version_id" UUID NOT NULL,"recurring_period" INTEGER NOT NULL,"converted_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "affiliate_conversions_pkey" PRIMARY KEY("id"),CONSTRAINT "affiliate_conversion_period_check" CHECK ("recurring_period">0));
CREATE TABLE "affiliate_payouts" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"affiliate_id" UUID NOT NULL,"affiliate_tenant_id" UUID NOT NULL,"idempotency_key" UUID NOT NULL,"amount_minor" INTEGER NOT NULL,"currency" CHAR(3) NOT NULL,"status" "AffiliatePayoutStatus" NOT NULL DEFAULT 'PENDING',"provider_reference" VARCHAR(255),"failure_code" VARCHAR(120),"changed_by_user_id" UUID,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,"paid_at" TIMESTAMPTZ(6),CONSTRAINT "affiliate_payouts_pkey" PRIMARY KEY("id"),CONSTRAINT "affiliate_payout_amount_check" CHECK ("amount_minor">=0));
CREATE TABLE "affiliate_commissions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"conversion_id" UUID NOT NULL,"affiliate_id" UUID NOT NULL,"payout_id" UUID,"amount_minor" INTEGER NOT NULL,"currency" CHAR(3) NOT NULL,"status" "CommissionStatus" NOT NULL DEFAULT 'PENDING',"rule_snapshot" JSONB NOT NULL,"approved_at" TIMESTAMPTZ(6),"reversed_at" TIMESTAMPTZ(6),"reversal_reason" VARCHAR(500),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "affiliate_commissions_pkey" PRIMARY KEY("id"),CONSTRAINT "affiliate_commission_amount_check" CHECK ("amount_minor">0));

CREATE UNIQUE INDEX "affiliate_profiles_tenant_id_key" ON "affiliate_profiles"("tenant_id"); CREATE UNIQUE INDEX "affiliate_profiles_user_id_key" ON "affiliate_profiles"("user_id"); CREATE UNIQUE INDEX "affiliate_profiles_code_key" ON "affiliate_profiles"("code");
CREATE UNIQUE INDEX "affiliate_program_configs_version_key" ON "affiliate_program_configs"("version"); CREATE INDEX "affiliate_program_configs_active_created_at_idx" ON "affiliate_program_configs"("active","created_at");
CREATE UNIQUE INDEX "affiliate_eligible_products_config_id_package_version_id_key" ON "affiliate_eligible_products"("config_id","package_version_id");
CREATE UNIQUE INDEX "referral_attributions_token_hash_key" ON "referral_attributions"("token_hash"); CREATE UNIQUE INDEX "referral_attributions_customer_tenant_id_key" ON "referral_attributions"("customer_tenant_id"); CREATE INDEX "referral_attributions_affiliate_id_status_attributed_at_idx" ON "referral_attributions"("affiliate_id","status","attributed_at");
CREATE UNIQUE INDEX "affiliate_conversions_payment_transaction_id_key" ON "affiliate_conversions"("payment_transaction_id"); CREATE UNIQUE INDEX "affiliate_conversions_attribution_id_recurring_period_key" ON "affiliate_conversions"("attribution_id","recurring_period");
CREATE UNIQUE INDEX "affiliate_commissions_conversion_id_key" ON "affiliate_commissions"("conversion_id"); CREATE INDEX "affiliate_commissions_affiliate_id_status_created_at_idx" ON "affiliate_commissions"("affiliate_id","status","created_at");
CREATE UNIQUE INDEX "affiliate_payouts_idempotency_key_key" ON "affiliate_payouts"("idempotency_key"); CREATE UNIQUE INDEX "affiliate_payouts_provider_reference_key" ON "affiliate_payouts"("provider_reference"); CREATE INDEX "affiliate_payouts_affiliate_id_status_created_at_idx" ON "affiliate_payouts"("affiliate_id","status","created_at");

ALTER TABLE "affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_tenant_id_fkey" FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_user_id_fkey" FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "affiliate_program_configs" ADD CONSTRAINT "affiliate_program_configs_created_by_user_id_fkey" FOREIGN KEY("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "affiliate_eligible_products" ADD CONSTRAINT "affiliate_eligible_products_config_id_fkey" FOREIGN KEY("config_id") REFERENCES "affiliate_program_configs"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "affiliate_eligible_products" ADD CONSTRAINT "affiliate_eligible_products_package_version_id_fkey" FOREIGN KEY("package_version_id") REFERENCES "package_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "referral_attributions" ADD CONSTRAINT "referral_attributions_affiliate_id_fkey" FOREIGN KEY("affiliate_id") REFERENCES "affiliate_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "referral_attributions" ADD CONSTRAINT "referral_attributions_config_id_fkey" FOREIGN KEY("config_id") REFERENCES "affiliate_program_configs"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "referral_attributions" ADD CONSTRAINT "referral_attributions_customer_tenant_id_fkey" FOREIGN KEY("customer_tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_attribution_id_fkey" FOREIGN KEY("attribution_id") REFERENCES "referral_attributions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_affiliate_id_fkey" FOREIGN KEY("affiliate_id") REFERENCES "affiliate_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_config_id_fkey" FOREIGN KEY("config_id") REFERENCES "affiliate_program_configs"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_customer_tenant_id_fkey" FOREIGN KEY("customer_tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_payment_transaction_id_fkey" FOREIGN KEY("payment_transaction_id") REFERENCES "payment_transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_conversions" ADD CONSTRAINT "affiliate_conversions_package_version_id_fkey" FOREIGN KEY("package_version_id") REFERENCES "package_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "affiliate_payouts" ADD CONSTRAINT "affiliate_payouts_affiliate_id_fkey" FOREIGN KEY("affiliate_id") REFERENCES "affiliate_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_payouts" ADD CONSTRAINT "affiliate_payouts_affiliate_tenant_id_fkey" FOREIGN KEY("affiliate_tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_payouts" ADD CONSTRAINT "affiliate_payouts_changed_by_user_id_fkey" FOREIGN KEY("changed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "affiliate_commissions" ADD CONSTRAINT "affiliate_commissions_conversion_id_fkey" FOREIGN KEY("conversion_id") REFERENCES "affiliate_conversions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_commissions" ADD CONSTRAINT "affiliate_commissions_affiliate_id_fkey" FOREIGN KEY("affiliate_id") REFERENCES "affiliate_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "affiliate_commissions" ADD CONSTRAINT "affiliate_commissions_payout_id_fkey" FOREIGN KEY("payout_id") REFERENCES "affiliate_payouts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

INSERT INTO "permissions"("id","key","description","created_at") VALUES ('20000000-0000-4000-8000-000000000061','affiliate.financial.read','Read own affiliate financial ledger',CURRENT_TIMESTAMP),('20000000-0000-4000-8000-000000000062','affiliate.manage','Configure affiliate programs, commissions, and payouts',CURRENT_TIMESTAMP) ON CONFLICT("key") DO NOTHING;
INSERT INTO "role_permissions"("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE (r."name"='Affiliate' AND p."key"='affiliate.financial.read') OR (r."name"='Owner' AND p."key"='affiliate.manage') ON CONFLICT DO NOTHING;
