import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { database } from '@zerochack/database';
import { encryptSecret, hashPassword, totp } from '@zerochack/auth';
import type { AiProviderAdapter } from '@zerochack/ai-gateway';
import { loadEnvironment } from '@zerochack/config';
import type { EmailMessage, EmailProvider } from '@zerochack/email';
import { buildApp } from './app.js';
import { processScan } from '../../worker/src/scan-worker.js';
import type { Job } from 'bullmq';
import { TargetSecurityError } from '@zerochack/scanner';
import { createHmac } from 'node:crypto';
import { PaymentProviderError, verifyHmacSha256, type PaymentProvider } from '@zerochack/payments';
import { processBackupCreate, processRestore, processRetention } from '../../worker/src/backup-worker.js';
import { processMonitoringCheck } from '../../worker/src/monitoring-worker.js';
import type { BackupProvider } from '@zerochack/storage';
import { createCommissionForPayment, reverseCommissionForPayment } from './modules/affiliate/service.js';
import { publishCommunicationEvent } from './modules/communications/service.js';
import { processCommunicationEvent } from '../../worker/src/notification-worker.js';
import { processEmailDelivery } from '../../worker/src/email-worker.js';
import { processReport } from '../../worker/src/report-worker.js';

class CapturingEmail implements EmailProvider {
  readonly messages: EmailMessage[] = [];
  async send(message: EmailMessage) { this.messages.push(message); return { providerMessageId: String(this.messages.length) }; }
  takeToken(): string { const message = this.messages.at(-1); const match = message?.text.match(/token=([^\s]+)/u); if (!match?.[1]) throw new Error('Token missing'); return decodeURIComponent(match[1]); }
}

const aiKey = Buffer.alloc(32, 8).toString('base64');
const paymentKey = Buffer.alloc(32, 7).toString('base64');
const environment = loadEnvironment({ NODE_ENV: 'test', DATABASE_URL: process.env.DATABASE_URL, REDIS_URL: process.env.REDIS_URL ?? 'redis://127.0.0.1:6380', SESSION_SECRET: 'integration-secret-at-least-thirty-two-chars', MFA_ENCRYPTION_KEY: Buffer.alloc(32, 9).toString('base64'), AI_CREDENTIAL_ENCRYPTION_KEY: aiKey, PAYMENT_CREDENTIAL_ENCRYPTION_KEY: paymentKey, CORS_ORIGINS: 'http://127.0.0.1:3100', LOG_LEVEL: 'silent' });
const email = new CapturingEmail(); let app: Awaited<ReturnType<typeof buildApp>>;
const aiPrompts: string[] = [];
const aiToolNames: string[][] = [];
const aiAdapter: AiProviderAdapter = { key: 'openai-responses', async complete(input) { aiPrompts.push(input.prompt); aiToolNames.push(input.tools?.map((tool) => tool.name) ?? []); return { text: 'What we found\nA response header is absent.\nWhy it matters\nDefense is reduced.\nRisk\nUse the authoritative severity.\nWhat could happen\nA browser may have fewer protections.\nRecommended action\nApply the recorded recommendation.', inputTokens: 40, outputTokens: 30, providerRequestId: 'test-response' }; } };
const paymentAdapter: PaymentProvider = {
  adapterKey: 'integration-payments',
  async createCheckout(_input, context) { return { checkoutReference: `checkout-${context.idempotencyKey}`, checkoutUrl: `https://pay.example.test/${context.idempotencyKey}` }; },
  async verifyPayment(reference) { return { verified: true, status: 'SUCCEEDED', paymentReference: `payment-${reference}`, subscriptionReference: `subscription-${reference}`, invoiceReference: `invoice-${reference}`, currentPeriodEnd: new Date(Date.now() + 30 * 86_400_000) }; },
  async createSubscription(_input, context) { return { subscriptionReference: `trial-${context.idempotencyKey}`, status: 'TRIALING', trialEndsAt: new Date(Date.now() + 7 * 86_400_000) }; },
  async createInvoice(_input, context) { return { invoiceReference: `invoice-${context.idempotencyKey}`, status: 'OPEN' }; },
  async refund(_reference, _amount, _reason, context) { return { refundReference: `refund-${context.idempotencyKey}`, status: 'SUCCEEDED' }; },
  async cancelSubscription() { return { cancelled: true, effectiveAt: new Date() }; },
  async verifyWebhook(rawPayload, headers, secret) { const signature = Array.isArray(headers['x-payment-signature']) ? headers['x-payment-signature'][0] : headers['x-payment-signature']; if (!signature || !verifyHmacSha256(rawPayload, signature, secret)) throw new PaymentProviderError('INVALID_SIGNATURE', 'Invalid signature'); const value = JSON.parse(rawPayload) as { id: string; occurredAt: string; checkoutReference?: string; paymentReference?: string }; return { eventId: value.id, type: 'payment.succeeded', occurredAt: new Date(value.occurredAt), status: 'SUCCEEDED', ...(value.checkoutReference ? { checkoutReference: value.checkoutReference } : {}), ...(value.paymentReference ? { paymentReference: value.paymentReference } : {}) }; },
  async health() { return 'HEALTHY'; }
};
const password = 'Secure-Password9!';
const cookieFrom = (header: string | string[] | undefined): string => { const value = Array.isArray(header) ? header[0] : header; if (!value) throw new Error('Cookie missing'); return value.split(';')[0]!; };
const register = async (role: 'Customer' | 'Agency' | 'Affiliate', address: string) => { const response = await app.inject({ method: 'POST', url: '/v1/auth/register', payload: { email: address, password, displayName: 'Test User', organizationName: `${role} Org`, role } }); expect(response.statusCode).toBe(202); return email.takeToken(); };
const login = (portal: string, address: string, value = password) => app.inject({ method: 'POST', url: `/v1/auth/${portal}/login`, payload: { email: address, password: value } });

beforeAll(async () => {
  const databaseName = new URL(environment.DATABASE_URL).pathname.replace(/^\//u, '');
  if (!databaseName.endsWith('_test')) throw new Error(`Refusing destructive integration setup against non-test database "${databaseName}". Point DATABASE_URL at an isolated *_test database.`);
  app = await buildApp(environment, { email, aiAdapters: [aiAdapter], paymentProviders: [paymentAdapter] });
});
beforeEach(async () => {
  email.messages.length = 0;
  aiPrompts.length = 0;
  aiToolNames.length = 0;
  await database.$transaction([
    database.emailDelivery.deleteMany(), database.notification.deleteMany(), database.communicationEvent.deleteMany(), database.notificationPreference.deleteMany(), database.platformIntegration.deleteMany(), database.systemSetting.deleteMany(), database.restoreOperation.deleteMany(), database.restoreAuthorization.deleteMany(), database.securityAlert.deleteMany(), database.securityEventEvidence.deleteMany(), database.securityEvent.deleteMany(), database.monitoringCheck.deleteMany(), database.monitoringPolicy.deleteMany(), database.backupPolicy.deleteMany(), database.developerModeSetting.deleteMany(), database.affiliateCommission.deleteMany(), database.affiliatePayout.deleteMany(), database.affiliateConversion.deleteMany(), database.referralAttribution.deleteMany(), database.paymentRefund.deleteMany(), database.paymentWebhookEvent.deleteMany(), database.quoteLineItem.deleteMany(), database.quote.deleteMany(), database.paymentTransaction.deleteMany(), database.invoice.deleteMany(), database.subscription.deleteMany(), database.paymentProviderConfig.deleteMany(), database.agencyPackageEntitlement.deleteMany(), database.agencyCommercePolicy.deleteMany(), database.affiliateEligibleProduct.deleteMany(), database.affiliateProgramConfig.deleteMany(), database.packageVersion.deleteMany(), database.commercialPackage.deleteMany(), database.warrantyClaim.deleteMany(), database.remediationRun.deleteMany(), database.remediationSession.deleteMany(), database.remediationAuthorization.deleteMany(), database.warrantyPolicy.deleteMany(), database.remediationPlaybook.deleteMany(), database.aiUsage.deleteMany(), database.aiTenantPolicy.deleteMany(), database.aiCredential.deleteMany(), database.aiModel.deleteMany(), database.aiProvider.deleteMany(), database.chatMessage.deleteMany(), database.report.deleteMany(), database.backup.deleteMany(), database.ticket.deleteMany(), database.findingEvidence.deleteMany(), database.securityFinding.deleteMany(), database.scan.deleteMany(), database.websiteVerification.deleteMany(), database.website.deleteMany(), database.notification.deleteMany(), database.auditLog.deleteMany(), database.session.deleteMany(), database.authToken.deleteMany(), database.mfaRecoveryCode.deleteMany(), database.agencyClientRelationship.deleteMany(), database.affiliateProfile.deleteMany(), database.userRole.deleteMany(), database.tenantMembership.deleteMany(), database.user.deleteMany(), database.tenant.deleteMany()
  ]);
});
afterAll(async () => { await app.close(); await database.$disconnect(); });

describe('authentication, RBAC, and tenant isolation', () => {
  it('registers, verifies once, enforces portal role, creates and revokes a session', async () => {
    const token = await register('Customer', 'customer@example.test');
    expect((await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } })).json()).toEqual({ status: 'APPROVED' });
    expect((await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } })).statusCode).toBe(400);
    expect((await login('agency', 'customer@example.test')).statusCode).toBe(401);
    const response = await login('customer', 'customer@example.test'); expect(response.statusCode).toBe(200); const cookie = cookieFrom(response.headers['set-cookie']); const identity = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie } })).json();
    expect(identity.roles).toEqual(['Customer']); expect(identity.permissions).not.toContain('users.suspend');
    const crossTenant = await app.inject({ method: 'GET', url: `/v1/tenants/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/access-check?tenantId=${identity.tenantId}`, headers: { cookie, 'x-tenant-id': 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' } }); expect(crossTenant.statusCode).toBe(404); expect(crossTenant.headers['cache-control']).toBe('private, no-store');
    expect((await app.inject({ method: 'GET', url: '/v1/tenants/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb/access-check', headers: { cookie, connection: 'Upgrade', upgrade: 'websocket' } })).statusCode).toBe(404);
    const sessions = (await app.inject({ method: 'GET', url: '/v1/auth/sessions', headers: { cookie } })).json().sessions; expect(sessions).toHaveLength(1);
    expect((await app.inject({ method: 'DELETE', url: `/v1/auth/sessions/${sessions[0].id}`, headers: { cookie } })).statusCode).toBe(204);
    expect((await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie } })).statusCode).toBe(401);
  });

  it('places approval roles in pending state and blocks suspended credentials', async () => {
    const token = await register('Agency', 'agency@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } });
    expect((await login('agency', 'agency@example.test')).json().error.code).toBe('APPROVAL_PENDING');
    await database.user.update({ where: { email: 'agency@example.test' }, data: { status: 'SUSPENDED' } });
    expect((await login('agency', 'agency@example.test')).json().error.code).toBe('ACCOUNT_SUSPENDED');
  });

  it('requires Owner MFA, supports recovery once, and prevents privilege escalation', async () => {
    const role = await database.role.findFirstOrThrow({ where: { name: 'Owner', tenantId: null } }); const tenant = await database.tenant.create({ data: { name: 'Platform', slug: `platform-${crypto.randomUUID()}` } });
    const owner = await database.user.create({ data: { email: 'owner@example.test', passwordHash: await hashPassword(password), displayName: 'Owner', status: 'APPROVED', emailVerifiedAt: new Date() } });
    await database.tenantMembership.create({ data: { tenantId: tenant.id, userId: owner.id, status: 'ACTIVE' } }); await database.userRole.create({ data: { tenantId: tenant.id, userId: owner.id, roleId: role.id } });
    const first = await login('owner', owner.email); expect(first.statusCode).toBe(202); expect(first.headers['set-cookie']).toBeUndefined(); expect(first.json()).toMatchObject({ enrollmentRequired: true, enrollmentPending: false }); const challenge = first.json().challengeToken as string;
    const enrollment = (await app.inject({ method: 'POST', url: '/v1/auth/mfa/enroll', payload: { token: challenge } })).json();
    const resumedLogin = await login('owner', owner.email); expect(resumedLogin.json()).toMatchObject({ enrollmentRequired: false, enrollmentPending: true });
    const resumedEnrollment = (await app.inject({ method: 'POST', url: '/v1/auth/mfa/enroll', payload: { token: resumedLogin.json().challengeToken } })).json(); expect(resumedEnrollment.secret).toBe(enrollment.secret);
    const confirmed = await app.inject({ method: 'POST', url: '/v1/auth/mfa/confirm', payload: { challengeToken: challenge, code: totp(enrollment.secret) } }); expect(confirmed.statusCode).toBe(200); const recovery = confirmed.json().recoveryCodes[0] as string;
    const ownerCookie = cookieFrom(confirmed.headers['set-cookie']); expect((await app.inject({ method: 'GET', url: '/v1/owner/approvals', headers: { cookie: ownerCookie } })).statusCode).toBe(200);
    const agencyToken = await register('Agency', 'approval@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: agencyToken } }); const agency = await database.user.findUniqueOrThrow({ where: { email: 'approval@example.test' } });
    expect((await app.inject({ method: 'PATCH', url: `/v1/owner/users/${agency.id}/status`, headers: { cookie: ownerCookie }, payload: { status: 'APPROVED' } })).statusCode).toBe(200); const approvedLogin = await login('agency', agency.email); const agencyCookie = cookieFrom(approvedLogin.headers['set-cookie']);
    expect((await app.inject({ method: 'PATCH', url: `/v1/owner/users/${agency.id}/status`, headers: { cookie: ownerCookie }, payload: { status: 'SUSPENDED', reason: 'integration test' } })).statusCode).toBe(200); expect((await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: agencyCookie } })).statusCode).toBe(401);
    const customerToken = await register('Customer', 'plain@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerToken } }); const customerLogin = await login('customer', 'plain@example.test'); const customerCookie = cookieFrom(customerLogin.headers['set-cookie']);
    expect((await app.inject({ method: 'GET', url: '/v1/owner/approvals', headers: { cookie: customerCookie } })).statusCode).toBe(403);
    const secondChallenge = (await login('owner', owner.email)).json().challengeToken; expect((await app.inject({ method: 'POST', url: '/v1/auth/mfa/verify', payload: { challengeToken: secondChallenge, code: recovery } })).statusCode).toBe(200);
    const thirdChallenge = (await login('owner', owner.email)).json().challengeToken; expect((await app.inject({ method: 'POST', url: '/v1/auth/mfa/verify', payload: { challengeToken: thirdChallenge, code: recovery } })).statusCode).toBe(401);
  });

  it('expires and revokes sessions and consumes password reset tokens once', async () => {
    const token = await register('Customer', 'reset@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } }); const signedIn = await login('customer', 'reset@example.test'); const cookie = cookieFrom(signedIn.headers['set-cookie']);
    await app.inject({ method: 'POST', url: '/v1/auth/forgot-password', payload: { email: 'reset@example.test' } }); const resetToken = email.takeToken();
    expect((await app.inject({ method: 'POST', url: '/v1/auth/reset-password', payload: { token: resetToken, password: 'New-Secure-Password8!' } })).statusCode).toBe(200);
    expect((await app.inject({ method: 'POST', url: '/v1/auth/reset-password', payload: { token: resetToken, password } })).statusCode).toBe(400); expect((await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie } })).statusCode).toBe(401);
    const refreshed = await login('customer', 'reset@example.test', 'New-Secure-Password8!'); const newCookie = cookieFrom(refreshed.headers['set-cookie']); const session = await database.session.findFirstOrThrow({ where: { userId: refreshed.json().user.id, revokedAt: null } }); await database.session.update({ where: { id: session.id }, data: { expiresAt: new Date(Date.now() - 1_000) } });
    expect((await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: newCookie } })).statusCode).toBe(401);
  });

  it('locks an account after repeated failed passwords and audits failures', async () => {
    const token = await register('Customer', 'lockout@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } });
    for (let attempt = 0; attempt < 5; attempt += 1) expect((await login('customer', 'lockout@example.test', 'Definitely-Wrong9!')).statusCode).toBe(401);
    const locked = await login('customer', 'lockout@example.test'); expect(locked.statusCode).toBe(429); expect(locked.json().error.code).toBe('ACCOUNT_LOCKED');
    expect(await database.auditLog.count({ where: { action: 'auth.login_failed' } })).toBe(5);
  });

  it('supports the customer website and chat flow while denying cross-tenant IDs', async () => {
    const tokenA = await register('Customer', 'tenant-a@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: tokenA } });
    const cookieA = cookieFrom((await login('customer', 'tenant-a@example.test')).headers['set-cookie']);
    for (const url of ['http://127.0.0.1', 'http://169.254.169.254/latest/meta-data', 'http://service.internal', 'https://example.com:8443']) expect((await app.inject({ method: 'POST', url: '/v1/websites', headers: { cookie: cookieA }, payload: { name: 'Blocked target', url } })).statusCode).toBe(400);
    const created = await app.inject({ method: 'POST', url: '/v1/websites', headers: { cookie: cookieA }, payload: { name: 'Tenant A Site', url: 'https://example.com' } });
    expect(created.statusCode).toBe(201); const websiteId = created.json().id as string;
    const challengeResponse = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/verification`, headers: { cookie: cookieA }, payload: { method: 'DNS' } });
    expect(challengeResponse.statusCode).toBe(201); const storedChallenge = await database.websiteVerification.findFirstOrThrow({ where: { websiteId } }); expect(storedChallenge.tokenHash).not.toBe(challengeResponse.json().recordValue);
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/chat`, headers: { cookie: cookieA }, payload: { content: 'Please review this website.' } })).statusCode).toBe(201);
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/scans`, headers: { cookie: cookieA } })).statusCode).toBe(409);
    await database.website.update({ where: { id: websiteId }, data: { connectionStatus: 'VERIFIED', connectedAt: new Date() } });
    await database.websiteAccessCredential.create({ data: { tenantId: created.json().tenantId, websiteId, host: 'example.com', port: 22, username: 'scanner', authMethod: 'SSH_KEY', encryptedSecret: encryptSecret('integration-test-key', environment.INTEGRATION_CREDENTIAL_ENCRYPTION_KEY), status: 'READY_FOR_SECURE_SESSION', lastCheckedAt: new Date() } });
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/scans`, headers: { cookie: cookieA } })).statusCode).toBe(202);
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/scans`, headers: { cookie: cookieA } })).json().error.code).toBe('SCAN_ALREADY_ACTIVE');
    const queuedScan = await database.scan.findFirstOrThrow({ where: { tenantId: created.json().tenantId, websiteId, status: 'QUEUED' } });
    await processScan({ data: { scanId: queuedScan.id, websiteId, tenantId: created.json().tenantId }, attemptsMade: 0, opts: { attempts: 3 } } as Job<{ scanId: string; websiteId: string; tenantId: string }>, undefined, async (_target, runnerOptions) => {
      await runnerOptions?.onEngineComplete?.(1, 1);
      return { targetUrl: 'https://example.com/', response: { url: 'https://example.com/', status: 200, resolvedAddress: '93.184.216.34', redirects: [] }, engineCount: 1, findings: [{ fingerprint: 'a'.repeat(64), title: 'Test header finding', description: 'A normalized test-engine result.', severity: 'MEDIUM', confidence: 0.99, affectedResource: 'https://example.com/', recommendation: 'Set the tested response header.', cwe: 'CWE-693', owaspCategory: 'A05:2021', remediationSupported: false, engine: 'integration-engine', engineVersion: '1.0.0', observedAt: new Date(), evidence: { summary: 'The expected header was absent.', metadata: { header: 'x-test', present: false } } }] };
    });
    const workspace = (await app.inject({ method: 'GET', url: `/v1/websites/${websiteId}`, headers: { cookie: cookieA } })).json();
    expect(workspace.scans[0]).toMatchObject({ status: 'SUCCEEDED', progress: 100 }); expect(workspace.findings[0].evidence).toHaveLength(1);
    const provider = await database.aiProvider.create({ data: { name: 'Integration provider', adapterKey: 'openai-responses', enabled: true, healthStatus: 'HEALTHY', credentials: { create: { label: 'primary', encryptedSecret: encryptSecret('integration-provider-secret', aiKey), healthStatus: 'HEALTHY' } }, models: { create: { name: 'integration-model', providerModel: 'test-model', inputCostMicrosPerM: 1000, outputCostMicrosPerM: 2000 } } } });
    await database.aiTenantPolicy.create({ data: { tenantId: created.json().tenantId, enabled: true, requestsPerMinute: 20, requestsPerUserMinute: 10, maxConcurrent: 2, dailyCostLimitMicros: 10000 } });
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/chat/ai`, headers: { cookie: cookieA }, payload: { content: 'password=must-not-leak', idempotencyKey: crypto.randomUUID(), providerId: provider.id } })).json().error.code).toBe('CHAT_SECRET_BLOCKED');
    const idempotencyKey = crypto.randomUUID(); const aiResponse = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/chat/ai`, headers: { cookie: cookieA }, payload: { content: 'Explain the latest finding.', findingId: workspace.findings[0].id, idempotencyKey, providerId: provider.id } });
    expect(aiResponse.statusCode).toBe(201); expect(aiResponse.json()).toMatchObject({ type: 'AI' }); expect(aiPrompts[0]).toContain('authoritativeSeverity'); expect(aiToolNames[0]).toEqual(['plan_security_assessment', 'get_latest_assessment_evidence', 'check_ssh_access', 'run_read_only_security_assessment', 'inspect_security_finding', 'request_live_access_specialist']);
    const duplicateAi = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/chat/ai`, headers: { cookie: cookieA }, payload: { content: 'Explain the latest finding.', findingId: workspace.findings[0].id, idempotencyKey, providerId: provider.id } });
    expect(duplicateAi.statusCode).toBe(200); expect(duplicateAi.json().id).toBe(aiResponse.json().id); expect(aiPrompts).toHaveLength(1);
    const ticketResponse = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/tickets`, headers: { cookie: cookieA }, payload: { title: 'Scoped remediation', findingId: workspace.findings[0].id } }); const ticketId = ticketResponse.json().id as string;
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/tickets/${ticketId}/queue`, headers: { cookie: cookieA } })).statusCode).toBe(200);
    const specialistRole = await database.role.findFirstOrThrow({ where: { name: 'Cybersecurity Specialist', tenantId: null } });
    const makeSpecialist = async (emailAddress: string) => { const tenant = await database.tenant.create({ data: { name: emailAddress, slug: `specialist-${crypto.randomUUID()}` } }); const user = await database.user.create({ data: { email: emailAddress, passwordHash: await hashPassword(password), status: 'APPROVED', emailVerifiedAt: new Date() } }); await database.tenantMembership.create({ data: { tenantId: tenant.id, userId: user.id, status: 'ACTIVE' } }); await database.userRole.create({ data: { tenantId: tenant.id, userId: user.id, roleId: specialistRole.id } }); return cookieFrom((await login('specialist', emailAddress)).headers['set-cookie']); };
    const specialistCookieA = await makeSpecialist('specialist-a@example.test'); const specialistCookieB = await makeSpecialist('specialist-b@example.test');
    expect((await app.inject({ method: 'POST', url: `/v1/specialist/jobs/${ticketId}/accept`, headers: { cookie: specialistCookieA } })).statusCode).toBe(200);
    expect((await app.inject({ method: 'POST', url: `/v1/specialist/jobs/${ticketId}/accept`, headers: { cookie: specialistCookieB } })).json().error.code).toBe('TICKET_ACCEPTANCE_CONFLICT');
    expect((await app.inject({ method: 'POST', url: `/v1/specialist/tickets/${ticketId}/backup`, headers: { cookie: specialistCookieA } })).statusCode).toBe(404);
    expect((await app.inject({ method: 'POST', url: `/v1/specialist/tickets/${ticketId}/request-authorization`, headers: { cookie: specialistCookieA } })).statusCode).toBe(200);
    const authorization = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/tickets/${ticketId}/authorization`, headers: { cookie: cookieA }, payload: { scope: ['finding.remediate'], expiresInMinutes: 60 } }); expect(authorization.statusCode).toBe(201);
    await database.remediationAuthorization.update({ where: { id: authorization.json().id }, data: { expiresAt: new Date(Date.now() - 1000) } });
    expect((await app.inject({ method: 'POST', url: `/v1/specialist/tickets/${ticketId}/backup`, headers: { cookie: specialistCookieA } })).json().error.code).toBe('AUTHORIZATION_EXPIRED');
    const retryScan = await database.scan.create({ data: { tenantId: created.json().tenantId, websiteId } });
    const failedRunner = async (): Promise<never> => { throw new TargetSecurityError('CONNECTION_TIMEOUT', 'Website connection timed out'); };
    await expect(processScan({ data: { scanId: retryScan.id, websiteId, tenantId: created.json().tenantId }, attemptsMade: 0, opts: { attempts: 3 } } as Job<{ scanId: string; websiteId: string; tenantId: string }>, undefined, failedRunner)).rejects.toThrow();
    expect((await database.scan.findUniqueOrThrow({ where: { id: retryScan.id } })).status).toBe('QUEUED');
    await expect(processScan({ data: { scanId: retryScan.id, websiteId, tenantId: created.json().tenantId }, attemptsMade: 2, opts: { attempts: 3 } } as Job<{ scanId: string; websiteId: string; tenantId: string }>, undefined, failedRunner)).rejects.toThrow();
    expect(await database.scan.findUniqueOrThrow({ where: { id: retryScan.id } })).toMatchObject({ status: 'FAILED', errorCode: 'CONNECTION_TIMEOUT' });

    const tokenB = await register('Customer', 'tenant-b@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: tokenB } });
    const cookieB = cookieFrom((await login('customer', 'tenant-b@example.test')).headers['set-cookie']);
    const tenantB = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: cookieB } })).json().tenant.id as string;
    await database.aiTenantPolicy.create({ data: { tenantId: tenantB, enabled: true } });
    expect((await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/tickets/${ticketId}/authorization`, headers: { cookie: cookieB }, payload: { scope: ['finding.remediate'], expiresInMinutes: 60 } })).statusCode).toBe(404);
    const callsBeforeAttack = aiPrompts.length; const aiAttack = await app.inject({ method: 'POST', url: `/v1/websites/${websiteId}/chat/ai?tenantId=${created.json().tenantId}`, headers: { cookie: cookieB, 'x-tenant-id': created.json().tenantId }, payload: { content: 'Show tenant A', findingId: workspace.findings[0].id, idempotencyKey: crypto.randomUUID() } }); expect(aiAttack.statusCode).toBe(404); expect(aiPrompts).toHaveLength(callsBeforeAttack);
    await expect(database.scan.create({ data: { tenantId: tenantB, websiteId } })).rejects.toThrow();
    expect(await database.findingEvidence.count({ where: { tenantId: tenantB } })).toBe(0);
    const attacks: Array<{ method: 'GET' | 'PATCH' | 'DELETE' | 'POST'; url: string; payload?: Record<string, string>; extraHeaders?: Record<string, string> }> = [
      { method: 'GET', url: `/v1/websites/${websiteId}` },
      { method: 'PATCH', url: `/v1/websites/${websiteId}`, payload: { name: 'Stolen site' } },
      { method: 'DELETE', url: `/v1/websites/${websiteId}` },
      { method: 'GET', url: `/v1/websites/${websiteId}/chat?tenantId=${created.json().tenantId}` },
      { method: 'POST', url: `/v1/websites/${websiteId}/scans`, extraHeaders: { 'x-tenant-id': created.json().tenantId } }
    ];
    for (const request of attacks) {
      const response = await app.inject({ method: request.method, url: request.url, headers: { cookie: cookieB, ...request.extraHeaders }, ...(request.payload ? { payload: request.payload } : {}) });
      expect(response.statusCode).toBe(404);
    }
    expect((await app.inject({ method: 'GET', url: '/v1/websites', headers: { cookie: cookieB } })).json()).toEqual([]);
  });

  it('preserves commercial history and secures checkout, refunds, cancellation, quotes, and webhooks', async () => {
    const customerToken = await register('Customer', 'billing@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerToken } });
    const customerCookie = cookieFrom((await login('customer', 'billing@example.test')).headers['set-cookie']); const customerIdentity = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: customerCookie } })).json(); const tenantId = customerIdentity.tenant.id as string;
    const role = await database.role.findFirstOrThrow({ where: { name: 'Owner', tenantId: null } }); const ownerTenant = await database.tenant.create({ data: { name: 'Commercial owner', slug: `commercial-owner-${crypto.randomUUID()}` } }); const ownerUser = await database.user.create({ data: { email: 'commercial-owner@example.test', passwordHash: await hashPassword(password), status: 'APPROVED', emailVerifiedAt: new Date() } }); await database.tenantMembership.create({ data: { tenantId: ownerTenant.id, userId: ownerUser.id, status: 'ACTIVE' } }); await database.userRole.create({ data: { tenantId: ownerTenant.id, userId: ownerUser.id, roleId: role.id } });
    const challenge = (await login('owner', ownerUser.email)).json().challengeToken as string; const enrollment = (await app.inject({ method: 'POST', url: '/v1/auth/mfa/enroll', payload: { token: challenge } })).json(); const ownerLogin = await app.inject({ method: 'POST', url: '/v1/auth/mfa/confirm', payload: { challengeToken: challenge, code: totp(enrollment.secret) } }); const ownerCookie = cookieFrom(ownerLogin.headers['set-cookie']);
    const provider = await app.inject({ method: 'POST', url: '/v1/owner/commercial/providers', headers: { cookie: ownerCookie }, payload: { name: 'Integration payments', adapterKey: 'integration-payments', credentials: 'webhook-secret', enabled: true } }); expect(provider.statusCode).toBe(201); const providerId = provider.json().id as string;
    const terms = { name: 'Protection', description: 'Versioned protection terms', priceMinor: 2500, currency: 'usd', billingInterval: 'MONTHLY', trialDays: 7, websiteLimit: 2, scanLimit: 10, monitoringIntervalMinutes: 15, backupFrequencyHours: 24, backupRetentionDays: 30, warrantyDays: 14, aiRequestLimit: 100, aiCostLimitMicros: 500000, supportLevel: 'standard', featureEntitlements: { reports: true } };
    const plan = await app.inject({ method: 'POST', url: '/v1/owner/commercial/packages', headers: { cookie: ownerCookie }, payload: { key: 'protection', ...terms } }); expect(plan.statusCode).toBe(201); const versionId = plan.json().id as string; const packageId = plan.json().packageId as string;
    const idempotencyKey = crypto.randomUUID(); const checkout = await app.inject({ method: 'POST', url: '/v1/commercial/checkouts', headers: { cookie: customerCookie }, payload: { packageVersionId: versionId, providerId, idempotencyKey } }); expect(checkout.statusCode).toBe(201); expect(checkout.json().status).toBe('PENDING');
    const duplicateCheckout = await app.inject({ method: 'POST', url: '/v1/commercial/checkouts', headers: { cookie: customerCookie }, payload: { packageVersionId: versionId, providerId, idempotencyKey } }); expect(duplicateCheckout.json()).toMatchObject({ id: checkout.json().id, duplicate: true }); expect(await database.paymentTransaction.count()).toBe(1);
    const verified = await app.inject({ method: 'POST', url: `/v1/commercial/payments/${checkout.json().id}/verify`, headers: { cookie: customerCookie } }); expect(verified.statusCode).toBe(200); expect(verified.json().payment.status).toBe('SUCCEEDED');
    await app.inject({ method: 'POST', url: `/v1/commercial/payments/${checkout.json().id}/verify`, headers: { cookie: customerCookie } }); expect(await database.invoice.count({ where: { tenantId } })).toBe(1); expect(await database.subscription.count({ where: { tenantId } })).toBe(1);
    const newer = await app.inject({ method: 'POST', url: `/v1/owner/commercial/packages/${packageId}/versions`, headers: { cookie: ownerCookie }, payload: { ...terms, priceMinor: 4500, name: 'Protection Plus' } }); expect(newer.statusCode).toBe(201);
    const historical = await database.subscription.findFirstOrThrow({ where: { tenantId } }); const historicalInvoice = await database.invoice.findFirstOrThrow({ where: { tenantId } }); expect(historical.priceMinor).toBe(2500); expect(historicalInvoice.amountMinor).toBe(2500); expect(historical.termsSnapshot).toMatchObject({ version: 1, priceMinor: 2500 });
    const refundKey = crypto.randomUUID(); const refund = await app.inject({ method: 'POST', url: `/v1/owner/commercial/transactions/${checkout.json().id}/refunds`, headers: { cookie: ownerCookie }, payload: { idempotencyKey: refundKey, amountMinor: 500, reason: 'Customer request' } }); expect(refund.statusCode).toBe(201); expect(refund.json().status).toBe('SUCCEEDED'); const duplicateRefund = await app.inject({ method: 'POST', url: `/v1/owner/commercial/transactions/${checkout.json().id}/refunds`, headers: { cookie: ownerCookie }, payload: { idempotencyKey: refundKey, amountMinor: 500 } }); expect(duplicateRefund.json()).toMatchObject({ id: refund.json().id, duplicate: true });
    const concurrentRefunds = await Promise.all([crypto.randomUUID(), crypto.randomUUID()].map((key) => app.inject({ method: 'POST', url: `/v1/owner/commercial/transactions/${checkout.json().id}/refunds`, headers: { cookie: ownerCookie }, payload: { idempotencyKey: key, amountMinor: 1500 } }))); expect(concurrentRefunds.map((item) => item.statusCode).sort()).toEqual([201, 409]);
    const subscription = await database.subscription.findFirstOrThrow({ where: { tenantId } }); expect((await app.inject({ method: 'POST', url: `/v1/commercial/subscriptions/${subscription.id}/cancel`, headers: { cookie: customerCookie } })).statusCode).toBe(200); expect((await app.inject({ method: 'POST', url: `/v1/commercial/subscriptions/${subscription.id}/cancel`, headers: { cookie: customerCookie } })).json().duplicate).toBe(true);
    const quote = await app.inject({ method: 'POST', url: '/v1/owner/commercial/quotes', headers: { cookie: ownerCookie }, payload: { tenantId, currency: 'USD', validUntil: new Date(Date.now() + 86_400_000).toISOString(), lineItems: [{ description: 'Incident readiness review', quantity: 2, unitMinor: 5000 }] } }); expect(quote.statusCode).toBe(201); expect(quote.json().totalMinor).toBe(10000); await app.inject({ method: 'PATCH', url: `/v1/owner/commercial/quotes/${quote.json().id}/status`, headers: { cookie: ownerCookie }, payload: { status: 'SENT' } }); expect((await app.inject({ method: 'POST', url: `/v1/customer/quotes/${quote.json().id}/view`, headers: { cookie: customerCookie } })).json().status).toBe('VIEWED'); expect((await app.inject({ method: 'POST', url: `/v1/customer/quotes/${quote.json().id}/accept`, headers: { cookie: customerCookie } })).json().status).toBe('ACCEPTED');
    const secondKey = crypto.randomUUID(); const second = await app.inject({ method: 'POST', url: '/v1/commercial/checkouts', headers: { cookie: customerCookie }, payload: { packageVersionId: newer.json().id, providerId, idempotencyKey: secondKey } }); const webhookBody = JSON.stringify({ id: 'event-valid-1', occurredAt: new Date().toISOString(), checkoutReference: second.json().checkoutReference, paymentReference: 'webhook-payment-1' }); const signature = createHmac('sha256', 'webhook-secret').update(webhookBody).digest('hex');
    expect((await app.inject({ method: 'POST', url: `/v1/payments/webhooks/${providerId}`, headers: { 'content-type': 'application/webhook+json', 'x-payment-signature': 'invalid' }, payload: webhookBody })).statusCode).toBe(401);
    const staleBody = JSON.stringify({ id: 'event-stale', occurredAt: new Date(Date.now() - 600_000).toISOString(), checkoutReference: second.json().checkoutReference, paymentReference: 'stale' }); const staleSignature = createHmac('sha256', 'webhook-secret').update(staleBody).digest('hex'); expect((await app.inject({ method: 'POST', url: `/v1/payments/webhooks/${providerId}`, headers: { 'content-type': 'application/webhook+json', 'x-payment-signature': staleSignature }, payload: staleBody })).json().error.code).toBe('WEBHOOK_REPLAY_REJECTED');
    const webhook = await app.inject({ method: 'POST', url: `/v1/payments/webhooks/${providerId}`, headers: { 'content-type': 'application/webhook+json', 'x-payment-signature': signature }, payload: webhookBody }); expect(webhook.json()).toEqual({ received: true, duplicate: false }); const duplicateWebhook = await app.inject({ method: 'POST', url: `/v1/payments/webhooks/${providerId}`, headers: { 'content-type': 'application/webhook+json', 'x-payment-signature': signature }, payload: webhookBody }); expect(duplicateWebhook.json()).toEqual({ received: true, duplicate: true });
    const conflictingBody = JSON.stringify({ id: 'event-valid-1', occurredAt: new Date().toISOString(), checkoutReference: second.json().checkoutReference, paymentReference: 'different-payment' }); const conflictingSignature = createHmac('sha256', 'webhook-secret').update(conflictingBody).digest('hex'); expect((await app.inject({ method: 'POST', url: `/v1/payments/webhooks/${providerId}`, headers: { 'content-type': 'application/webhook+json', 'x-payment-signature': conflictingSignature }, payload: conflictingBody })).json().error.code).toBe('WEBHOOK_EVENT_CONFLICT');
    const tenantBToken = await register('Customer', 'billing-attacker@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: tenantBToken } }); const tenantBCookie = cookieFrom((await login('customer', 'billing-attacker@example.test')).headers['set-cookie']); expect((await app.inject({ method: 'POST', url: `/v1/commercial/payments/${second.json().id}/verify`, headers: { cookie: tenantBCookie } })).statusCode).toBe(404);
  });

  it('fails closed for backup and restore, enforces retention scope, and deduplicates monitoring alert storms', async () => {
    const token = await register('Customer', 'operations@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token } }); const cookie = cookieFrom((await login('customer', 'operations@example.test')).headers['set-cookie']); const identity = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie } })).json(); const tenantId = identity.tenant.id as string;
    const site = await database.website.create({ data: { tenantId, name: 'Operations site', url: 'https://example.com/', normalizedHost: 'example.com', connectionStatus: 'VERIFIED', connectedAt: new Date() } });
    const schedulerFailure = await app.inject({ method: 'PATCH', url: `/v1/websites/${site.id}/monitoring`, headers: { cookie }, payload: { enabled: true } }); expect(schedulerFailure.statusCode).toBe(503); expect(await database.monitoringPolicy.findUniqueOrThrow({ where: { websiteId: site.id } })).toMatchObject({ enabled: false }); expect((await database.website.findUniqueOrThrow({ where: { id: site.id } })).monitoringStatus).toBe('ERROR');
    const failedBackup = await database.backup.create({ data: { tenantId, websiteId: site.id } }); await processBackupCreate({ id: `backup-${failedBackup.id}`, data: { action: 'CREATE', backupId: failedBackup.id, tenantId, websiteId: site.id } } as Job); expect(await database.backup.findUniqueOrThrow({ where: { id: failedBackup.id } })).toMatchObject({ status: 'FAILED', errorCode: 'BACKUP_PROVIDER_UNCONFIGURED' });
    const artifactData = { restoreReference: `tenants/${tenantId}/websites/${site.id}/backups/valid.zcb`, integrityHash: 'a'.repeat(64), sizeBytes: BigInt(100), encryption: { algorithm: 'AES-256-GCM', keyId: 'v1' }, providerKey: 'integration-backup', verifiedAt: new Date(), completedAt: new Date(), status: 'SUCCEEDED' as const };
    const validBackup = await database.backup.create({ data: { tenantId, websiteId: site.id, ...artifactData, retentionUntil: new Date(Date.now() - 10_000) } }); const restoreAuthorization = await database.restoreAuthorization.create({ data: { tenantId, websiteId: site.id, backupId: validBackup.id, authorizedByUserId: identity.user.id, expiresAt: new Date(Date.now() + 60_000), usedAt: new Date() } }); const restore = await database.restoreOperation.create({ data: { tenantId, websiteId: site.id, backupId: validBackup.id, authorizationId: restoreAuthorization.id } }); await processRestore({ id: `restore-${restore.id}`, data: { action: 'RESTORE', restoreId: restore.id, backupId: validBackup.id, tenantId, websiteId: site.id } } as Job); expect(await database.restoreOperation.findUniqueOrThrow({ where: { id: restore.id } })).toMatchObject({ status: 'FAILED', errorCode: 'BACKUP_PROVIDER_UNCONFIGURED' });
    const retainedBackup = await database.backup.create({ data: { tenantId, websiteId: site.id, ...artifactData, restoreReference: `tenants/${tenantId}/websites/${site.id}/backups/retained.zcb`, completedAt: new Date(Date.now() + 1000), retentionUntil: new Date(Date.now() + 86_400_000) } }); await database.backupPolicy.create({ data: { tenantId, websiteId: site.id, enabled: true, frequencyHours: 24, retentionDays: 30, restorePointLimit: 1 } }); let deleted = 0; const backupProvider: BackupProvider = { providerKey: 'integration-backup', async createBackup() { throw new Error('unused'); }, async verifyBackup() { return true; }, async restoreBackup() { throw new Error('RESTORE_PROVIDER_FAILURE'); }, async deleteBackup() { deleted += 1; } }; expect(await processRetention(tenantId, site.id, backupProvider)).toBe(1); expect(deleted).toBe(1); expect((await database.backup.findUniqueOrThrow({ where: { id: validBackup.id } })).deletedAt).not.toBeNull(); expect((await database.backup.findUniqueOrThrow({ where: { id: retainedBackup.id } })).deletedAt).toBeNull();
    const attackerToken = await register('Customer', 'operations-attacker@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: attackerToken } }); const attackerCookie = cookieFrom((await login('customer', 'operations-attacker@example.test')).headers['set-cookie']); expect((await app.inject({ method: 'POST', url: `/v1/websites/${site.id}/backups/${retainedBackup.id}/restore-authorizations`, headers: { cookie: attackerCookie } })).statusCode).toBe(404);
    await database.monitoringPolicy.update({ where: { websiteId: site.id }, data: { enabled: true, indicators: { expectedStatus: 200 }, alertCooldownMinutes: 60 } }); const response = { url: 'https://example.com/', status: 503, headers: {}, body: Buffer.from('maintenance'), resolvedAddress: '93.184.216.34', redirects: [] }; const runner = async () => response; const firstJob = { id: 'monitor-job-1', timestamp: Date.now(), data: { tenantId, websiteId: site.id } } as Job<{ tenantId: string; websiteId: string }>; expect(await processMonitoringCheck(firstJob, runner)).toEqual({ events: 2 }); expect(await processMonitoringCheck(firstJob, runner)).toEqual({ events: 2 }); expect(await database.monitoringCheck.count({ where: { tenantId, websiteId: site.id } })).toBe(1); expect(await database.securityAlert.count({ where: { tenantId, websiteId: site.id } })).toBe(2);
    await processMonitoringCheck({ id: 'monitor-job-2', timestamp: Date.now(), data: { tenantId, websiteId: site.id } } as Job, runner); expect(await database.securityAlert.count({ where: { tenantId, websiteId: site.id } })).toBe(2); expect(await database.notification.count({ where: { tenantId } })).toBe(2); expect((await database.securityAlert.aggregate({ where: { tenantId, websiteId: site.id }, _sum: { suppressedCount: true } }))._sum.suppressedCount).toBe(2); expect(await database.ticket.count({ where: { tenantId, websiteId: site.id, title: { startsWith: 'Monitoring escalation:' } } })).toBe(2);
    const specialistRole = await database.role.findFirstOrThrow({ where: { name: 'Cybersecurity Specialist', tenantId: null } }); const specialistTenant = await database.tenant.create({ data: { name: 'Isolated specialist', slug: `isolated-specialist-${crypto.randomUUID()}` } }); const specialistUser = await database.user.create({ data: { email: 'isolated-alert-specialist@example.test', passwordHash: await hashPassword(password), status: 'APPROVED', emailVerifiedAt: new Date() } }); await database.tenantMembership.create({ data: { tenantId: specialistTenant.id, userId: specialistUser.id, status: 'ACTIVE' } }); await database.userRole.create({ data: { tenantId: specialistTenant.id, userId: specialistUser.id, roleId: specialistRole.id } }); const specialistCookie = cookieFrom((await login('specialist', specialistUser.email)).headers['set-cookie']); const foreignAlert = await database.securityAlert.findFirstOrThrow({ where: { tenantId, websiteId: site.id } }); expect((await app.inject({ method: 'PATCH', url: `/v1/operations/alerts/${foreignAlert.id}`, headers: { cookie: specialistCookie }, payload: { status: 'RESOLVED' } })).statusCode).toBe(404);
    const mode = await app.inject({ method: 'PUT', url: '/v1/developer-mode', headers: { cookie }, payload: { enabled: true, durationMinutes: 10 } }); expect(mode.statusCode).toBe(200); const diagnostics = await app.inject({ method: 'GET', url: `/v1/websites/${site.id}/diagnostics`, headers: { cookie } }); expect(diagnostics.statusCode).toBe(200); expect(JSON.stringify(diagnostics.json())).not.toMatch(/secret|ciphertext|restoreReference/iu); expect(await database.auditLog.count({ where: { action: { startsWith: 'developer_mode.' } } })).toBe(2);
  });

  it('scopes agency clients and commerce grants, blocks escalation, and revokes access immediately', async () => {
    const agencyToken = await register('Agency', 'phase8-agency@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: agencyToken } }); const agencyUser = await database.user.findUniqueOrThrow({ where: { email: 'phase8-agency@example.test' } }); await database.user.update({ where: { id: agencyUser.id }, data: { status: 'APPROVED' } }); await database.tenantMembership.updateMany({ where: { userId: agencyUser.id }, data: { status: 'ACTIVE' } }); const agencyCookie = cookieFrom((await login('agency', agencyUser.email)).headers['set-cookie']); const agencyIdentity = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: agencyCookie } })).json(); const agencyTenantId = agencyIdentity.tenant.id as string;
    const customerAToken = await register('Customer', 'phase8-client-a@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerAToken } }); const customerA = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: cookieFrom((await login('customer', 'phase8-client-a@example.test')).headers['set-cookie']) } })).json(); const clientA = customerA.tenant.id as string;
    const customerBToken = await register('Customer', 'phase8-client-b@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerBToken } }); const customerB = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: cookieFrom((await login('customer', 'phase8-client-b@example.test')).headers['set-cookie']) } })).json(); const clientB = customerB.tenant.id as string;
    const relationship = await database.agencyClientRelationship.create({ data: { agencyTenantId, clientTenantId: clientA, status: 'ACTIVE', activatedAt: new Date(), permissions: ['CLIENT_READ', 'WEBSITES_READ', 'SECURITY_READ', 'TICKETS_READ', 'SUBSCRIPTIONS_READ', 'BILLING_READ', 'QUOTES_READ'] } });
    await database.website.createMany({ data: [{ tenantId: clientA, name: 'Client A One', url: 'https://a-one.example/', normalizedHost: 'a-one.example' }, { tenantId: clientA, name: 'Client A Two', url: 'https://a-two.example/', normalizedHost: 'a-two.example' }, { tenantId: clientB, name: 'Unrelated', url: 'https://unrelated.example/', normalizedHost: 'unrelated.example' }] });
    const clients = await app.inject({ method: 'GET', url: '/v1/agency/clients', headers: { cookie: agencyCookie } }); expect(clients.statusCode).toBe(200); expect(clients.json().clients).toHaveLength(1); expect(clients.json().clients[0].websites).toHaveLength(2);
    expect((await app.inject({ method: 'GET', url: `/v1/agency/clients/${clientB}`, headers: { cookie: agencyCookie, 'x-tenant-id': clientB } })).statusCode).toBe(404);
    expect((await app.inject({ method: 'GET', url: `/v1/agency/clients/${clientA}/billing?tenantId=${clientB}`, headers: { cookie: agencyCookie, 'x-tenant-id': clientB } })).statusCode).toBe(200);
    expect((await app.inject({ method: 'POST', url: '/v1/owner/agency-clients', headers: { cookie: agencyCookie }, payload: { agencyTenantId, clientTenantId: clientB } })).statusCode).toBe(403);
    const commercialPackage = await database.commercialPackage.create({ data: { key: `agency-${crypto.randomUUID()}` } }); const version = await database.packageVersion.create({ data: { packageId: commercialPackage.id, version: 1, name: 'Agency Protection', description: 'Authorized package', priceMinor: 10_000, currency: 'USD', billingInterval: 'MONTHLY', websiteLimit: 5, scanLimit: 20, monitoringIntervalMinutes: 60, backupFrequencyHours: 24, backupRetentionDays: 30, warrantyDays: 14, aiRequestLimit: 100, aiCostLimitMicros: 500_000, supportLevel: 'standard', featureEntitlements: {}, createdByUserId: agencyUser.id } }); await database.agencyCommercePolicy.create({ data: { agencyTenantId, markupBasisPoints: 1500, maxDiscountBasisPoints: 500, revenueShareBasisPoints: 2000 } }); await database.agencyPackageEntitlement.create({ data: { agencyTenantId, packageVersionId: version.id } });
    const quotePayload = { clientTenantId: clientA, packageVersionId: version.id, discountMinor: 500, validUntil: new Date(Date.now() + 86_400_000).toISOString() };
    expect((await app.inject({ method: 'POST', url: '/v1/agency/quotes', headers: { cookie: agencyCookie }, payload: quotePayload })).statusCode).toBe(404);
    await database.agencyClientRelationship.update({ where: { id: relationship.id }, data: { permissions: { push: 'QUOTES_MANAGE' } } }); const quote = await app.inject({ method: 'POST', url: '/v1/agency/quotes', headers: { cookie: agencyCookie }, payload: quotePayload }); expect(quote.statusCode).toBe(201); expect(quote.json()).toMatchObject({ subtotalMinor: 11_500, discountMinor: 500, totalMinor: 11_000, agencyTenantId, tenantId: clientA }); expect(quote.json().termsSnapshot).toMatchObject({ markupBasisPoints: 1500, revenueShareBasisPoints: 2000 });
    await database.agencyClientRelationship.update({ where: { id: relationship.id }, data: { status: 'REVOKED', revokedAt: new Date(), permissions: [] } }); expect((await app.inject({ method: 'GET', url: `/v1/agency/clients/${clientA}`, headers: { cookie: agencyCookie } })).statusCode).toBe(404); expect((await app.inject({ method: 'PATCH', url: `/v1/agency/quotes/${quote.json().id}/status`, headers: { cookie: agencyCookie }, payload: { status: 'SENT' } })).statusCode).toBe(404); expect((await app.inject({ method: 'GET', url: '/v1/agency/clients', headers: { cookie: agencyCookie } })).json().clients).toHaveLength(0);
    await database.agencyClientRelationship.update({ where: { id: relationship.id }, data: { status: 'ACTIVE', activatedAt: new Date(), revokedAt: null, permissions: ['CLIENT_READ'] } }); expect((await app.inject({ method: 'DELETE', url: `/v1/agency/clients/${clientA}`, headers: { cookie: agencyCookie } })).statusCode).toBe(204); expect((await app.inject({ method: 'GET', url: `/v1/agency/clients/${clientA}`, headers: { cookie: agencyCookie } })).statusCode).toBe(404);
  });

  it('prevents affiliate fraud and keeps recurring commissions and payouts idempotent', async () => {
    const affiliateToken = await register('Affiliate', 'phase9-affiliate@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: affiliateToken } }); const affiliateUser = await database.user.findUniqueOrThrow({ where: { email: 'phase9-affiliate@example.test' }, include: { memberships: true } }); await database.user.update({ where: { id: affiliateUser.id }, data: { status: 'APPROVED' } }); await database.tenantMembership.updateMany({ where: { userId: affiliateUser.id }, data: { status: 'ACTIVE' } }); const affiliateCookie = cookieFrom((await login('affiliate', affiliateUser.email)).headers['set-cookie']); const affiliateTenantId = affiliateUser.memberships[0]!.tenantId; const profile = await database.affiliateProfile.create({ data: { tenantId: affiliateTenantId, userId: affiliateUser.id, code: 'ZCPHASE9TEST' } });
    const customerToken = await register('Customer', 'phase9-customer@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerToken } }); const customerCookie = cookieFrom((await login('customer', 'phase9-customer@example.test')).headers['set-cookie']); const customer = (await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: customerCookie } })).json(); const customerTenantId = customer.tenant.id as string;
    const commercialPackage = await database.commercialPackage.create({ data: { key: `affiliate-${crypto.randomUUID()}` } }); const version = await database.packageVersion.create({ data: { packageId: commercialPackage.id, version: 1, name: 'Eligible', description: 'Eligible referral product', priceMinor: 10_000, currency: 'USD', billingInterval: 'MONTHLY', websiteLimit: 1, scanLimit: 1, monitoringIntervalMinutes: 60, backupFrequencyHours: 24, backupRetentionDays: 30, warrantyDays: 0, aiRequestLimit: 0, aiCostLimitMicros: 0, supportLevel: 'standard', featureEntitlements: {}, createdByUserId: affiliateUser.id } }); const config = await database.affiliateProgramConfig.create({ data: { version: 1, active: true, attributionWindowDays: 30, attributionModel: 'FIRST_TOUCH', commissionKind: 'RECURRING', calculation: 'PERCENTAGE', percentageBasisPoints: 1000, recurringDurationMonths: 2, payoutThresholdMinor: 1000, approvalRequired: false, eligibilityRules: {}, createdByUserId: affiliateUser.id, eligibleProducts: { create: { packageVersionId: version.id } } } });
    const attribution = await database.referralAttribution.create({ data: { affiliateId: profile.id, configId: config.id, tokenHash: 'a'.repeat(64), customerTenantId, expiresAt: new Date(Date.now() + 86_400_000) } }); await expect(database.referralAttribution.create({ data: { affiliateId: profile.id, configId: config.id, tokenHash: 'b'.repeat(64), customerTenantId, expiresAt: new Date(Date.now() + 86_400_000) } })).rejects.toThrow();
    const customerRole = await database.role.findFirstOrThrow({ where: { name: 'Customer', tenantId: null } }); await database.userRole.create({ data: { tenantId: affiliateTenantId, userId: affiliateUser.id, roleId: customerRole.id } }); const captured = await app.inject({ method: 'POST', url: '/v1/affiliate/attributions', payload: { code: profile.code } }); const referral = cookieFrom(captured.headers['set-cookie']); expect((await app.inject({ method: 'POST', url: '/v1/affiliate/attributions/claim', headers: { cookie: `${affiliateCookie}; ${referral}` } })).json().error.code).toBe('SELF_REFERRAL_FORBIDDEN');
    const provider = await database.paymentProviderConfig.create({ data: { name: 'Affiliate test', adapterKey: 'none' } }); const payments = [] as string[]; for (let period = 0; period < 3; period += 1) { const payment = await database.paymentTransaction.create({ data: { tenantId: customerTenantId, providerConfigId: provider.id, packageVersionId: version.id, idempotencyKey: crypto.randomUUID(), amountMinor: 10_000, currency: 'USD', status: 'SUCCEEDED', providerPaymentReference: `affiliate-payment-${period}`, completedAt: new Date() } }); payments.push(payment.id); await database.$transaction((tx) => createCommissionForPayment(tx, payment.id)); }
    expect(await database.affiliateConversion.count({ where: { attributionId: attribution.id } })).toBe(2); expect(await database.affiliateCommission.count({ where: { affiliateId: profile.id } })).toBe(2); await database.$transaction((tx) => createCommissionForPayment(tx, payments[0]!)); expect(await database.affiliateCommission.count({ where: { affiliateId: profile.id } })).toBe(2);
    await database.$transaction((tx) => reverseCommissionForPayment(tx, payments[1]!, 'Subscription cancelled')); expect((await database.affiliateCommission.findFirstOrThrow({ where: { conversion: { paymentTransactionId: payments[1]! } } })).status).toBe('REVERSED');
    const payable = await database.affiliateCommission.findFirstOrThrow({ where: { affiliateId: profile.id, status: 'PAYABLE' } }); const key = crypto.randomUUID(); const payout = await database.affiliatePayout.create({ data: { affiliateId: profile.id, affiliateTenantId, idempotencyKey: key, amountMinor: payable.amountMinor, currency: payable.currency } }); await database.affiliateCommission.update({ where: { id: payable.id }, data: { payoutId: payout.id } }); await expect(database.affiliatePayout.create({ data: { affiliateId: profile.id, affiliateTenantId, idempotencyKey: key, amountMinor: payable.amountMinor, currency: payable.currency } })).rejects.toThrow(); expect(await database.affiliatePayout.count({ where: { idempotencyKey: key } })).toBe(1);
  });

  it('protects Owner controls, settings, audit integrity, session revocation, and integration credentials', async () => {
    const ownerRole = await database.role.findFirstOrThrow({ where: { name: 'Owner', tenantId: null } }); const ownerTenant = await database.tenant.create({ data: { name: 'Control owner', slug: `control-owner-${crypto.randomUUID()}` } }); const ownerUser = await database.user.create({ data: { email: 'control-owner@example.test', passwordHash: await hashPassword(password), status: 'APPROVED', emailVerifiedAt: new Date() } }); await database.tenantMembership.create({ data: { tenantId: ownerTenant.id, userId: ownerUser.id, status: 'ACTIVE' } }); await database.userRole.create({ data: { tenantId: ownerTenant.id, userId: ownerUser.id, roleId: ownerRole.id } }); const challenge = (await login('owner', ownerUser.email)).json().challengeToken as string; const enrollment = (await app.inject({ method: 'POST', url: '/v1/auth/mfa/enroll', payload: { token: challenge } })).json(); const verified = await app.inject({ method: 'POST', url: '/v1/auth/mfa/confirm', payload: { challengeToken: challenge, code: totp(enrollment.secret) } }); const ownerCookie = cookieFrom(verified.headers['set-cookie']);
    const customerToken = await register('Customer', 'control-customer@example.test'); await app.inject({ method: 'POST', url: '/v1/auth/verify-email', payload: { token: customerToken } }); const customerLogin = await login('customer', 'control-customer@example.test'); const customerCookie = cookieFrom(customerLogin.headers['set-cookie']); const customerId = customerLogin.json().user.id as string;
    expect((await app.inject({ method: 'GET', url: '/v1/owner/control/users', headers: { cookie: customerCookie } })).statusCode).toBe(403); expect((await app.inject({ method: 'GET', url: '/v1/owner/control/users', headers: { cookie: ownerCookie } })).statusCode).toBe(200);
    expect((await app.inject({ method: 'POST', url: '/v1/auth/register', payload: { email: 'public-specialist@example.test', password, displayName: 'Public Specialist', organizationName: 'Unauthorized Staff', role: 'Cybersecurity Specialist' } })).statusCode).toBe(400);
    const specialistInvite=await app.inject({method:'POST',url:'/v1/owner/control/specialists',headers:{cookie:ownerCookie},payload:{email:'owner-created-specialist@example.test',displayName:'Owner Created Specialist'}});expect(specialistInvite.statusCode).toBe(201);expect(specialistInvite.json().inviteSent).toBe(true);const specialist=await database.user.findUniqueOrThrow({where:{email:'owner-created-specialist@example.test'},include:{memberships:true,userRoles:{include:{role:true}}}});expect(specialist.status).toBe('APPROVED');expect(specialist.memberships).toEqual(expect.arrayContaining([expect.objectContaining({tenantId:ownerTenant.id,status:'ACTIVE'})]));expect(specialist.userRoles.some((assignment)=>assignment.role.name==='Cybersecurity Specialist')).toBe(true);
    expect((await app.inject({ method: 'PUT', url: '/v1/owner/control/settings/defaultMonitoringIntervalMinutes', headers: { cookie: ownerCookie }, payload: { value: 45 } })).statusCode).toBe(200); expect((await database.systemSetting.findUniqueOrThrow({ where: { key: 'defaultMonitoringIntervalMinutes' } })).value).toBe(45);
    await database.systemSetting.create({ data: { key: 'notificationCooldownMinutes', value: 60, description: 'Protected test invariant', securityInvariant: true, changedByUserId: ownerUser.id } }); expect((await app.inject({ method: 'PUT', url: '/v1/owner/control/settings/notificationCooldownMinutes', headers: { cookie: ownerCookie }, payload: { value: 1 } })).statusCode).toBe(403);
    const secret = 'phase10-super-secret-credential'; const integration = await app.inject({ method: 'POST', url: '/v1/owner/control/integrations', headers: { cookie: ownerCookie }, payload: { type: 'STORAGE', name: 'Test object storage', adapterKey: 's3-compatible', enabled: true, credentials: secret, configuration: { region: 'test-1' } } }); expect(integration.statusCode).toBe(201); expect(JSON.stringify(integration.json())).not.toContain(secret); const stored = await database.platformIntegration.findUniqueOrThrow({ where: { id: integration.json().id } }); expect(stored.encryptedCredentials).not.toContain(secret);
    expect((await app.inject({ method: 'POST', url: `/v1/owner/control/users/${customerId}/revoke-sessions`, headers: { cookie: ownerCookie } })).json().revoked).toBe(1); expect((await app.inject({ method: 'GET', url: '/v1/auth/me', headers: { cookie: customerCookie } })).statusCode).toBe(401);
    const audit = await database.auditLog.findMany({ where: { action: { in: ['owner.specialist_created', 'system.setting_changed', 'integration.created', 'owner.user_sessions_revoked'] } } }); expect(audit).toHaveLength(4); expect(JSON.stringify(audit)).not.toContain(secret); const exported = await app.inject({ method: 'GET', url: '/v1/owner/control/audit-logs/export', headers: { cookie: ownerCookie } }); expect(exported.statusCode).toBe(200); expect(exported.headers['content-type']).toContain('text/csv'); expect(exported.body).not.toContain(secret);
  });

  it('deduplicates communication, retries email, isolates notifications, and protects signed reports', async () => {
    const tokenA=await register('Customer','phase11-a@example.test');await app.inject({method:'POST',url:'/v1/auth/verify-email',payload:{token:tokenA}});const loginA=await login('customer','phase11-a@example.test');const cookieA=cookieFrom(loginA.headers['set-cookie']);const identityA=(await app.inject({method:'GET',url:'/v1/auth/me',headers:{cookie:cookieA}})).json();const tenantA=identityA.tenant.id as string;const userA=identityA.user.id as string;
    const tokenB=await register('Customer','phase11-b@example.test');await app.inject({method:'POST',url:'/v1/auth/verify-email',payload:{token:tokenB}});const loginB=await login('customer','phase11-b@example.test');const cookieB=cookieFrom(loginB.headers['set-cookie']);
    const request={tenantId:tenantA,recipientId:userA,eventType:'SCAN_COMPLETED' as const,deduplicationKey:'phase11-scan-completed',title:'Scan completed',message:'The authorized scan completed.',actionUrl:'/customer/websites/site/scans'};const first=await publishCommunicationEvent(request);const second=await publishCommunicationEvent(request);expect(second).toEqual({eventId:first.eventId,duplicate:true});expect(await database.communicationEvent.count({where:{deduplicationKey:request.deduplicationKey}})).toBe(1);
    const emailJobs:string[]=[];await processCommunicationEvent(first.eventId,{add:async(_name:string,data:unknown)=>{emailJobs.push((data as {deliveryId:string}).deliveryId);return{} as never;}} as never);await processCommunicationEvent(first.eventId,{add:async()=>({} as never)} as never);expect(await database.notification.count({where:{eventId:first.eventId}})).toBe(1);expect(await database.emailDelivery.count({where:{eventId:first.eventId}})).toBe(1);expect(emailJobs).toHaveLength(1);
    const own=await app.inject({method:'GET',url:'/v1/notifications',headers:{cookie:cookieA}});const other=await app.inject({method:'GET',url:'/v1/notifications',headers:{cookie:cookieB}});expect(own.json().some((item:{eventId?:string})=>item.eventId===first.eventId)).toBe(true);expect(other.json().some((item:{eventId?:string})=>item.eventId===first.eventId)).toBe(false);
    const sharedTenantUser=await database.user.create({data:{email:'phase11-shared@example.test',passwordHash:await hashPassword(password),status:'APPROVED',emailVerifiedAt:new Date()}});const customerRole=await database.role.findFirstOrThrow({where:{name:'Customer',tenantId:null}});await database.tenantMembership.create({data:{tenantId:tenantA,userId:sharedTenantUser.id,status:'ACTIVE'}});await database.userRole.create({data:{tenantId:tenantA,userId:sharedTenantUser.id,roleId:customerRole.id}});const beforeOverview=(await app.inject({method:'GET',url:'/v1/customer/overview',headers:{cookie:cookieA}})).json().unreadNotifications as number;await database.notification.create({data:{tenantId:tenantA,recipientUserId:sharedTenantUser.id,title:'Private to another member',body:'Must not affect this user'}});const afterOverview=(await app.inject({method:'GET',url:'/v1/customer/overview',headers:{cookie:cookieA}})).json().unreadNotifications as number;expect(afterOverview).toBe(beforeOverview);
    const delivery=await database.emailDelivery.findUniqueOrThrow({where:{eventId:first.eventId}});let attempts=0;const retryingProvider:EmailProvider={async send(message){attempts+=1;if(attempts===1)throw new Error('SMTP_TEMPORARY_FAILURE');expect(message.idempotencyKey).toBe(delivery.idempotencyKey);return{providerMessageId:'provider-phase11'};}};await expect(processEmailDelivery({data:{deliveryId:delivery.id},attemptsMade:0,opts:{attempts:3}} as never,retryingProvider)).rejects.toThrow();expect((await database.emailDelivery.findUniqueOrThrow({where:{id:delivery.id}})).status).toBe('RETRYING');await processEmailDelivery({data:{deliveryId:delivery.id},attemptsMade:1,opts:{attempts:3}} as never,retryingProvider);expect(await database.emailDelivery.findUniqueOrThrow({where:{id:delivery.id}})).toMatchObject({status:'DELIVERED',attempts:2,providerMessageId:'provider-phase11'});
    const site=await database.website.create({data:{tenantId:tenantA,name:'Phase 11 site',url:'https://example.com/',normalizedHost:'example.com',connectionStatus:'VERIFIED',connectedAt:new Date()}});const scan=await database.scan.create({data:{tenantId:tenantA,websiteId:site.id,status:'SUCCEEDED',progress:100,completedAt:new Date()}});const report=await database.report.create({data:{tenantId:tenantA,websiteId:site.id,requestedByUserId:userA,type:'SECURITY_SCAN',sourceId:scan.id,title:'Authorized scan report'}});await processReport(report.id,environment);const completed=await database.report.findUniqueOrThrow({where:{id:report.id}});expect(completed).toMatchObject({status:'SUCCEEDED'});expect(completed.integrityHash).toHaveLength(64);expect(completed.signature).toHaveLength(64);const download=await app.inject({method:'GET',url:`/v1/websites/${site.id}/reports/${report.id}/download`,headers:{cookie:cookieA}});expect(download.statusCode).toBe(200);expect(download.headers['x-content-sha256']).toBe(completed.integrityHash);expect((await app.inject({method:'GET',url:`/v1/websites/${site.id}/reports/${report.id}/download`,headers:{cookie:cookieB}})).statusCode).toBe(404);expect((await app.inject({method:'GET',url:`/v1/websites/${site.id}/chat/stream`,headers:{cookie:cookieB,connection:'Upgrade',upgrade:'websocket','x-tenant-id':tenantA}})).statusCode).toBe(404);
  });
});
