'use client';

import Link from 'next/link';
import { CareReview, CareReviewForm, type ReviewRole } from './care-review';
import { CareRepair } from './care-repair';
import { CareWorkspace } from './care-workspace';
import { CareTools } from './care-tools';
import { useEffect, useRef, useState } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { MotionConfig, motion } from 'motion/react';
import { api, apiUrl, ApiClientError } from '../lib/api';

type Website = { id: string; name: string; url: string; connectionStatus: string };
type Message = { id: string; type: string; content: string; createdAt: string; author?: { displayName: string | null } | null };
type Credential = { id: string; kind: string; environment: string; host: string; username: string; version: number; status: string; authorizationExpiresAt: string };
type Grant = { id: string; specialistName: string; reason: string; status: string; expiresAt: string; credential: Credential };
type Agent = { id: string; name: string; task: string; state: string; heartbeatAt: string; resultMessageId: string | null };
type Job = { id: string; kind: string; summary: string; state: string; environment: string; errorCode: string | null; expectedBehavior?: string | null; agents: Agent[]; createdAt: string };
type CareState = { nextCursor?: string | null; credentials: Credential[]; accessRequests: Grant[]; jobs: Job[]; roles?: ReviewRole[]; capabilities: { sourceReview?: boolean; maximumReviewBudgetMicros?: number; attachments: boolean; isolatedRepair: boolean; deployment: boolean } };
const humanState = (value: string) => value.toLowerCase().replaceAll('_', ' ');
const time = (value: string) => new Date(value).toLocaleString();
const sensitive = (value: string) => /-----BEGIN .*PRIVATE KEY-----|\b(?:password|passwd|pwd|secret|token|api[_ -]?key)\s*[:=]\s*\S+|\bBearer\s+\S+|\bsk-[\w-]{12,}/iu.test(value);
const active = ['QUEUED','RUNNING','VERIFYING','WAITING_FOR_DEPENDENCY'];

export function CareChat({ website }: { website: Website }) {
  const client = useQueryClient(); const base = `/websites/${website.id}`;
  const [draft, setDraft] = useState(''); const [secure, setSecure] = useState(true); const [confirmed, setConfirmed] = useState(false);
  const [environment, setEnvironment] = useState('PRODUCTION'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [teamOpen, setTeamOpen] = useState(false); const [accessOpen, setAccessOpen] = useState(false); const [theme, setTheme] = useState('light'); const [reduceMotion, setReduceMotion] = useState(false);
  const [connected, setConnected] = useState(false); const [newActivity, setNewActivity] = useState(false); const [issueOpen, setIssueOpen] = useState(false);
  const [recoveryOpen, setRecoveryOpen] = useState(false);
  const [reviewOpen, setReviewOpen] = useState(false); const [teamLimit, setTeamLimit] = useState(24);
  const [summary, setSummary] = useState(''); const [expected, setExpected] = useState('');
  const [feedbackJob, setFeedbackJob] = useState<string | null>(null); const [feedback, setFeedback] = useState('');
  const viewport = useRef<HTMLDivElement>(null); const nearBottom = useRef(true); const controller = useRef<AbortController | null>(null); const alive = useRef(true); const initialMode = useRef(false);
  const care = useInfiniteQuery({ queryKey: ['care', website.id, environment], queryFn: ({ pageParam }) => api<CareState>(`${base}/care?environment=${environment}${pageParam ? `&before=${pageParam}` : ''}`), initialPageParam: null as string | null, getNextPageParam: (page) => page.nextCursor ?? undefined, refetchInterval: 10000, retry: false });
  const chat = useInfiniteQuery({ queryKey: ['chat', website.id, environment], queryFn: ({ pageParam }) => api<Message[]>(`${base}/chat?environment=${environment}${pageParam ? `&before=${pageParam}` : ''}`), initialPageParam: null as string | null, getNextPageParam: (page) => page.length === 200 ? page[0]!.id : undefined, refetchInterval: connected ? 15000 : 5000 });
  const careState = care.data?.pages[0];
  const messages = [...new Map((chat.data?.pages.slice().reverse().flat() ?? []).map((message) => [message.id, message])).values()];
  const careAvailable = Boolean(careState);
  const recovery = useQuery({ queryKey: ['care-recovery', website.id, environment], enabled: recoveryOpen && careAvailable, queryFn: () => api<{ state: string; observedAt: string; checks: Array<{ name: string; state: string; detail: string }>; limitation: string }>(`${base}/care/recovery?environment=${environment}`), refetchInterval: recoveryOpen ? 30000 : false, retry: false });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['care', website.id] }), client.invalidateQueries({ queryKey: ['chat', website.id] }), client.invalidateQueries({ queryKey: ['website', website.id] })]); };
  useEffect(() => { alive.current = true; return () => { alive.current = false; controller.current?.abort(); }; }, []);
  useEffect(() => {
    if (care.isError && !initialMode.current) { initialMode.current = true; setSecure(false); }
    if (careState && !initialMode.current) { initialMode.current = true; setSecure(careState.credentials.length === 0); }
  }, [careState, care.isError]);
  useEffect(() => {
    if (!careAvailable) return;
    const stream = new EventSource(`${apiUrl}${base}/activity/stream?environment=${environment}`, { withCredentials: true });
    stream.onopen = () => setConnected(true); stream.onerror = () => setConnected(false);
    stream.addEventListener('activity', () => { void client.invalidateQueries({ queryKey: ['care', website.id] }); void client.invalidateQueries({ queryKey: ['chat', website.id] }); });
    return () => { stream.close(); setConnected(false); };
  // The connection follows scope and availability, not each snapshot refresh.
  }, [base, client, website.id, environment, careAvailable]);
  useEffect(() => {
    if (!messages.length) return;
    if (nearBottom.current) viewport.current?.scrollTo({ top: viewport.current.scrollHeight, behavior: 'instant' }); else setNewActivity(true);
  }, [messages.length, careState?.jobs]);
  const jobs = [...new Map((care.data?.pages.flatMap((page) => page.jobs) ?? []).filter((job) => job.environment === environment).map((job) => [job.id, job])).values()];
  const allAgents = jobs.flatMap((job) => job.agents.map((agent) => ({ ...agent, jobId: job.id })));
  const agents = allAgents.slice(0, teamLimit);
  const credentials = careState?.credentials.filter((credential) => credential.environment === environment) ?? [];
  const grants = careState?.accessRequests.filter((grant) => grant.credential.environment === environment && ['PENDING','APPROVED'].includes(grant.status)) ?? [];
  async function action(path: string, body?: unknown, method = 'POST') {
    setError('');
    try { await api(path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); await refresh(); return true; }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'The request could not be completed.'); return false; }
  }
  async function submit() {
    if (busy || !draft.trim()) return;
    if (!secure && sensitive(draft)) { setSecure(true); setConfirmed(false); setNotice('This looks like access information. Secure capture is selected; confirm your authority before sending.'); return; }
    if (secure && !confirmed) { setError('Confirm your authority to store and use these accounts for scoped inspection.'); return; }
    if (!secure && environment !== 'PRODUCTION') { setError('The evidence assistant currently covers the production website. Staging access can be stored, but staging analysis needs its connector.'); return; }
    setBusy(true); setError(''); setNotice(''); const input = draft; setDraft(''); controller.current = new AbortController();
    try {
      await api(`${base}/chat/ingest`, { method: 'POST', signal: controller.current.signal, body: JSON.stringify(secure ? { mode: 'SECURE', idempotencyKey: crypto.randomUUID(), content: input, environment, authorizationConfirmed: true } : { mode: 'MESSAGE', content: input, idempotencyKey: crypto.randomUUID() }) });
      if (!alive.current) return;
      setConfirmed(false); if (secure) { setSecure(false); setNotice('Access stored securely. Connection has not been checked.'); }
      await refresh();
    } catch (caught) {
      if (!alive.current) return;
      setError(caught instanceof ApiClientError ? caught.message : 'The response connection ended. Check activity before retrying; work may still be running.');
      // Sensitive submissions are deliberately never restored to a browser draft or mutation cache.
      await refresh();
    } finally { if (alive.current) setBusy(false); }
  }
  const clearContext = (value: string) => { setEnvironment(value); setReviewOpen(false); setRecoveryOpen(false); setTeamLimit(24); setDraft(''); setConfirmed(false); setError(''); setNotice(''); setAccessOpen(false); setIssueOpen(false); setSummary(''); setExpected(''); setFeedbackJob(null); setFeedback(''); nearBottom.current = true; setNewActivity(false); };
  return <MotionConfig reducedMotion={reduceMotion ? 'always' : 'user'}><section className={`care-chat care-theme-${theme}`} data-reduce-motion={reduceMotion} aria-label={`${website.name} conversation`}>
    <header className="care-context"><div><span className="care-eyebrow">YOUR WEBSITE WORKSPACE</span><h2>{website.name}</h2><p>{new URL(website.url).hostname} <span aria-hidden="true">·</span> {humanState(website.connectionStatus)}</p></div><label className="care-environment">Environment<select aria-label="Environment" value={environment} disabled={busy} onChange={(event) => clearContext(event.target.value)}><option value="PRODUCTION">Production</option><option value="STAGING">Staging</option></select></label></header>
    <div className="care-live-note"><span className="care-safe-dot" aria-hidden="true"/><span>Production changes require separate approval.</span><span className="care-stream-state">{connected ? 'Live activity connected' : 'Reconnecting · refreshing status'}</span></div>
    <p className="care-small">Saved messages, submitted jobs and review files stay in your account. Reopen this website to continue; unsent drafts are not saved.</p>
    <nav className="care-toolbar" aria-label="Conversation controls"><button aria-expanded={teamOpen} onClick={() => setTeamOpen(!teamOpen)}>✦ Your AI team <span>{allAgents.filter((agent) => ['RUNNING','VERIFYING'].includes(agent.state)).length} working · {allAgents.filter((agent) => ['QUEUED','WAITING_FOR_DEPENDENCY'].includes(agent.state)).length} waiting</span></button><button aria-expanded={accessOpen} onClick={() => setAccessOpen(!accessOpen)}>Access <span>{credentials.length}</span></button><button aria-expanded={issueOpen} onClick={() => setIssueOpen(!issueOpen)}>Report an issue</button>{careState?.capabilities.sourceReview && <button aria-expanded={reviewOpen} onClick={() => setReviewOpen(!reviewOpen)}>Review source with AI team</button>}<button disabled={!careAvailable} aria-expanded={recoveryOpen} onClick={() => setRecoveryOpen(!recoveryOpen)}>Recovery readiness</button><button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`}>{theme === 'light' ? 'Dark' : 'Light'}</button><label className="care-motion"><input type="checkbox" checked={reduceMotion} onChange={(event) => setReduceMotion(event.target.checked)}/>Reduce motion</label></nav>
    {recoveryOpen && <section className="care-panel" aria-label="Recovery readiness"><h3>Recovery evidence</h3>{recovery.isLoading && <p role="status">Loading saved recovery records…</p>}{recovery.error && <p role="alert">{recovery.error.message}</p>}{recovery.data && <><p>Observed {time(recovery.data.observedAt)} · {humanState(recovery.data.state)}</p>{recovery.data.checks.map((check) => <article className="care-agent" key={check.name}><strong>{check.name} · {humanState(check.state)}</strong><p>{check.detail}</p></article>)}<p>{recovery.data.limitation}</p></>}<Link href={`/customer/websites/${website.id}/backups`}>View backups and restore controls</Link></section>}
    {teamOpen && <section className="care-panel" aria-label="Assigned AI team"><div className="care-panel-heading"><h3>Your AI team</h3><span>Only assigned roles appear here</span></div>{agents.length === 0 ? <p>No AI role has been assigned yet. Send a message to begin.</p> : <div className="care-agent-grid">{agents.map((agent) => <motion.article initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .18 }} className="care-agent" key={agent.id}><div className="care-agent-title"><span className="care-agent-avatar" aria-hidden="true">✦</span><strong>{agent.name}<small>AI role</small></strong><span className={`care-state care-state-${connected || !active.includes(agent.state) ? agent.state.toLowerCase() : 'stale'}`}>{connected || !active.includes(agent.state) ? humanState(agent.state) : 'status reconnecting'}</span></div><p>{agent.task}</p><small>Last activity {time(agent.heartbeatAt)}</small>{agent.resultMessageId && <a href={`#message-${agent.resultMessageId}`}>View result</a>}{active.includes(agent.state) && <div className="care-inline-actions"><button onClick={() => void action(`/jobs/${agent.jobId}/pause`)}>Pause work</button><button onClick={() => void action(`/jobs/${agent.jobId}/cancel`)}>Cancel work</button></div>}</motion.article>)}</div>}{allAgents.length > teamLimit && <button onClick={() => setTeamLimit(teamLimit + 24)}>Show more assigned agents</button>}</section>}
    {reviewOpen && careState?.capabilities.sourceReview && <CareReviewForm key={`${website.id}-${environment}`} websiteId={website.id} environment={environment} roles={careState.roles ?? []} maximumBudgetMicros={careState.capabilities.maximumReviewBudgetMicros ?? 5000000} onDone={() => { setReviewOpen(false); setTeamOpen(true); }}/>}
    {accessOpen && <section className="care-panel" aria-label="Stored access"><h3>Access to {environment.toLowerCase()}</h3><p>Storage and connection checks are separate. AI never receives these credential values.</p>{credentials.length ? credentials.map((credential) => <article className="care-access-row" key={credential.id}><div><strong>{credential.kind} · {credential.host}</strong><small>Secret hidden · {humanState(credential.status)} · inspection permission until {time(credential.authorizationExpiresAt)}</small></div><button onClick={() => void action(`${base}/credentials/${credential.id}`, undefined, 'DELETE')}>Revoke access</button></article>) : <p>No accounts stored in this environment.</p>}<button onClick={() => { setSecure(true); setConfirmed(false); setAccessOpen(false); }}>Add or replace access in chat</button>{environment === 'PRODUCTION' && credentials.some((credential) => credential.kind === 'SSH') && <button onClick={() => void action(`${base}/access/check`)}>Check saved SSH connection</button>}<p className="care-small">Revocation stops future platform access. Rotate any password a specialist has already copied.</p></section>}
    {issueOpen && <form className="care-panel care-issue-form" onSubmit={(event) => { event.preventDefault(); void action(`${base}/jobs`, { requestKey: crypto.randomUUID(), environment, summary, expectedBehavior: expected }).then((saved) => { if (saved) { setIssueOpen(false); setSummary(''); setExpected(''); } }); }}><h3>What needs fixing?</h3><label>What happens now?<textarea minLength={10} maxLength={1000} required value={summary} onChange={(event) => setSummary(event.target.value)}/></label><label>What should happen?<textarea minLength={10} maxLength={4000} required value={expected} onChange={(event) => setExpected(event.target.value)}/></label><p>We’ll record the issue and show which repair capabilities are available. This does not approve a production change.</p><button type="submit">Record issue</button></form>}
    <div className="care-conversation" ref={viewport} onScroll={() => { const element = viewport.current; if (element) nearBottom.current = element.scrollHeight - element.scrollTop - element.clientHeight < 90; }} tabIndex={0} aria-label="Conversation history">
      {chat.hasNextPage && <button disabled={chat.isFetchingNextPage} onClick={() => { nearBottom.current = false; void chat.fetchNextPage(); }}>Load older messages</button>}
      {chat.isLoading && <p role="status">Loading conversation…</p>}
      {chat.isError && <div role="alert">Conversation unavailable. <button onClick={() => void chat.refetch()}>Try again</button></div>}
      {!chat.isLoading && !messages.length && <div className="care-welcome"><span aria-hidden="true" className="care-welcome-icon">✦</span><h3>Let’s take care of your website.</h3><p>Tell us what you’ve noticed. Connect access securely, review the evidence, and stay in control of every change.</p><div><button onClick={() => { setSecure(false); setDraft('Help me understand the current website findings and coverage.'); }}>Understand my website</button><button onClick={() => { setSecure(true); setConfirmed(false); }}>Connect access securely</button><button onClick={() => setIssueOpen(true)}>Something isn’t working</button></div></div>}
      {messages.map((message) => <article className={`care-message care-message-${message.type.toLowerCase()}`} id={`message-${message.id}`} key={message.id}><div className="care-message-label"><strong>{message.type === 'CUSTOMER' ? 'You' : message.type === 'AI' ? 'ZeroRoot · AI assistant' : message.type === 'SPECIALIST' ? `${message.author?.displayName ?? 'Assigned specialist'} · Human` : 'ZeroRoot · System'}</strong><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{ img: () => <span>[Image omitted — use a protected attachment]</span>, a: ({ href, children }) => href && /^(https?:\/\/|\/[^/]|#)/i.test(href) ? <a href={href} rel="noopener noreferrer" target={href.startsWith('http') ? '_blank' : undefined}>{children}</a> : <span>{children}</span>, pre: ({ children }) => <div className="care-code"><pre>{children}</pre><button onClick={(event) => { const text = event.currentTarget.parentElement?.querySelector('pre')?.textContent ?? ''; void navigator.clipboard.writeText(text).then(() => setNotice('Code copied.')).catch(() => setError('Clipboard access was unavailable.')); }}>Copy code</button></div> }}>{message.content}</ReactMarkdown></article>)}
      {grants.map((grant) => <article className="care-approval" key={grant.id} aria-label="Specialist access request"><span className="care-eyebrow">HUMAN SPECIALIST · {grant.status}</span><h3>{grant.specialistName} requested {grant.credential.kind} access</h3><p>{grant.reason}</p><dl><dt>Account</dt><dd>{grant.credential.host} · {grant.credential.environment.toLowerCase()}</dd><dt>Expires</dt><dd>{time(grant.expiresAt)}</dd></dl><p>Approval allows this specialist to see and copy the actual credential. Expiry cannot erase a copy; rotation may be needed afterward.</p><div className="care-inline-actions">{grant.status === 'PENDING' ? <><button onClick={() => void action(`/access-requests/${grant.id}/approve`)}>Approve this access</button><button onClick={() => void action(`/access-requests/${grant.id}/deny`)}>Deny</button></> : <button onClick={() => void action(`/access-requests/${grant.id}/revoke`)}>Revoke grant</button>}</div></article>)}
      {jobs.filter((job) => job.kind === 'REPAIR').map((job) => <article className="care-repair-card" key={job.id}><span className="care-eyebrow">REPAIR REQUEST · {humanState(job.state)}</span><h3>{job.summary}</h3>{job.errorCode === 'ISOLATED_WORKER_NOT_CONFIGURED' && <p>Your issue is recorded. An isolated repair worker is not configured, so no patch or deployment has started. A specialist can help scope this work.</p>}{careState?.capabilities.isolatedRepair && <CareRepair key={`${job.id}-${environment}`} websiteId={website.id} jobId={job.id} credentials={careState.credentials}/>}<CareTools key={`tools-${job.id}-${environment}`} jobId={job.id} websiteId={website.id} environment={environment} review={false}/><Link href={`/customer/websites/${website.id}/tickets`}>View specialist options</Link><button onClick={() => { setFeedbackJob(job.id); setFeedback(''); }}>Add a correction or requirement</button>{feedbackJob === job.id && <form className="care-issue-form" onSubmit={(event) => { event.preventDefault(); void action(`/jobs/${job.id}/feedback`, { content: feedback }).then((saved) => { if (saved) { setFeedbackJob(null); setFeedback(''); setNotice('Feedback recorded. The revised scope needs review.'); } }); }}><label>What needs to change?<textarea required maxLength={4000} value={feedback} onChange={(event) => setFeedback(event.target.value)}/></label><button type="submit">Record feedback</button></form>}</article>)}
      {jobs.filter((job) => job.kind === 'REVIEW').map((job) => <article className="care-repair-card" key={job.id}><span className="care-eyebrow">SOURCE REVIEW · {humanState(job.state)}</span><h3>{job.summary}</h3><CareReview key={`${job.id}-${environment}`} jobId={job.id} websiteId={website.id} roles={careState?.roles ?? []} environment={environment}/><CareTools key={`tools-${job.id}-${environment}`} jobId={job.id} websiteId={website.id} environment={environment} review/></article>)}
      {jobs.filter((job) => job.kind === 'WORKSPACE').map((job) => <article className="care-repair-card" key={job.id}><h3>{job.summary}</h3><CareWorkspace jobId={job.id} websiteId={website.id}/></article>)}
      {jobs.filter((job) => job.kind === 'MONITOR_PLAN').map((job) => <article className="care-repair-card" key={job.id}><h3>{job.summary}</h3><p>{humanState(job.state)} · No monitoring was activated by this proposal.</p><details><summary>Saved proposal</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{job.expectedBehavior}</pre></details>{job.state !== 'CANCELLED' && <button onClick={() => void action(`/jobs/${job.id}/cancel`)}>Cancel proposal</button>}</article>)}
      {care.hasNextPage && <button disabled={care.isFetchingNextPage} onClick={() => void care.fetchNextPage()}>Load older jobs</button>}
      {busy && <p role="status" className="care-pending">{secure ? 'Saving access securely…' : 'Request submitted. Check Your AI team for execution status.'}</p>}
    </div>
    {newActivity && <button className="care-new-activity" onClick={() => { nearBottom.current = true; viewport.current?.scrollTo({ top: viewport.current.scrollHeight, behavior: 'instant' }); setNewActivity(false); }}>New activity ↓</button>}
    {care.isError && <p className="care-alert" role="alert">{care.error.message} <button onClick={() => void care.refetch()}>Retry workspace</button> <Link href={`/customer/websites/${website.id}/access`}>Use existing Secure Access</Link></p>}
    {error && <p className="care-alert" role="alert">{error}</p>}{notice && <p className="care-notice" role="status">{notice}</p>}
    <form className={`care-composer ${secure ? 'care-composer-secure' : ''}`} onSubmit={(event) => { event.preventDefault(); void submit(); }}>
      <div className="care-composer-mode"><button type="button" aria-pressed={secure} disabled={busy} onClick={() => { setSecure(!secure); setConfirmed(false); }}> {secure ? '🔒 Secure capture' : '✦ Message assistant'}</button><span>{secure ? 'Goes directly to the vault · excluded from AI and history' : 'Use Secure capture for any access information'}</span></div>
      <label className="sr-only" htmlFor={`care-draft-${website.id}`}>{secure ? 'Secure access details' : 'Message ZeroRoot'}</label><textarea id={`care-draft-${website.id}`} value={draft} disabled={busy} onChange={(event) => setDraft(event.target.value)} autoComplete="off" autoCorrect="off" spellCheck={!secure} data-private="true" maxLength={secure ? 100000 : 4000} placeholder={secure ? 'Paste access details here, for example:\nType: SSH\nHost: server.example.com\nUsername: deployment\nPassword: …' : 'Describe an issue or ask about your website…'} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && !secure && window.matchMedia('(min-width: 768px)').matches) { event.preventDefault(); void submit(); } }}/>
      {secure && <label className="care-consent"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} disabled={busy}/>I’m authorized to provide these accounts for this website and permit scoped read-only inspection for 24 hours. Repairs, release, and specialist disclosure require separate approval.</label>}
      <div className="care-composer-footer"><small>{secure ? 'Label each field. Separate accounts with ---.' : 'Shift + Enter for a new line.'}</small><button type="submit" className="care-send" disabled={busy || !draft.trim() || (secure && !confirmed) || (secure && care.isError)}>{busy ? 'Sending…' : secure ? 'Store securely ↑' : 'Send ↑'}</button></div>
    </form><footer className="care-footer"><span>Evidence first. You approve consequential changes.</span><Link href="/customer/support">Talk to a human specialist</Link></footer>
  </section></MotionConfig>;
}
