'use client';
import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';
type Role = { id: string; name: string; enabled: boolean; boundary: string; implementation: string; executionBoundary: string };
type Tool = { id: string; name: string; enabled: boolean; purpose: string };
export function CareCapabilities() {
  const query = useQuery({ queryKey: ['care-capabilities'], queryFn: () => api<{ roles: Role[]; tools: Tool[]; sourceReview: string; isolatedRepair: string; deployment: string; limitations: string[] }>('/owner/care/capabilities') });
  return <div className="care-chat"><header className="care-context"><div><span className="care-eyebrow">OWNER CONTROL CENTER</span><h2>Care capabilities</h2><p>Versioned roles and tools. Unavailable capabilities remain disabled.</p></div></header>{query.isError ? <p role="alert" className="care-alert">{query.error.message}</p> : query.data ? <><section className="care-panel"><p>Source reviews: {query.data.sourceReview} · Isolated repairs: {query.data.isolatedRepair} · Production release: {query.data.deployment}</p>{query.data.limitations.map((item) => <p key={item}>{item}</p>)}</section><section className="care-panel"><h3>24 role definitions</h3><div className="care-agent-grid">{query.data.roles.map((role) => <article key={role.id} className="care-agent"><strong>{role.id} · {role.name}</strong><span>{role.enabled ? role.implementation.toLowerCase().replaceAll('_', ' ') : 'Not enabled'}</span><p>{role.executionBoundary}</p><details><summary>Wider role scope</summary><p>{role.boundary}</p></details></article>)}</div></section><section className="care-panel"><h3>64 tool contracts</h3>{query.data.tools.map((tool) => <article key={tool.id} className="care-agent"><strong>{tool.id} · {tool.name}</strong><span>{tool.enabled ? 'Implemented for offline source review' : 'Implementation / evaluation required'}</span><p>{tool.purpose}</p></article>)}</section></> : <p role="status" className="care-panel">Loading capability registry…</p>}</div>;
}
