'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Card, EmptyState, ErrorState, LoadingState, Table } from '@zerochack/ui';
import { api } from '../lib/api';

type Plan = { id: string; key: string; versions: Array<{ id: string; version: number; name: string; description: string; priceMinor: number; currency: string; billingInterval: string; trialDays: number; websiteLimit: number; scanLimit: number; monitoringIntervalMinutes: number; backupFrequencyHours: number; backupRetentionDays: number; warrantyDays: number; aiRequestLimit: number; supportLevel: string; featureEntitlements: Record<string, boolean | string | number> }> };
type Commercial = { billingStatus: string; subscription: null | { id: string; planName: string; status: string; priceMinor: number | null; currency: string | null; billingInterval: string | null; trialEndsAt: string | null; currentPeriodEnd: string | null }; invoices: Array<{ id: string; invoiceNumber: string | null; amountMinor: number; currency: string; status: string; issuedAt: string }>; payments: Array<{ id: string; amountMinor: number; currency: string; status: string; createdAt: string; refunds: Array<{ id: string; amountMinor: number; status: string }> }>; quotes: Array<{ id: string; quoteNumber: string; status: string; totalMinor: number; currency: string; validUntil: string; lineItems: Array<{ id: string; description: string; quantity: number; totalMinor: number }> }> };
const money = (amount: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(amount / 100);

export function SubscriptionPage() {
  const client = useQueryClient(); const plans = useQuery<Plan[]>({ queryKey: ['plans'], queryFn: () => api('/commercial/packages') }); const account = useQuery<Commercial>({ queryKey: ['commercial'], queryFn: () => api('/customer/commercial') });
  const action = useMutation({ mutationFn: async ({ version, trial }: { version: Plan['versions'][number]; trial: boolean }) => api<{ checkoutUrl?: string }>(trial ? '/commercial/trials' : '/commercial/checkouts', { method: 'POST', body: JSON.stringify({ packageVersionId: version.id, idempotencyKey: crypto.randomUUID() }) }), onSuccess: async (result) => { await client.invalidateQueries({ queryKey: ['commercial'] }); if (result.checkoutUrl) window.location.assign(result.checkoutUrl); } });
  const cancel = useMutation({ mutationFn: (id: string) => api(`/commercial/subscriptions/${id}/cancel`, { method: 'POST' }), onSuccess: () => client.invalidateQueries({ queryKey: ['commercial'] }) });
  if (plans.isLoading || account.isLoading) return <LoadingState label="Loading subscription options" />; if (plans.isError || account.isError) return <ErrorState description={(plans.error ?? account.error)?.message ?? 'Unable to load subscriptions'} retry={() => { void plans.refetch(); void account.refetch(); }} />;
  const subscription = account.data?.subscription;
  return <div className="portal-stack"><header className="portal-heading"><div><span className="eyebrow">Subscription</span><h1>Coverage plan</h1><p>Terms shown here come from the published package version.</p></div><span className="status-pill">{account.data?.billingStatus.replaceAll('_', ' ').toLowerCase()}</span></header>
    {action.isError && <Alert title="Payment provider unavailable" tone="danger">{action.error.message}</Alert>}{cancel.isError && <Alert title="Cancellation failed" tone="danger">{cancel.error.message}</Alert>}
    {subscription && <Card><div className="resource-row"><div><strong>{subscription.planName}</strong><p>{subscription.priceMinor !== null && subscription.currency ? money(subscription.priceMinor, subscription.currency) : 'Historical price unavailable'} {subscription.billingInterval ? `· ${subscription.billingInterval.toLowerCase()}` : ''}</p></div><span className="status-pill">{subscription.status.toLowerCase()}</span></div>{!['CANCELLED', 'EXPIRED'].includes(subscription.status) && <div className="portal-actions"><Button variant="danger" size="sm" disabled={cancel.isPending} onClick={() => cancel.mutate(subscription.id)}>{cancel.isPending ? 'Cancelling…' : 'Cancel subscription'}</Button></div>}</Card>}
    <section><h2>Available packages</h2><div className="website-grid">{plans.data?.map((plan) => { const version = plan.versions[0]; if (!version) return null; return <Card key={plan.id} className="plan-card"><span className="eyebrow">Version {version.version}</span><h3>{version.name}</h3><strong className="plan-price">{money(version.priceMinor, version.currency)}</strong><p>{version.description}</p><dl className="data-list"><div><dt>Websites</dt><dd>{version.websiteLimit}</dd></div><div><dt>Scans</dt><dd>{version.scanLimit} / interval</dd></div><div><dt>Monitoring</dt><dd>{version.monitoringIntervalMinutes} min</dd></div><div><dt>Backups</dt><dd>Every {version.backupFrequencyHours}h</dd></div><div><dt>AI requests</dt><dd>{version.aiRequestLimit}</dd></div><div><dt>Support</dt><dd>{version.supportLevel}</dd></div></dl><div className="portal-actions"><Button disabled={action.isPending} onClick={() => action.mutate({ version, trial: version.trialDays > 0 })}>{version.trialDays > 0 ? `Start ${version.trialDays}-day trial` : 'Continue to checkout'}</Button></div></Card>; })}</div>{plans.data?.length === 0 && <EmptyState title="No packages published" description="An owner must publish a package before checkout can begin." />}</section>
  </div>;
}

export function BillingPage() {
  const client = useQueryClient(); const query = useQuery<Commercial>({ queryKey: ['commercial'], queryFn: () => api('/customer/commercial') }); const quote = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'view' | 'accept' }) => api(`/customer/quotes/${id}/${action}`, { method: 'POST' }), onSuccess: () => client.invalidateQueries({ queryKey: ['commercial'] }) });
  if (query.isLoading) return <LoadingState label="Loading billing records" />; if (query.isError) return <ErrorState description={query.error.message} retry={() => void query.refetch()} />; const data = query.data!;
  return <div className="portal-stack"><header className="portal-heading"><div><span className="eyebrow">Billing</span><h1>Invoices and payments</h1><p>Provider-verified financial records for your tenant.</p></div><span className="status-pill">{data.billingStatus.replaceAll('_', ' ').toLowerCase()}</span></header>{quote.isError && <Alert title="Quote action failed" tone="danger">{quote.error.message}</Alert>}
    <section><h2>Invoices</h2>{data.invoices.length ? <Table caption="Invoices" rows={data.invoices} rowKey={(row) => row.id} columns={[{ key: 'number', header: 'Invoice', render: (row) => row.invoiceNumber ?? 'Provider invoice' }, { key: 'amount', header: 'Amount', render: (row) => money(row.amountMinor, row.currency) }, { key: 'status', header: 'Status', render: (row) => <span className="status-pill">{row.status.toLowerCase()}</span> }, { key: 'date', header: 'Issued', render: (row) => new Date(row.issuedAt).toLocaleDateString() }]} /> : <EmptyState title="No invoices" description="Invoices appear only after provider confirmation." />}</section>
    <section><h2>Payment history</h2>{data.payments.length ? <Table caption="Payment history" rows={data.payments} rowKey={(row) => row.id} columns={[{ key: 'amount', header: 'Amount', render: (row) => money(row.amountMinor, row.currency) }, { key: 'status', header: 'Status', render: (row) => <span className="status-pill">{row.status.toLowerCase()}</span> }, { key: 'refunds', header: 'Refunds', render: (row) => row.refunds.length }, { key: 'date', header: 'Created', render: (row) => new Date(row.createdAt).toLocaleString() }]} /> : <EmptyState title="No payment history" description="No checkout or payment attempts exist for this tenant." />}</section>
    <section><h2>Quotes</h2><div className="resource-list">{data.quotes.map((item) => <Card key={item.id}><div className="resource-row"><div><strong>{item.quoteNumber}</strong><p>{money(item.totalMinor, item.currency)} · valid until {new Date(item.validUntil).toLocaleDateString()}</p></div><span className="status-pill">{item.status.toLowerCase()}</span></div><div className="portal-actions">{item.status === 'SENT' && <Button size="sm" variant="secondary" onClick={() => quote.mutate({ id: item.id, action: 'view' })}>View quote</Button>}{['SENT', 'VIEWED'].includes(item.status) && <Button size="sm" onClick={() => quote.mutate({ id: item.id, action: 'accept' })}>Accept quote</Button>}</div></Card>)}</div>{data.quotes.length === 0 && <EmptyState title="No quotes" description="There are no commercial quotes for this tenant." />}</section>
  </div>;
}

type OwnerDashboard = { revenue: Array<{ currency: string; grossMinor: number; refundedMinor: number; netMinor: number; successfulTransactions: number }>; providers: Array<{ id: string; name: string; adapterKey: string; enabled: boolean; healthStatus: string; lastHealthCheckAt: string | null }>; transactions: Array<{ id: string; tenantId: string; amountMinor: number; currency: string; status: string; createdAt: string }>; events: Array<{ id: string; eventType: string; status: string; receivedAt: string }> };
export function OwnerCommercial() {
  const query = useQuery<OwnerDashboard>({ queryKey: ['owner-commercial'], queryFn: () => api('/owner/commercial/dashboard') });
  if (query.isLoading) return <LoadingState label="Loading commercial operations" />; if (query.isError) return <ErrorState title="Owner MFA required" description={query.error.message} retry={() => void query.refetch()} />; const data = query.data!;
  return <div className="portal-stack"><header className="portal-heading"><div><span className="eyebrow">Owner operations</span><h1>Commercial platform</h1><p>Real provider health, payment events, transactions, and verified volume by currency.</p></div></header><div className="metric-grid">{data.revenue.map((item) => <Card key={item.currency}><span>{item.currency} net revenue</span><strong>{money(item.netMinor, item.currency)}</strong><small>{money(item.grossMinor, item.currency)} gross · {money(item.refundedMinor, item.currency)} refunded · {item.successfulTransactions} payments</small></Card>)}<Card><span>Configured providers</span><strong>{data.providers.length}</strong></Card></div>
    <section><h2>Provider health</h2>{data.providers.length ? <Table caption="Payment providers" rows={data.providers} rowKey={(row) => row.id} columns={[{ key: 'name', header: 'Provider', render: (row) => row.name }, { key: 'adapter', header: 'Adapter', render: (row) => row.adapterKey }, { key: 'enabled', header: 'Enabled', render: (row) => row.enabled ? 'Yes' : 'No' }, { key: 'health', header: 'Health', render: (row) => <span className="status-pill">{row.healthStatus.toLowerCase()}</span> }]} /> : <EmptyState title="No payment provider configured" description="Install a PaymentProvider adapter, then create and enable its encrypted configuration through the API." />}</section>
    <section><h2>Transactions</h2>{data.transactions.length ? <Table caption="Transactions" rows={data.transactions} rowKey={(row) => row.id} columns={[{ key: 'tenant', header: 'Tenant', render: (row) => row.tenantId }, { key: 'amount', header: 'Amount', render: (row) => money(row.amountMinor, row.currency) }, { key: 'status', header: 'Status', render: (row) => row.status.toLowerCase() }, { key: 'date', header: 'Created', render: (row) => new Date(row.createdAt).toLocaleString() }]} /> : <EmptyState title="No transactions" description="No real payment attempts have been recorded." />}</section>
    <section><h2>Payment events</h2>{data.events.length ? <Table caption="Payment events" rows={data.events} rowKey={(row) => row.id} columns={[{ key: 'type', header: 'Event', render: (row) => row.eventType }, { key: 'status', header: 'Status', render: (row) => row.status.toLowerCase() }, { key: 'date', header: 'Received', render: (row) => new Date(row.receivedAt).toLocaleString() }]} /> : <EmptyState title="No payment events" description="Verified provider webhooks will appear here." />}</section>
  </div>;
}
