'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, EmptyState, ErrorState, LoadingState, useToast } from '@zerochack/ui';
import { api } from '../lib/api';
import { MfaSettings } from './mfa-settings';

export function CustomerResource({ kind }: { kind: 'subscription' | 'billing' | 'notifications' | 'profile' }) {
  if(kind==='notifications')return <Notifications/>;
  const path = kind === 'profile' ? '/auth/me' : `/customer/${kind}`; const query = useQuery({ queryKey: [kind], queryFn: () => api<unknown>(path) });
  if (query.isLoading) return <LoadingState label={`Loading ${kind}`} />; if (query.isError) return <ErrorState description={query.error.message} retry={() => void query.refetch()} />;
  const data = query.data; const title = kind.charAt(0).toUpperCase() + kind.slice(1);
  if (data === null || (Array.isArray(data) && data.length === 0)) return <><h1>{title}</h1><EmptyState title={`No ${kind} data`} description={`No ${kind} records exist for this tenant.`} /></>;
  return <div className="portal-stack"><h1>{title}</h1>{Array.isArray(data) ? data.map((item: Record<string, unknown>) => <Card key={String(item.id)}><Data value={item} /></Card>) : <Card><Data value={data as Record<string, unknown>} /></Card>}{kind === 'profile' && <MfaSettings />}</div>;
}
function Data({ value }: { value: Record<string, unknown> }) { return <dl className="data-list">{Object.entries(value).filter(([key]) => !['id', 'tenantId', 'providerReference'].includes(key)).map(([key, item]) => <div key={key}><dt>{key.replaceAll(/([A-Z])/g, ' $1')}</dt><dd>{item === null ? 'Not available' : typeof item === 'string' && /^\d{4}-\d\d-\d\dT/.test(item) ? new Date(item).toLocaleString() : String(item)}</dd></div>)}</dl>; }

type Notification={id:string;title:string;body:string;eventType:string|null;readAt:string|null;createdAt:string};type Preference={eventType:string;inAppEnabled:boolean;emailEnabled:boolean};
function Notifications(){const cache=useQueryClient();const toast=useToast();const notices=useQuery<Notification[]>({queryKey:['notifications'],queryFn:()=>api('/notifications')});const preferences=useQuery<{preferences:Preference[]}>({queryKey:['notification-preferences'],queryFn:()=>api('/notification-preferences')});const read=useMutation({mutationFn:(id:string)=>api(`/notifications/${id}/read`,{method:'PATCH'}),onSuccess:()=>void cache.invalidateQueries({queryKey:['notifications']})});const save=useMutation({mutationFn:(preference:Preference)=>api(`/notification-preferences/${preference.eventType}`,{method:'PUT',body:JSON.stringify({inAppEnabled:preference.inAppEnabled,emailEnabled:preference.emailEnabled})}),onSuccess:()=>{toast.notify('Notification preference saved','success');void cache.invalidateQueries({queryKey:['notification-preferences']});},onError:(error:Error)=>toast.notify(error.message,'danger')});if(notices.isLoading||preferences.isLoading)return <LoadingState label="Loading notifications"/>;if(notices.isError||preferences.isError)return <ErrorState description={(notices.error??preferences.error)?.message??'Unable to load notifications'} retry={()=>{void notices.refetch();void preferences.refetch();}}/>;return <div className="portal-stack"><h1>Notifications</h1><section><h2>Preferences</h2><div className="resource-list">{preferences.data!.preferences.map((item)=><Card key={item.eventType}><strong>{item.eventType.replaceAll('_',' ').toLowerCase()}</strong><div className="portal-actions"><Button size="sm" variant="secondary" disabled={save.isPending} onClick={()=>save.mutate({...item,inAppEnabled:!item.inAppEnabled})}>In-app: {item.inAppEnabled?'On':'Off'}</Button><Button size="sm" variant="secondary" disabled={save.isPending} onClick={()=>save.mutate({...item,emailEnabled:!item.emailEnabled})}>Email: {item.emailEnabled?'On':'Off'}</Button></div></Card>)}</div></section><section><h2>Inbox</h2>{notices.data!.length?<div className="resource-list">{notices.data!.map((item)=><Card key={item.id}><div className="resource-row"><strong>{item.title}</strong><span className="status-pill">{item.readAt?'read':'unread'}</span></div><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString()}</small>{!item.readAt&&<div className="portal-actions"><Button size="sm" variant="secondary" disabled={read.isPending} onClick={()=>read.mutate(item.id)}>Mark read</Button></div>}</Card>)}</div>:<EmptyState title="No notifications" description="Important account and security events will appear here."/>}</section></div>}
