'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Card, ErrorState, Input, LoadingState, useToast } from '@zerochack/ui';
import { api } from '../lib/api';

type Status = { enabled: boolean; enabledAt: string | null; required: boolean };
type Setup = { secret: string; otpauthUri: string };

export function MfaSettings() {
  const cache = useQueryClient(); const toast = useToast(); const status = useQuery<Status>({ queryKey: ['mfa-status'], queryFn: () => api('/auth/mfa/status') }); const [setup, setSetup] = useState<Setup>(); const [qr, setQr] = useState<string>(); const [code, setCode] = useState(''); const [recovery, setRecovery] = useState<string[]>();
  useEffect(() => { if (setup) void QRCode.toDataURL(setup.otpauthUri, { width: 220, margin: 2, errorCorrectionLevel: 'M', color: { dark: '#07120f', light: '#ffffff' } }).then(setQr); }, [setup]);
  const begin = useMutation({ mutationFn: async () => { setSetup(await api<Setup>('/auth/mfa/setup', { method: 'POST', cache: 'no-store' })); }, onError: (error: Error) => toast.notify(error.message, 'danger') });
  const enable = useMutation({ mutationFn: async () => { const data = await api<{ recoveryCodes: string[] }>('/auth/mfa/enable', { method: 'POST', cache: 'no-store', body: JSON.stringify({ code }) }); setRecovery(data.recoveryCodes); }, onSuccess: () => { setSetup(undefined); setCode(''); void cache.invalidateQueries({ queryKey: ['mfa-status'] }); }, onError: (error: Error) => toast.notify(error.message, 'danger') });
  const disable = useMutation({ mutationFn: () => api('/auth/mfa/disable', { method: 'POST', body: JSON.stringify({ code }) }), onSuccess: () => { setCode(''); toast.notify('Authenticator MFA disabled', 'success'); void cache.invalidateQueries({ queryKey: ['mfa-status'] }); }, onError: (error: Error) => toast.notify(error.message, 'danger') });
  if (status.isLoading) return <LoadingState label="Loading authenticator settings" />; if (status.isError) return <ErrorState description={status.error.message} retry={() => void status.refetch()} />;
  if (recovery) return <Card><div className="portal-stack"><Alert title="Authenticator enabled" tone="success">Save these one-time recovery codes offline. They will not be shown again.</Alert><pre className="recovery-codes">{recovery.join('\n')}</pre><Button onClick={() => setRecovery(undefined)}>I saved these codes</Button></div></Card>;
  return <Card><div className="portal-stack"><div className="resource-row"><div><h2>Authenticator security</h2><p>Optional extra protection for your account.</p></div><span className="status-pill">{status.data!.enabled ? 'Enabled' : 'Disabled'}</span></div>{setup ? <><div className="mfa-enrollment"><div><span className="eyebrow">Optional MFA setup</span><h2>Scan this QR code</h2><p>Scan with your authenticator app, then enter its current six-digit code.</p></div>{qr ? <Image className="mfa-qr-code" src={qr} width={220} height={220} unoptimized alt="QR code for ZeroRoot authenticator setup" /> : <LoadingState label="Generating QR code" />}<details className="mfa-manual-key"><summary>Can’t scan? Use the setup key</summary><code>{setup.secret}</code></details></div><Input label="Six-digit authenticator code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/gu, '').slice(0, 6))} /><div className="portal-actions"><Button disabled={code.length !== 6 || enable.isPending} onClick={() => enable.mutate()}>Enable authenticator</Button><Button variant="secondary" onClick={() => { setSetup(undefined); setQr(undefined); setCode(''); }}>Cancel</Button></div></> : status.data!.enabled ? <><Alert title="MFA is optional" tone="info">Your account currently asks for an authenticator code after your password.</Alert><Input label="Current six-digit code to disable" inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/gu, '').slice(0, 6))} /><Button variant="danger" disabled={code.length !== 6 || disable.isPending} onClick={() => disable.mutate()}>Disable authenticator</Button></> : <><p>You can continue signing in with only your password, or enable an authenticator for additional security.</p><Button disabled={begin.isPending} onClick={() => begin.mutate()}>Enable authenticator</Button></>}</div></Card>;
}
