'use client';
import { useQuery } from '@tanstack/react-query'; import { Alert, Button, ErrorState, LoadingState, Table } from '@zerochack/ui';
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/v1';
type PendingUser = { id: string; email: string; displayName?: string; createdAt: string; userRoles: Array<{ tenantId: string; role: { name: string } }> };
export function OwnerApprovals() {
  const query = useQuery<{ users: PendingUser[] }>({ queryKey: ['owner-approvals'], queryFn: async () => { const response = await fetch(`${apiUrl}/owner/approvals`, { credentials: 'include', cache: 'no-store' }); if (!response.ok) throw new Error(response.status === 403 ? 'Owner MFA authorization is required.' : 'Unable to load approvals.'); return response.json(); } });
  const decide = async (userId: string, status: 'APPROVED' | 'REJECTED') => { const response = await fetch(`${apiUrl}/owner/users/${userId}/status`, { method: 'PATCH', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error('Decision could not be saved'); await query.refetch(); };
  if (query.isLoading) return <LoadingState label="Loading approval queue" />; if (query.error) return <ErrorState description={query.error.message} retry={() => void query.refetch()} />;
  return <div className="page-stack owner-console-page owner-approvals"><header className="portal-heading owner-console-heading"><div><span className="eyebrow">Owner security</span><h1>Account approvals</h1><p>Review verified Agency, Affiliate, and Specialist registrations before granting platform access.</p></div><span className="owner-queue-count">{query.data?.users.length ?? 0} pending</span></header>{query.data?.users.length === 0 ? <Alert title="No pending approvals" tone="info">The approval queue is empty.</Alert> : <div className="owner-record-panel"><div className="owner-record-panel__heading"><div><span className="eyebrow">Access governance</span><h2>Pending decisions</h2></div><strong>{query.data?.users.length ?? 0}</strong></div><Table caption="Pending account approvals" rows={query.data?.users ?? []} rowKey={(user) => user.id} columns={[{ key: 'user', header: 'Account', render: (user) => <div className="owner-person"><span>{(user.displayName ?? user.email).slice(0,1).toUpperCase()}</span><div><strong>{user.displayName ?? 'Unnamed'}</strong><small>{user.email}</small></div></div> }, { key: 'role', header: 'Role', render: (user) => <span className="status-pill">{user.userRoles[0]?.role.name ?? 'Unknown'}</span> }, { key: 'created', header: 'Registered', render: (user) => new Date(user.createdAt).toLocaleDateString() }, { key: 'actions', header: 'Decision', render: (user) => <div className="owner-row-actions"><Button size="sm" onClick={() => void decide(user.id, 'APPROVED')}>Approve</Button><Button size="sm" variant="danger" onClick={() => void decide(user.id, 'REJECTED')}>Reject</Button></div> }]} /></div>}</div>;
}
