'use client';

import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, EmptyState, ErrorState, Input, LoadingState, Select, Table, useToast } from '@zerochack/ui';
import { api } from '../lib/api';

type View = 'tickets' | 'commissions' | 'payouts';
type Ticket = { id:string; title:string; status:string; progressStage:string; createdAt:string; website:{name:string}; assignedSpecialist?:{displayName?:string|null;email:string}|null };
type Specialist = { id:string; displayName?:string|null; email:string };
type Commission = { id:string; amountMinor:number; currency:string; status:string; createdAt:string; affiliate:{code:string}; conversion?:{recurringPeriod?:number|null}|null };
type Payout = { id:string; amountMinor:number; currency:string; status:string; createdAt:string; providerReference?:string|null; affiliate:{code:string} };
type OwnerAction = { isPending:boolean; mutate:(input:{url:string;body:Record<string,unknown>})=>void };
const pretty=(value:string)=>value.replaceAll('_',' ').toLowerCase();
const money=(amount:number,currency:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount/100);
const copy={tickets:['Ticket operations','Assign approved specialists, escalate urgent work, and follow every customer case.'],commissions:['Commission review','Approve or cancel pending affiliate earnings with a complete audit trail.'],payouts:['Payout operations','Move payable batches through approval, processing, and provider-confirmed settlement.']} as const;

export function OwnerOperations({view}:{view:View}) {
  const cache=useQueryClient();const toast=useToast();const [status,setStatus]=useState('');
  const query=useQuery<Record<string,unknown>>({queryKey:['owner-operations',view,status],queryFn:()=>api(`/owner/control/${view}?status=${encodeURIComponent(status)}`)});
  const action=useMutation({mutationFn:({url,body}:{url:string;body:Record<string,unknown>})=>api(url,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:()=>{toast.notify('Owner action saved','success');void cache.invalidateQueries({queryKey:['owner-operations',view]});},onError:(error:Error)=>toast.notify(error.message,'danger')});
  if(query.isLoading)return <LoadingState label={`Loading ${view}`}/>;
  if(query.isError)return <ErrorState description={query.error.message} retry={()=>void query.refetch()}/>;
  return <div className="portal-stack owner-console-page"><header className="portal-heading owner-console-heading"><div><span className="eyebrow">Owner control center</span><h1>{copy[view][0]}</h1><p>{copy[view][1]}</p></div></header><div className="inline-form owner-filter-bar"><Select label="Status filter" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option>{view==='tickets'?<><option value="CREATED">Created</option><option value="QUEUED">Queued</option><option value="ASSIGNED">Assigned</option><option value="ESCALATED">Escalated</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></>:view==='commissions'?<><option value="PENDING">Pending</option><option value="PAYABLE">Payable</option><option value="PAID">Paid</option><option value="CANCELLED">Cancelled</option></>:<><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="PROCESSING">Processing</option><option value="PAID">Paid</option><option value="FAILED">Failed</option></>}</Select><Button variant="secondary" onClick={()=>void query.refetch()}>Refresh records</Button></div>{view==='tickets'?<Tickets data={query.data} action={action}/>:view==='commissions'?<Commissions data={query.data} action={action}/>:<Payouts data={query.data} action={action}/>}</div>;
}

function Tickets({data,action}:{data:Record<string,unknown>|undefined;action:OwnerAction}) {
  const rows=(data?.records??[]) as Ticket[];const specialists=(data?.specialists??[]) as Specialist[];const [assigned,setAssigned]=useState<Record<string,string>>({});
  if(!rows.length)return <EmptyState title="No tickets" description="No security tickets match the selected status."/>;
  return <div className="owner-record-panel"><div className="owner-record-panel__heading"><div><span className="eyebrow">Security workflow</span><h2>Customer cases</h2></div><strong>{rows.length}</strong></div><Table caption="Owner ticket operations" rows={rows} rowKey={(row)=>row.id} columns={[{key:'ticket',header:'Ticket',render:(row)=><div><strong>{row.title}</strong><br/><small>{row.website.name} · {new Date(row.createdAt).toLocaleDateString()}</small></div>},{key:'status',header:'Status',render:(row)=><span className="status-pill">{pretty(row.status)}</span>},{key:'specialist',header:'Specialist',render:(row)=><div>{row.assignedSpecialist?.displayName??row.assignedSpecialist?.email??'Unassigned'}</div>},{key:'actions',header:'Controls',render:(row)=><div className="ticket-owner-actions"><Select label="Assign specialist" aria-label={`Assign ${row.title}`} value={assigned[row.id]??''} onChange={(event)=>setAssigned((current)=>({...current,[row.id]:event.target.value}))}><option value="">Choose specialist</option>{specialists.map((person)=><option key={person.id} value={person.id}>{person.displayName??person.email}</option>)}</Select><Button size="sm" disabled={!assigned[row.id]||action.isPending} onClick={()=>action.mutate({url:`/owner/control/tickets/${row.id}`,body:{assignedSpecialistId:assigned[row.id]}})}>Assign</Button>{!['CLOSED','CANCELLED','RESOLVED'].includes(row.status)&&<Button size="sm" variant="secondary" disabled={action.isPending} onClick={()=>action.mutate({url:`/owner/control/tickets/${row.id}`,body:{escalate:true}})}>Escalate</Button>}</div>}]} /></div>;
}

function Commissions({data,action}:{data:Record<string,unknown>|undefined;action:OwnerAction}) {
  const rows=(data?.records??[]) as Commission[];
  if(!rows.length)return <EmptyState title="No commissions" description="No affiliate commissions match the selected status."/>;
  return <div className="owner-record-panel"><div className="owner-record-panel__heading"><div><span className="eyebrow">Affiliate finance</span><h2>Commission ledger</h2></div><strong>{rows.length}</strong></div><Table caption="Affiliate commissions" rows={rows} rowKey={(row)=>row.id} columns={[{key:'affiliate',header:'Affiliate',render:(row)=><strong>{row.affiliate.code}</strong>},{key:'amount',header:'Amount',render:(row)=>money(row.amountMinor,row.currency)},{key:'status',header:'Status',render:(row)=><span className="status-pill">{pretty(row.status)}</span>},{key:'created',header:'Recorded',render:(row)=>new Date(row.createdAt).toLocaleDateString()},{key:'actions',header:'Review',render:(row)=>row.status==='PENDING'?<div className="owner-row-actions"><Button size="sm" disabled={action.isPending} onClick={()=>action.mutate({url:`/owner/affiliate/commissions/${row.id}`,body:{status:'APPROVED'}})}>Approve</Button><Button size="sm" variant="danger" disabled={action.isPending} onClick={()=>action.mutate({url:`/owner/affiliate/commissions/${row.id}`,body:{status:'CANCELLED'}})}>Cancel</Button></div>:<small>Review complete</small>}]} /></div>;
}

function Payouts({data,action}:{data:Record<string,unknown>|undefined;action:OwnerAction}) {
  const rows=(data?.records??[]) as Payout[];const [references,setReferences]=useState<Record<string,string>>({});
  if(!rows.length)return <EmptyState title="No payouts" description="No affiliate payout batches match the selected status."/>;
  return <div className="owner-record-panel"><div className="owner-record-panel__heading"><div><span className="eyebrow">Settlement control</span><h2>Payout batches</h2></div><strong>{rows.length}</strong></div><Table caption="Affiliate payouts" rows={rows} rowKey={(row)=>row.id} columns={[{key:'affiliate',header:'Affiliate',render:(row)=><strong>{row.affiliate.code}</strong>},{key:'amount',header:'Amount',render:(row)=>money(row.amountMinor,row.currency)},{key:'status',header:'Status',render:(row)=><span className="status-pill">{pretty(row.status)}</span>},{key:'created',header:'Created',render:(row)=>new Date(row.createdAt).toLocaleDateString()},{key:'actions',header:'Controls',render:(row)=><div className="owner-row-actions">{row.status==='PENDING'&&<><Button size="sm" onClick={()=>action.mutate({url:`/owner/affiliate/payouts/${row.id}`,body:{status:'APPROVED'}})}>Approve</Button><Button size="sm" variant="danger" onClick={()=>action.mutate({url:`/owner/affiliate/payouts/${row.id}`,body:{status:'CANCELLED'}})}>Cancel</Button></>}{row.status==='APPROVED'&&<Button size="sm" onClick={()=>action.mutate({url:`/owner/affiliate/payouts/${row.id}`,body:{status:'PROCESSING'}})}>Start processing</Button>}{row.status==='PROCESSING'&&<div className="payout-confirm"><Input label="Provider reference" value={references[row.id]??''} onChange={(event)=>setReferences((current)=>({...current,[row.id]:event.target.value}))}/><Button size="sm" disabled={!references[row.id]||action.isPending} onClick={()=>action.mutate({url:`/owner/affiliate/payouts/${row.id}`,body:{status:'PAID',providerReference:references[row.id]}})}>Confirm paid</Button><Button size="sm" variant="danger" onClick={()=>action.mutate({url:`/owner/affiliate/payouts/${row.id}`,body:{status:'FAILED',failureCode:'MANUAL_PROCESSING_FAILED'}})}>Mark failed</Button></div>}{['PAID','FAILED','CANCELLED'].includes(row.status)&&<small>Final state</small>}</div>}]} /></div>;
}
