'use client';
import Link from 'next/link';

type Role = 'customer' | 'agency' | 'affiliate' | 'specialist';
type Value = string | number;
type Config = { eyebrow: string; title: string; highlight: string; description: string; metrics: Array<[string, Value, string]>; focus: Array<[string, string, Value, string]>; actions: Array<[string, string]> };
const number = (value: unknown) => Number(value ?? 0);
const nested = (data: Record<string, unknown>, key: string, child: string) => number((data[key] as Record<string, unknown> | undefined)?.[child]);
const money = (minor: unknown) => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(number(minor) / 100);

function config(role: Role, data: Record<string, unknown>): Config {
  if (role === 'customer') return { eyebrow: 'Your protection center', title: 'Your digital world,', highlight: 'beautifully protected.', description: 'See what matters, understand every signal, and move from risk to resolution with confidence.', metrics: [['Protected websites',number(data.protectedWebsites),'/customer/websites'],['Open findings',number(data.openFindings),'/customer/websites'],['Active monitoring',`${nested(data,'monitoring','active')} / ${nested(data,'monitoring','total')}`,'/customer/websites'],['Verified backups',`${nested(data,'backups','active')} / ${nested(data,'backups','total')}`,'/customer/websites']], focus: [['Critical findings','Resolve urgent website risk',number(data.criticalFindings),'/customer/websites'],['Open tickets','Continue security conversations',number(data.openTickets),'/customer/websites'],['Notifications','See what changed',number(data.unreadNotifications),'/customer/notifications']], actions: [['Add or manage websites','/customer/websites'],['Review subscription','/customer/subscription'],['Open billing','/customer/billing'],['Secure your profile','/customer/profile']] };
  if (role === 'agency') return { eyebrow: 'Agency command center', title: 'Every client,', highlight: 'one clear horizon.', description: 'Guide client security, commercial activity, and operational priorities from one connected workspace.', metrics: [['Active clients',number(data.clients),'/agency/clients'],['Protected websites',number(data.websites),'/agency/websites'],['Subscriptions',number(data.subscriptions),'/agency/subscriptions'],['Unread updates',number(data.unreadNotifications),'/agency/notifications']], focus: [['Open tickets','Coordinate client response',number(data.openTickets),'/agency/clients'],['Client portfolio','Review authorized access',number(data.clients),'/agency/clients'],['New updates','Stay ahead of changes',number(data.unreadNotifications),'/agency/notifications']], actions: [['Manage clients','/agency/clients'],['View websites','/agency/websites'],['Create a quote','/agency/quotes'],['Agency profile','/agency/profile']] };
  if (role === 'affiliate') return { eyebrow: 'Growth intelligence', title: 'Every connection,', highlight: 'growing with purpose.', description: 'Follow the journey from referral to reward with transparent performance and payout visibility.', metrics: [['Referrals',number(data.referrals),'/affiliate/referrals'],['Conversions',number(data.conversions),'/affiliate/transactions'],['Commissions',number(data.commissions),'/affiliate/commissions'],['Payable balance',money(data.payableMinor),'/affiliate/commissions']], focus: [['Pending payouts','Track money in motion',number(data.pendingPayouts),'/affiliate/payouts'],['Conversions','Measure trusted growth',number(data.conversions),'/affiliate/transactions'],['Total referrals','See your audience expand',number(data.referrals),'/affiliate/referrals']], actions: [['Copy referral link','/affiliate/referral-link'],['View referrals','/affiliate/referrals'],['Review commissions','/affiliate/commissions'],['Payout history','/affiliate/payouts']] };
  return { eyebrow: 'Specialist operations', title: 'Focused work,', highlight: 'meaningful impact.', description: 'Move authorized remediation forward with clear scope, secure sessions, and accountable outcomes.', metrics: [['Available jobs',number(data.availableJobs),'/specialist/jobs'],['My open tickets',number(data.myOpenTickets),'/specialist/tickets'],['Secure sessions',number(data.activeSessions),'/specialist/sessions'],['Resolved tickets',number(data.resolvedTickets),'/specialist/performance']], focus: [['Available work','Choose the next priority',number(data.availableJobs),'/specialist/jobs'],['Active tickets','Continue authorized work',number(data.myOpenTickets),'/specialist/tickets'],['Live sessions','Watch scoped access',number(data.activeSessions),'/specialist/sessions']], actions: [['Browse available jobs','/specialist/jobs'],['Open my tickets','/specialist/tickets'],['Review sessions','/specialist/sessions'],['View performance','/specialist/performance']] };
}

export function RoleDashboard({ role, data }: { role: Role; data: Record<string, unknown> }) { const c=config(role,data);return <div className={`role-dashboard role-dashboard--${role}`}><section className="role-command"><div className="role-command__copy"><span className="role-live"><i/>{c.eyebrow}</span><h1>{c.title}<br/><em>{c.highlight}</em></h1><p>{c.description}</p><Link className="role-primary" href={c.actions[0]![1]}>{c.actions[0]![0]} <span>→</span></Link></div><div className="role-visual" aria-hidden="true"><i className="role-ring r1"/><i className="role-ring r2"/><i className="role-ring r3"/><span className="role-core"><b>{role[0]!.toUpperCase()}</b><small>Live</small></span><em className="role-dot d1"/><em className="role-dot d2"/><em className="role-dot d3"/></div></section><section className="role-metrics">{c.metrics.map(([label,value,href],index)=><Link href={href} className="role-metric" key={label} style={{'--role-delay':`${index*80}ms`} as React.CSSProperties}><span>0{index+1}</span><small>{label}</small><strong>{value}</strong><i><b/></i><em>View details →</em></Link>)}</section><section className="role-lower"><article className="role-focus"><span className="role-section-label">Your focus</span><h2>What deserves attention</h2><div>{c.focus.map(([label,copy,value,href])=><Link href={href} key={label}><span><strong>{label}</strong><small>{copy}</small></span><b>{value}</b><em>→</em></Link>)}</div></article><article className="role-pulse"><span className="role-section-label">Live posture</span><div className="role-pulse__orb"><i/><b>Ready</b></div><h2>Workspace in sync</h2><p>Your latest role-authorized data is connected and ready for action.</p></article></section><section className="role-actions"><div><span className="role-section-label">Move forward</span><h2>Quick actions</h2></div><nav>{c.actions.map(([label,href],index)=><Link href={href} key={href}><span>0{index+1}</span>{label}<b>→</b></Link>)}</nav></section></div> }
