/** Browser-safe directory shared by marketing and the actual review intake. */
export const coreReviewRoleIds = ['A01','A03','A05','A14','A18'] as const;
export const technologyChecks = {
  T19: 'Declared npm dependencies (package.json; no advisory lookup)',
  T31: 'HTML attribute checks (.html / .htm)',
  T32: 'Local HTML fragment links (.html / .htm)',
  T65: 'JavaScript / TypeScript / strict JSON syntax',
  T66: 'Standalone CSS syntax',
  T67: 'YAML syntax and duplicate keys'
} as const;
export type TechnologyCheckId = keyof typeof technologyChecks;
export type TechnologyArea = {
  id: string; title: string; group: string; symbol: string; description: string; tags: string[];
  roleIds: readonly string[]; examples: string[]; checkIds: TechnologyCheckId[];
};
export const technologyGroups = ['All technologies', 'Frontend & apps', 'Backend & data', 'Servers & DevOps', 'Security & reliability'] as const;
export const technologyCoverage: TechnologyArea[] = [
  { id: "frontend", roleIds: [...coreReviewRoleIds, "A08", "A09", "A10", "A15", "A21", "A24"], examples: ["src/page.tsx", "styles.css", "page.astro", "App.vue", "App.svelte"], checkIds: ["T31", "T32", "T65", "T66", "T19"], title: 'Frontend & user experience', group: 'Frontend & apps', symbol: '◧', description: 'Review broken layouts, responsive behavior, accessibility, rendering logic and user journeys.', tags: ['HTML / CSS / SCSS', 'JavaScript / TypeScript', 'React / Next.js', 'Vue / Nuxt', 'Svelte / SvelteKit', 'Angular / Astro'] },
  { id: "cms", roleIds: [...coreReviewRoleIds, "A08", "A19", "A20", "A21"], examples: ["theme.php", "sections/product.liquid", "template.twig", "package.json"], checkIds: ["T19", "T65", "T66"], title: 'CMS, commerce & web platforms', group: 'Frontend & apps', symbol: '▦', description: 'Review supplied theme, plugin and storefront source; plan content, SEO and integration improvements.', tags: ['WordPress / WooCommerce', 'Shopify theme excerpts', 'Drupal / Joomla', 'Magento / Adobe Commerce', 'Headless CMS', 'Custom web applications'] },
  { id: "backend", roleIds: [...coreReviewRoleIds, "A06", "A07", "A13", "A16"], examples: ["api.ts", "views.py", "Controller.php", "Service.java", "Program.cs", "server.go", "lib.rs", "app.rb"], checkIds: ["T19", "T65"], title: 'Backend & application frameworks', group: 'Backend & data', symbol: '⌘', description: 'Trace application logic, validation and error handling in supplied code. Plan changes for a developer to implement.', tags: ['Node.js / Express / NestJS', 'PHP / Laravel / Symfony', 'Python / Django / FastAPI', 'Java / Spring', '.NET / C# excerpts', 'Go / Rust / Ruby on Rails'] },
  { id: "apis", roleIds: [...coreReviewRoleIds, "A07", "A13", "A20"], examples: ["openapi.yaml", "schema.graphql", "service.proto", "webhook.ts"], checkIds: ["T65", "T67"], title: 'APIs, identity & integrations', group: 'Backend & data', symbol: '⇄', description: 'Review endpoint logic, authorization, webhooks, integration failures, retry behavior and timeout handling.', tags: ['REST / OpenAPI', 'GraphQL', 'gRPC / WebSockets', 'OAuth / OIDC / JWT', 'Webhooks / payment integrations', 'Third-party API clients'] },
  { id: "data", roleIds: [...coreReviewRoleIds, "A07", "A10", "A11", "A16"], examples: ["migration.sql", "schema.prisma", "search.json", "redis.conf"], checkIds: ["T65"], title: 'Databases & data systems', group: 'Backend & data', symbol: '▤', description: 'Review schema and migration text, query patterns, data handling and plans for safer changes.', tags: ['PostgreSQL / MySQL / MariaDB', 'SQL Server / SQLite', 'MongoDB', 'Redis', 'Prisma / ORM schemas', 'Elasticsearch / OpenSearch'] },
  { id: "servers", roleIds: [...coreReviewRoleIds, "A04", "A12", "A17", "A22"], examples: ["app.service", "server.conf", "web.config", "incident.log"], checkIds: [], title: 'Servers & operating systems', group: 'Servers & DevOps', symbol: '▣', description: 'Review redacted configuration and incident context for service failures, permissions and maintenance planning.', tags: ['Linux / Ubuntu / Debian', 'RHEL / Rocky / AlmaLinux', 'Windows Server', 'VPS / dedicated servers', 'systemd / service configuration', 'SSH / SFTP access planning'] },
  { id: "routing", roleIds: [...coreReviewRoleIds, "A10", "A12", "A20"], examples: ["nginx.conf", ".htaccess", "web.config", "Caddyfile", "traefik.yaml"], checkIds: ["T67"], title: 'Web servers & traffic routing', group: 'Servers & DevOps', symbol: '↗', description: 'Review configuration excerpts for routing, redirects, proxy behavior, TLS settings and availability concerns.', tags: ['Nginx / Apache', 'IIS / Caddy', 'HAProxy / Traefik', 'Reverse proxies / load balancers', 'DNS / SSL / TLS', 'CDN / Cloudflare configuration'] },
  { id: "cloud", roleIds: [...coreReviewRoleIds, "A06", "A12", "A17"], examples: ["infra/main.tf", "policy.json", "deployment.yaml", "hosting.toml"], checkIds: ["T65", "T67"], title: 'Cloud & hosting infrastructure', group: 'Servers & DevOps', symbol: '☁', description: 'Review supplied infrastructure definitions, access policies and deployment context for reliability and security.', tags: ['AWS', 'Microsoft Azure', 'Google Cloud', 'DigitalOcean / Hetzner', 'Vercel / Netlify', 'cPanel / Plesk / managed hosting'] },
  { id: "containers", roleIds: [...coreReviewRoleIds, "A06", "A12", "A13"], examples: ["Dockerfile", "compose.yaml", "deployment.yml", "infra/main.tf", "values.yaml"], checkIds: ["T67"], title: 'Containers & infrastructure as code', group: 'Servers & DevOps', symbol: '⬡', description: 'Review images, manifests and configuration excerpts for isolation, dependencies, readiness and deployment risks.', tags: ['Docker / Compose', 'Kubernetes / Helm', 'Terraform excerpts', 'Ansible configuration', 'YAML / JSON / TOML', 'Container registries'] },
  { id: "devops", roleIds: [...coreReviewRoleIds, "A06", "A12", "A13", "A16", "A17"], examples: [".github/workflows/ci.yml", "Jenkinsfile", "Makefile", "pipeline.yaml"], checkIds: ["T67"], title: 'DevOps, CI/CD & releases', group: 'Servers & DevOps', symbol: '⟳', description: 'Review pipeline definitions for build failures, permissions, test gates, release steps and rollback prerequisites.', tags: ['GitHub Actions / GitLab CI', 'Jenkins / CircleCI', 'Azure DevOps', 'Argo CD / GitOps', 'Build & package configuration', 'Release / rollback planning'] },
  { id: "security", roleIds: [...coreReviewRoleIds, "A02", "A04", "A06", "A12", "A16", "A17"], examples: ["auth.ts", "policy.json", "incident.log", "recovery.md"], checkIds: ["T19", "T65"], title: 'Security hardening & recovery', group: 'Security & reliability', symbol: '◇', description: 'Review defensive controls and supplied incident evidence; prioritize improvements and specialist-led recovery.', tags: ['Authentication / authorization', 'IAM / least privilege', 'Firewall / WAF configuration', 'Dependency & secret-handling review', 'Incident triage / recovery planning', 'Backup / restore prerequisites'] },
  { id: "observability", roleIds: [...coreReviewRoleIds, "A07", "A10", "A11", "A22", "A23"], examples: ["worker.ts", "metrics.yaml", "query.sql", "incident.log"], checkIds: ["T65", "T67"], title: 'Performance, queues & observability', group: 'Security & reliability', symbol: '⌁', description: 'Find source-level performance hypotheses, review retry patterns and use supplied logs to plan measurements.', tags: ['Caching / CDN strategy', 'RabbitMQ / Kafka / BullMQ', 'Prometheus / Grafana', 'OpenTelemetry / Sentry', 'Logs / metrics / alerting', 'Query / memory / latency review'] }
];
