/** Browser-safe bindings. A binding is implementation evidence, not deployment activation. */
export const workflowToolBindings: Record<string, { entrypoint: string; boundary: string; requirements: string[] }> = {
  T08: { entrypoint: 'POST /jobs/:id/change-plan; POST /websites/:websiteId/reviews', boundary: 'Persist a static HTML or uploaded-source plan; customer approval starts work.', requirements: ['CARE_REPAIR_ENABLED or CARE_REVIEW_ENABLED', 'Configured model and prices', 'Authorized source and budget'] },
  T15: { entrypoint: 'Approved static HTML repair worker → runOneRepair', boundary: 'Package one validated index.html candidate as an encrypted artifact. No general repository commits.', requirements: ['CARE_REPAIR_ENABLED', 'Exact approved static HTML plan', 'Configured provider'] },
  T49: { entrypoint: 'Static HTML repair worker → writeArtifact', boundary: 'Register the validated candidate with SHA-256, creator, job and environment provenance.', requirements: ['CARE_REPAIR_ENABLED', 'Artifact encryption key and quota', 'Validated candidate'] },
  T50: { entrypoint: 'GET /artifacts/:id/content', boundary: 'Authorized retained artifact bytes with integrity validation; no public download URL.', requirements: ['CARE_REPAIR_ENABLED', 'Authorized artifact', 'Artifact decryption key'] },
  T52: { entrypoint: 'GET /artifacts/:id/preview', boundary: 'Return validated static HTML for the private sandboxed preview. No hosted app, scripts, forms or network.', requirements: ['CARE_REPAIR_ENABLED', 'Authorized static HTML artifact'] },
  T54: { entrypoint: 'POST /jobs/:id/releases', boundary: 'Persist a single-file SFTP release proposal bound to the verified candidate, path and account; no deployment.', requirements: ['CARE_REPAIR_ENABLED and CARE_RELEASE_ENABLED', 'Verified candidate/site', 'Current fingerprint-pinned account'] },
  T55: { entrypoint: 'POST /jobs/:id/releases → release.approval_required', boundary: 'Publish the saved release approval card in Care. Separate customer approval and fresh MFA are mandatory.', requirements: ['Same prerequisites as T54', 'Customer must separately approve'] },
  T60: { entrypoint: 'POST /jobs/:id/pause', boundary: 'Persist a stop request and fence future steps. In-flight costs or external effects can remain uncertain.', requirements: ['Nonterminal authorized job'] },
  T61: { entrypoint: 'POST /websites/:websiteId/tickets', boundary: 'Customer submits a screened support request to the human ticket queue. No automatic assignment, secret grant or repair.', requirements: ['tickets.create permission', 'Customer-reviewed, sanitized title and description'] },
  T63: { entrypoint: 'POST /jobs/:id/feedback', boundary: 'Persist repair feedback and invalidate earlier approvals. A new plan is required; old history is retained.', requirements: ['Authorized REPAIR job', 'Sanitized feedback'] },
  T64: { entrypoint: 'POST /jobs/:id/monitoring-plan', boundary: 'Save a monitoring proposal in job history. Does not schedule checks, contact a host or change the live policy.', requirements: ['websites.manage permission', 'Customer must review the proposal', 'Operator configures the approved monitoring policy separately'] }
};
export const limitedToolBoundaries: Record<string, string> = {
  T03: 'Credential types and capability metadata only; never account secrets or live access.',
  T05: 'Bounded persisted source findings and artifact references; no runtime verification.',
  T06: 'Search the bundled, versioned Care policy notes; no external vendor or cross-customer knowledge.',
  T07: 'Read an exact bundled Care policy note revision and provenance.',
  T12: 'Compare hashes and changed paths of two authorized stored artifacts in the same job.',
  T16: 'Check persisted plan version and source digest conflicts; no live Git merge or ownership checks.',
  T17: 'Reviewed JS/TS AST patterns for dynamic evaluation and raw HTML sinks; no data-flow or exploit analysis.',
  T18: 'Versioned defensive configuration line patterns; observations require contextual review.',
  T22: 'Inventory top-level CycloneDX/SPDX JSON declarations; no image extraction or advisory feed.',
  T30: 'Compare custom-property declarations in two supplied CSS files; no rendering or computed cascade.',
  T38: 'Basic OpenAPI 3 JSON structure and reference existence; no full schema or compatibility validation.',
  T45: 'Inventory supplied Prisma declaration names; no live schema connection or customer rows.',
  T47: 'Versioned container and infrastructure text patterns; no live infrastructure changes.',
  T51: 'Compare the exact saved candidate/source hashes and attached static verification.',
  T56: 'Read saved single-file release status; no new post-deployment probe.',
  T57: 'Read bounded Care job/agent/release error codes; no raw logs or telemetry export.',
  T58: 'Read saved production monitoring signals with timestamps and staleness; no live check.',
  T62: 'Prepare a summary from actual retained source reports with artifact references.'
};
export const unavailableToolRequirements: Record<string, string> = {
  T13: 'No disposable multi-file workspace service is provisioned. Needs tenant isolation, quotas, lifecycle cleanup and evaluated execution profiles.',
  T14: 'No general patch workspace exists. Needs approved paths, base digest, conflict checks and isolated candidate storage; static HTML repair is separate.',
  T20: 'No approved advisory dataset/feed adapter is connected. Needs ecosystem/version normalization, freshness, provenance and applicability tests.',
  T23: 'No Care-bound HTTP observation adapter is implemented. Needs fixed verified targets, DNS/redirect/response limits and consent; no arbitrary URL tool.',
  T24: 'No Care-bound TLS adapter is implemented. Needs a fixed verified host, certificate-chain validation and timestamped evaluation.',
  T25: 'No disposable restricted preview browser service is provisioned. Static HTML iframe preview is available through T52.',
  T26: 'Needs T25 plus sanitized browser accessibility-tree extraction and privacy tests.',
  T27: 'Needs T25 plus approved viewports, reliable private-region masking, retention and screenshot evidence tests.',
  T28: 'Needs T25 plus a reviewed journey registry, synthetic fixtures and bounded execution. Customer scripts are not executed.',
  T29: 'Needs approved baseline/candidate screenshots from a reproducible renderer and an evaluated image comparison profile.',
  T33: 'No disposable lint worker/profile registry is provisioned. Needs pinned rules without customer plugins, resource limits and isolation tests.',
  T34: 'No isolated project type-check profile is provisioned. T65 supplies syntax checks only.',
  T35: 'No isolated registered unit-test worker is provisioned. Application CI tests this product; it does not execute uploaded customer tests.',
  T36: 'No isolated integration-test worker with disposable test services is provisioned.',
  T37: 'No isolated reproducible build worker with pinned dependencies and restricted package scripts is provisioned.',
  T39: 'No registered API fixture runner exists. Needs isolated services, synthetic data and explicit expected outcomes.',
  T40: 'No controlled performance-profile runner/baseline store exists. No production load testing is supported.',
  T41: 'No CMS-specific read-only inventory connector is connected or evaluated.',
  T42: 'Needs a supported CMS connector and authenticated trusted package manifests/artifacts. User-supplied files alone do not establish trusted provenance.',
  T43: 'Needs a supported CMS staging connector, exact update approval, compatibility evaluation and recovery evidence.',
  T44: 'Needs a supported commerce sandbox account, registered synthetic checkout journey and proof that real transactions/messages are disabled.',
  T46: 'Needs isolated disposable database profiles, synthetic fixtures and approved migration/recovery checks. No customer database is queried.',
  T48: 'Needs a provider-specific registered fixture adapter and test account configuration. No generic external request runner is available.'
};
