/** Browser-safe, versioned scope. Implemented profiles are not deployment readiness. */
export const VERIFICATION_POLICY = 'offline-verification-v1';
export const verificationProfiles = [
  { id: 'T35', name: 'Node unit tests', file: 'test/unit.test.mjs', boundary: 'Run the supplied Node test file inside an offline disposable container. Built-in Node modules only; no package install or customer shell command.' },
  { id: 'T36', name: 'Node integration tests', file: 'test/integration.test.mjs', boundary: 'Run supplied integration tests with disposable SQLite and loopback services inside the same offline container. No external databases or services.' },
  { id: 'T37', name: 'TypeScript build', file: '*.ts', boundary: 'Compile supplied TypeScript with fixed strict settings and pinned TypeScript 5.9.3; record emitted file hashes. Customer scripts, tsconfig and package installs are ignored.' },
  { id: 'T39', name: 'Local API fixtures', file: 'app/server.mjs + care/api.json', boundary: 'Start the supplied Node server and check explicit synthetic HTTP fixtures on container loopback. No arbitrary external target or redirects.' },
  { id: 'T40', name: 'Baseline performance comparison', file: 'app/server.mjs + care/performance.json', boundary: 'Measure two explicitly selected saved snapshots sequentially with identical GET fixtures, 3 warmups and 20 single-concurrency samples per path. Timings are observations, not production load results.' },
  { id: 'T41', name: 'WordPress snapshot inventory', file: 'wp-includes/version.php; plugin headers; theme style.css', boundary: 'Read WordPress core, plugin and theme declarations through the offline saved-file connector. Does not authenticate to a CMS or prove deployed/active versions.' },
  { id: 'T42', name: 'WordPress trusted-file comparison', file: 'WordPress core snapshot', boundary: 'Compare the supplied core-file subset against an operator-reviewed reference baked into the immutable runner image. Missing reference, paths or version matches block the check; this is not a whole-site integrity verdict.' },
  { id: 'T43', name: 'Prepare WordPress core-file update', file: 'care/wordpress.json + WordPress core snapshot', boundary: 'Prepare a retained candidate for the supplied core-file subset from the trusted image reference, check declared PHP requirements and verify exact source-file restoration. No PHP execution, database upgrade or CMS installation; runtime compatibility remains unverified.' },
  { id: 'T44', name: 'Offline checkout fixture', file: 'app/server.mjs', boundary: 'Exercise the supplied checkout endpoint against a fixed local payment mock: success, duplicate and decline. No real provider account, orders, payments or outgoing messages. Live checkout remains unverified.' },
  { id: 'T46', name: 'SQLite migration and recovery', file: 'database/{setup,seed,migrate}.sql + care/database.json', boundary: 'Apply a migration to a disposable SQLite database with explicit before/after synthetic row assertions; restore the backup and verify original bytes and assertions. Does not certify PostgreSQL/MySQL or customer data migrations.' },
  { id: 'T48', name: 'Payment integration retry fixture', file: 'app/server.mjs', boundary: 'Check the supplied integration endpoint against a registered Stripe-shaped balance mock, including throttling and malformed responses. No live provider requests or credentials.' }
] as const;
export type VerificationToolId = typeof verificationProfiles[number]['id'];
