import type { FastifyPluginAsync, FastifyRequest } from 'fastify';
import type { Queue } from 'bullmq';
import { z } from 'zod';
import type { Environment } from '@zerochack/config';
import { database } from '@zerochack/database';
import { ApiError } from '../../errors.js';
import { authenticate, requireOwnerMfa, requirePermission } from '../auth/security.js';
import { writeAudit } from '../auth/service.js';

const uuid = z.string().uuid();
const ids = z.object({ websiteId: uuid, backupId: uuid });
function parse<T>(schema: z.ZodType<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new ApiError(400, 'VALIDATION_ERROR', 'Request validation failed', result.error.flatten()); return result.data; }
function owner(request: FastifyRequest, permission: string): void { requireOwnerMfa(request); requirePermission(request, permission); }
async function website(tenantId: string, websiteId: string) { const value = await database.website.findFirst({ where: { id: websiteId, tenantId, lifecycle: 'ACTIVE' } }); if (!value) throw new ApiError(404, 'WEBSITE_NOT_FOUND', 'Website was not found'); return value; }

export const operationsRoutes: FastifyPluginAsync<{ environment: Environment; queues?: { backups?: Queue; monitoring?: Queue } }> = async (app, options) => {
  app.addHook('preHandler', async (request) => authenticate(request, options.environment)); app.addHook('onSend', async (_request, reply) => { void reply.header('cache-control', 'private, no-store'); });

  app.get('/websites/:websiteId/operations', async (request) => { requirePermission(request, 'websites.read'); const websiteId = parse(uuid, (request.params as { websiteId?: string }).websiteId); const tenantId = request.tenantId!; await website(tenantId, websiteId); const [backupPolicy, monitoringPolicy, checks, events, alerts, restores] = await Promise.all([database.backupPolicy.findUnique({ where: { websiteId } }), database.monitoringPolicy.findUnique({ where: { websiteId } }), database.monitoringCheck.findMany({ where: { tenantId, websiteId }, orderBy: { startedAt: 'desc' }, take: 50 }), database.securityEvent.findMany({ where: { tenantId, websiteId }, orderBy: { lastSeenAt: 'desc' }, take: 100, include: { evidence: { orderBy: { observedAt: 'desc' }, take: 10 } } }), database.securityAlert.findMany({ where: { tenantId, websiteId }, orderBy: { createdAt: 'desc' }, take: 100 }), database.restoreOperation.findMany({ where: { tenantId, websiteId }, orderBy: { requestedAt: 'desc' }, take: 50 })]); return { backupPolicy, monitoringPolicy: monitoringPolicy ?? { enabled: false, intervalMinutes: 60, alertCooldownMinutes: 60, indicators: {} }, checks, events, alerts, restores }; });

  app.post('/websites/:websiteId/monitoring/checks', async (request, reply) => { requirePermission(request, 'monitoring.manage'); const websiteId = parse(uuid, (request.params as { websiteId?: string }).websiteId); const tenantId = request.tenantId!; await website(tenantId, websiteId); const policy = await database.monitoringPolicy.findFirst({ where: { websiteId, tenantId, enabled: true } }); if (!policy) throw new ApiError(409, 'MONITORING_INACTIVE', 'Enable monitoring before requesting a check'); try { if (!options.queues?.monitoring) throw new Error('queue unavailable'); const job = await options.queues.monitoring.add('monitoring.manual', { tenantId, websiteId }, { jobId: `monitor-${websiteId}-${crypto.randomUUID()}`, removeOnComplete: 1000, removeOnFail: 5000 }); await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: 'monitoring.check_requested', resourceType: 'website', resourceId: websiteId, ipAddress: request.ip, metadata: { jobId: job.id } }); return reply.code(202).send({ queued: true, jobId: job.id }); } catch { throw new ApiError(503, 'SCHEDULER_UNAVAILABLE', 'The monitoring check could not be queued'); } });

  app.post('/websites/:websiteId/backups/:backupId/restore-authorizations', async (request, reply) => { requirePermission(request, 'backups.manage'); const { websiteId, backupId } = parse(ids, request.params); const tenantId = request.tenantId!; await website(tenantId, websiteId); const backup = await database.backup.findFirst({ where: { id: backupId, tenantId, websiteId, status: 'SUCCEEDED', verifiedAt: { not: null }, deletedAt: null } }); if (!backup) throw new ApiError(404, 'BACKUP_NOT_RESTORABLE', 'Verified backup was not found'); const authorization = await database.restoreAuthorization.create({ data: { tenantId, websiteId, backupId, authorizedByUserId: request.userId!, expiresAt: new Date(Date.now() + 10 * 60_000) } }); await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: 'backup.restore_authorized', resourceType: 'backup', resourceId: backupId, ipAddress: request.ip, metadata: { authorizationId: authorization.id, expiresAt: authorization.expiresAt } }); return reply.code(201).send(authorization); });
  app.post('/websites/:websiteId/backups/:backupId/restores', async (request, reply) => { requirePermission(request, 'backups.manage'); const { websiteId, backupId } = parse(ids, request.params); const { authorizationId } = parse(z.object({ authorizationId: uuid }), request.body); const tenantId = request.tenantId!; await website(tenantId, websiteId); const operation = await database.$transaction(async (tx) => { const used = await tx.restoreAuthorization.updateMany({ where: { id: authorizationId, tenantId, websiteId, backupId, usedAt: null, revokedAt: null, expiresAt: { gt: new Date() } }, data: { usedAt: new Date() } }); if (!used.count) throw new ApiError(409, 'RESTORE_AUTHORIZATION_INVALID', 'Restore authorization is invalid, expired, or already used'); const backup = await tx.backup.findFirst({ where: { id: backupId, tenantId, websiteId, status: 'SUCCEEDED', verifiedAt: { not: null }, deletedAt: null } }); if (!backup) throw new ApiError(404, 'BACKUP_NOT_RESTORABLE', 'Verified backup was not found'); return tx.restoreOperation.create({ data: { tenantId, websiteId, backupId, authorizationId } }); }); try { if (!options.queues?.backups) throw new Error('queue unavailable'); await options.queues.backups.add('backup.restore', { action: 'RESTORE', restoreId: operation.id, tenantId, websiteId, backupId }, { jobId: `restore-${operation.id}`, attempts: 1, removeOnComplete: 1000, removeOnFail: 5000 }); } catch { await database.restoreOperation.update({ where: { id: operation.id }, data: { status: 'FAILED', errorCode: 'QUEUE_UNAVAILABLE', completedAt: new Date() } }); throw new ApiError(503, 'QUEUE_UNAVAILABLE', 'Restore could not be queued'); } await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: 'backup.restore_requested', resourceType: 'restore_operation', resourceId: operation.id, ipAddress: request.ip, metadata: { backupId } }); return reply.code(202).send(operation); });
  app.delete('/websites/:websiteId/backups/:backupId', async (request, reply) => { requirePermission(request, 'backups.manage'); const { websiteId, backupId } = parse(ids, request.params); const tenantId = request.tenantId!; await website(tenantId, websiteId); const backup = await database.backup.findFirst({ where: { id: backupId, tenantId, websiteId, status: 'SUCCEEDED', deletedAt: null }, include: { remediationRuns: { take: 1 }, ticket: true } }); if (!backup) throw new ApiError(404, 'BACKUP_NOT_FOUND', 'Backup was not found'); const activeClaim = backup.ticketId ? await database.warrantyClaim.findFirst({ where: { ticketId: backup.ticketId, status: { in: ['SUBMITTED', 'REVIEWING', 'APPROVED'] } } }) : null; if (backup.remediationRuns.length || activeClaim || (backup.ticket && !['RESOLVED', 'CLOSED', 'CANCELLED'].includes(backup.ticket.status)) || (backup.protectedUntil && backup.protectedUntil > new Date()) || (backup.retentionUntil && backup.retentionUntil > new Date())) throw new ApiError(409, 'BACKUP_PROTECTED', 'Backup is protected by retention, remediation, or warranty requirements'); await database.backup.update({ where: { id: backupId }, data: { deleteRequestedAt: new Date() } }); try { if (!options.queues?.backups) throw new Error('queue unavailable'); await options.queues.backups.add('backup.delete', { action: 'DELETE', backupId, tenantId, websiteId }, { jobId: `delete-${backupId}`, attempts: 3, backoff: { type: 'exponential', delay: 5000 }, removeOnComplete: 1000, removeOnFail: 5000 }); } catch { throw new ApiError(503, 'QUEUE_UNAVAILABLE', 'Backup deletion could not be queued'); } await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: 'backup.deletion_requested', resourceType: 'backup', resourceId: backupId, ipAddress: request.ip }); return reply.code(202).send({ queued: true }); });

  app.get('/developer-mode', async (request) => { requirePermission(request, 'developer_mode.manage'); const setting = await database.developerModeSetting.findUnique({ where: { tenantId: request.tenantId! } }); return { enabled: Boolean(setting?.enabled && (!setting.expiresAt || setting.expiresAt > new Date())), expiresAt: setting?.expiresAt ?? null }; });
  app.put('/developer-mode', async (request) => { requirePermission(request, 'developer_mode.manage'); const input = parse(z.object({ enabled: z.boolean(), durationMinutes: z.number().int().min(5).max(1440).default(60) }), request.body); const tenantId = request.tenantId!; const setting = await database.developerModeSetting.upsert({ where: { tenantId }, create: { tenantId, enabled: input.enabled, enabledByUserId: request.userId!, expiresAt: input.enabled ? new Date(Date.now() + input.durationMinutes * 60_000) : null }, update: { enabled: input.enabled, enabledByUserId: request.userId!, enabledAt: new Date(), expiresAt: input.enabled ? new Date(Date.now() + input.durationMinutes * 60_000) : null } }); await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: input.enabled ? 'developer_mode.enabled' : 'developer_mode.disabled', resourceType: 'tenant', resourceId: tenantId, ipAddress: request.ip, metadata: { expiresAt: setting.expiresAt } }); return { enabled: setting.enabled, expiresAt: setting.expiresAt }; });
  app.get('/websites/:websiteId/diagnostics', async (request) => { requirePermission(request, 'developer_mode.manage'); const websiteId = parse(uuid, (request.params as { websiteId?: string }).websiteId); const tenantId = request.tenantId!; await website(tenantId, websiteId); const setting = await database.developerModeSetting.findFirst({ where: { tenantId, enabled: true, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] } }); if (!setting) throw new ApiError(403, 'DEVELOPER_MODE_DISABLED', 'Developer Mode is not active'); const [checks, backups, scans] = await Promise.all([database.monitoringCheck.findMany({ where: { tenantId, websiteId }, orderBy: { startedAt: 'desc' }, take: 20, select: { id: true, jobId: true, status: true, responseTimeMs: true, errorCode: true, startedAt: true, completedAt: true, snapshotHash: true } }), database.backup.findMany({ where: { tenantId, websiteId }, orderBy: { requestedAt: 'desc' }, take: 20, select: { id: true, status: true, purpose: true, providerKey: true, errorCode: true, requestedAt: true, completedAt: true, verifiedAt: true } }), database.scan.findMany({ where: { tenantId, websiteId }, orderBy: { requestedAt: 'desc' }, take: 20, select: { id: true, status: true, engineCount: true, completedEngines: true, errorCode: true, startedAt: true, completedAt: true } })]); await writeAudit({ tenantId, actorUserId: request.userId, requestId: request.id, action: 'developer_mode.diagnostics_read', resourceType: 'website', resourceId: websiteId, ipAddress: request.ip }); return { requestId: request.id, websiteId, workerState: { monitoring: checks[0]?.status ?? 'NO_JOBS', backups: backups[0]?.status ?? 'NO_JOBS', scans: scans[0]?.status ?? 'NO_JOBS' }, monitoringChecks: checks, backupJobs: backups, scanJobs: scans };
  });

  app.put('/owner/operations/websites/:websiteId/monitoring-policy', async (request) => { owner(request, 'monitoring.configure'); const websiteId = parse(uuid, (request.params as { websiteId?: string }).websiteId); const input = parse(z.object({ enabled: z.boolean(), intervalMinutes: z.number().int().min(5).max(10080).default(60), alertCooldownMinutes: z.number().int().min(5).max(10080).default(60), indicators: z.object({ expectedStatus: z.number().int().min(100).max(599).optional(), requiredHeaders: z.array(z.enum(['strict-transport-security', 'content-security-policy', 'x-content-type-options', 'referrer-policy'])).max(4).optional(), integrityHash: z.string().regex(/^[a-f0-9]{64}$/u).optional() }).default({}) }), request.body); const target = await database.website.findUnique({ where: { id: websiteId } }); if (!target) throw new ApiError(404, 'WEBSITE_NOT_FOUND', 'Website was not found'); await database.monitoringPolicy.upsert({ where: { websiteId }, create: { websiteId, tenantId: target.tenantId, ...input }, update: input }); try { if (!options.queues?.monitoring) throw new Error('queue unavailable'); if (input.enabled) await options.queues.monitoring.upsertJobScheduler(`monitor-${websiteId}`, { every: input.intervalMinutes * 60_000 }, { name: 'monitoring.scheduled', data: { websiteId, tenantId: target.tenantId }, opts: { removeOnComplete: 1000, removeOnFail: 5000 } }); else await options.queues.monitoring.removeJobScheduler(`monitor-${websiteId}`); } catch { await database.monitoringPolicy.update({ where: { websiteId }, data: { enabled: false } }); throw new ApiError(503, 'SCHEDULER_UNAVAILABLE', 'Monitoring policy was saved disabled because scheduling failed'); } await database.website.update({ where: { id: websiteId }, data: { monitoringStatus: input.enabled ? 'PENDING' : 'PAUSED' } }); await writeAudit({ tenantId: target.tenantId, actorUserId: request.userId, requestId: request.id, action: 'monitoring.policy_changed', resourceType: 'website', resourceId: websiteId, ipAddress: request.ip, metadata: { intervalMinutes: input.intervalMinutes, cooldownMinutes: input.alertCooldownMinutes, enabled: input.enabled } }); return database.monitoringPolicy.findUnique({ where: { websiteId } }); });
  app.put('/owner/operations/websites/:websiteId/backup-policy', async (request) => { owner(request, 'backups.configure'); const websiteId = parse(uuid, (request.params as { websiteId?: string }).websiteId); const input = parse(z.object({ enabled: z.boolean(), frequencyHours: z.number().int().min(1).max(8760), retentionDays: z.number().int().min(1).max(3650), restorePointLimit: z.number().int().min(1).max(10000) }), request.body); const target = await database.website.findUnique({ where: { id: websiteId } }); if (!target) throw new ApiError(404, 'WEBSITE_NOT_FOUND', 'Website was not found'); await database.backupPolicy.upsert({ where: { websiteId }, create: { websiteId, tenantId: target.tenantId, ...input }, update: input }); try { if (!options.queues?.backups) throw new Error('queue unavailable'); if (input.enabled) { await options.queues.backups.upsertJobScheduler(`backup-${websiteId}`, { every: input.frequencyHours * 3_600_000 }, { name: 'backup.scheduled', data: { action: 'CREATE', websiteId, tenantId: target.tenantId }, opts: { removeOnComplete: 1000, removeOnFail: 5000 } }); await options.queues.backups.upsertJobScheduler(`retention-${websiteId}`, { every: 86_400_000 }, { name: 'backup.retention', data: { action: 'RETENTION', websiteId, tenantId: target.tenantId }, opts: { removeOnComplete: 1000, removeOnFail: 5000 } }); } else { await options.queues.backups.removeJobScheduler(`backup-${websiteId}`); await options.queues.backups.removeJobScheduler(`retention-${websiteId}`); } } catch { await database.backupPolicy.update({ where: { websiteId }, data: { enabled: false } }); throw new ApiError(503, 'SCHEDULER_UNAVAILABLE', 'Backup policy was saved disabled because scheduling failed'); } await database.website.update({ where: { id: websiteId }, data: { backupStatus: input.enabled ? 'PENDING' : 'PAUSED' } }); await writeAudit({ tenantId: target.tenantId, actorUserId: request.userId, requestId: request.id, action: 'backup.policy_changed', resourceType: 'website', resourceId: websiteId, ipAddress: request.ip, metadata: input }); return database.backupPolicy.findUnique({ where: { websiteId } }); });
  app.patch('/operations/alerts/:alertId', async (request) => { requirePermission(request, 'alerts.manage'); const alertId = parse(uuid, (request.params as { alertId?: string }).alertId); const { status } = parse(z.object({ status: z.enum(['ACKNOWLEDGED', 'RESOLVED']) }), request.body); const alert = request.roleNames?.includes('Owner') ? await database.securityAlert.findUnique({ where: { id: alertId } }) : await database.securityAlert.findFirst({ where: { id: alertId, tenantId: request.tenantId! } }); if (!alert) throw new ApiError(404, 'ALERT_NOT_FOUND', 'Security alert was not found'); const updated = await database.securityAlert.update({ where: { id: alertId }, data: { status } }); if (status === 'RESOLVED') await database.securityEvent.updateMany({ where: { id: alert.eventId, tenantId: alert.tenantId, websiteId: alert.websiteId }, data: { status: 'RESOLVED', resolvedAt: new Date() } }); await writeAudit({ tenantId: alert.tenantId, actorUserId: request.userId, requestId: request.id, action: 'monitoring.alert_changed', resourceType: 'security_alert', resourceId: alertId, ipAddress: request.ip, metadata: { status } }); return updated; });
};
